import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {join} from 'node:path';
import type {SuasData,Unit} from '@/lib/eficiencia/assistencia/dados';
import contrato from '@/lib/eficiencia/escores/contrato.json';
import anterior from '@/lib/eficiencia/escores/contrato-v0.3.json';
import {CESTA,escoreCapitulo,escoreAgregado} from '@/lib/eficiencia/escores/calculo';
const json=(p:string)=>JSON.parse(readFileSync(join(process.cwd(),p),'utf8'));
const g=json('public/eficiencia/assistencia-social/panorama.json') as SuasData;
const seed=JSON.parse(gunzipSync(readFileSync(join(process.cwd(),'pipeline/assistencia/seed/recorte.json.gz'))).toString()) as {units:Unit[];monthly:(string|number|null)[][]};
describe('Assistência: registros, derivação e edição',()=>{
 it('reconcilia todos os arquivos por UF com o seed e não omite redes regionais',()=>{let units=0,rma=0;for(const uf of g.ufs){const p=json(`public/eficiencia/assistencia-social/uf-${uf}.json`);units+=p.units.length;rma+=p.monthly.length;expect(p.units).toEqual(seed.units.filter(u=>u.uf===uf));expect(p.monthly).toEqual(seed.monthly.filter(r=>r[2]===uf));}expect(units).toBe(14050);expect(rma).toBe(103847);expect(seed.units.filter(u=>u.scope==='Regional')).toHaveLength(36);expect(seed.units.filter(u=>u.scope==='Estadual')).toHaveLength(5)});
 it('reconcilia percentuais, mediana cadastral e somas com os mesmos universos',()=>{for(const c of g.catalog.filter(c=>c.kind!=='RMA')){const us=seed.units.filter(u=>u.kind===c.kind),obs=us.map(u=>u.values[c.variable]).filter(v=>v.status==='OBSERVADO');const s=g.stats.Brasil.metrics[c.id];expect(s.total).toBe(us.length);expect(s.observed).toBe(obs.length);expect(s.total).toBe(s.observed+s.missing+s.notApplicable);for(const category of s.categories){expect(category.count).toBe(obs.filter(v=>v.value===category.label).length);expect(category.percent).toBeCloseTo(100*category.count/obs.length)}if(c.unit==='contagem')expect(s.sum).toBe(obs.length?obs.reduce((a,v)=>a+Number(v.value),0):null);}const wait=seed.units.filter(u=>u.kind==='CRAS').map(u=>u.values.q51_1).filter(v=>v.status==='OBSERVADO').map(v=>Number(v.value)).sort((a,b)=>a-b);const n=wait.length;expect(g.stats.Brasil.metrics['CRAS.q51_1'].median).toBe(n%2?wait[(n-1)/2]:(wait[n/2-1]+wait[n/2])/2);expect(wait).toContain(0)});
 it('RMA mensal usa valores tratados e mostra os originais alterados sem somar estoques anuais',()=>{for(const month of g.stats.Brasil.monthly){const rows=seed.monthly.filter(r=>r[3]===month.month);for(const [k,index] of [['a1',4],['a2',6],['c1',8],['c5',10]] as const){const obs=rows.filter(r=>r[index]!==null),s=month.values[k];expect(s.total).toBe(rows.length);expect(s.observed).toBe(obs.length);expect(s.sum).toBe(obs.length?obs.reduce((a,r)=>a+Number(r[index]),0):null);expect(s.changed).toBe(rows.filter(r=>r[index]!==r[index+1]).length)}}});
 it('csvs incluem todo o recorte, ausências, valores originais e competência',()=>{const unitCsv=readFileSync(join(process.cwd(),'public/eficiencia/assistencia-social/unidades.csv'),'utf8');expect(unitCsv.split('\r\n').filter(Boolean)).toHaveLength(seed.units.reduce((s,u)=>s+Object.keys(u.values).length,0)+1);expect(unitCsv).toContain('NAO_APLICAVEL');expect(unitCsv).toContain('Regional');const rma=readFileSync(join(process.cwd(),'public/eficiencia/assistencia-social/rma-cras.csv'),'utf8');expect(rma.split('\r\n').filter(Boolean)).toHaveLength(103848);expect(rma).toContain('a1_original')});
 it('inclui o quinto capítulo sem reponderar a cesta anterior e bloqueia nota incompleta',()=>{expect(anterior.basket).toHaveLength(4);expect(contrato.basket).toEqual(CESTA);expect(contrato.basket).toHaveLength(5);const context={edicao:contrato.edition,territorio:'Brasil',periodo:'2025'};const cap=Object.fromEntries(anterior.basket.map(id=>[id,escoreCapitulo({acesso:80,resposta:80,qualidade:80},true,context)]));expect(escoreAgregado(cap,contrato.edition,true).valor).toBeNull();const memory=json('public/eficiencia/assistencia-social/memoria-escore.json');expect(memory.value).toBeNull();expect(memory.capacity_is_not_service_quality).toBe(true)});
});
