import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import type {SnapshotAlimentar} from '@/lib/eficiencia/seguranca-alimentar/tipos';
import {csvAlimentar,numeroIndicadorAlimentar,rotuloDimensaoAlimentar,diaCapturaAlimentar} from '@/lib/eficiencia/seguranca-alimentar/apresentacao';
import {partesCsvAlimentar,streamCsvAlimentar} from '@/lib/eficiencia/seguranca-alimentar/csv';
import {ComposicaoEbia,SerieAlimentar} from '@/components/eficiencia/seguranca-alimentar/FigurasAlimentares';
import {ComplementoMunicipalAlimentar} from '@/components/eficiencia/seguranca-alimentar/ComplementoMunicipalAlimentar';
import {GET} from '@/app/eficiencia-estatal/seguranca-alimentar/dados.csv/route';
const base=(arquivo:string)=>JSON.parse(readFileSync('public/eficiencia/seguranca-alimentar/'+arquivo,'utf8')) as SnapshotAlimentar;
async function textoStream(stream:ReadableStream<Uint8Array>){const reader=stream.getReader();const decoder=new TextDecoder('utf-8',{ignoreBOM:true});let texto='';while(true){const parte=await reader.read();if(parte.done)break;texto+=decoder.decode(parte.value,{stream:true});}return texto+decoder.decode();}
describe('contratos analíticos e exportação da segurança alimentar',()=>{
 it('a composição completa usa o mesmo território, dimensão, grupo e ano sem preencher uma classe ausente',()=>{const dados=base('snapshot.json');const props={dados,territorio:'1',dimensao:'total',grupo:'Total',periodos:['2024']};const completo=renderToStaticMarkup(createElement(ComposicaoEbia,props));expect(completo).toContain('saa-composicao-barra');expect(completo).toContain('Insegurança grave');const faltante={...dados,observacoes:dados.observacoes.filter(o=>!(o.territorioId==='1'&&o.periodo==='2024'&&o.indicadorId==='ebia-grave'&&o.dimensao==='total'))};const html=renderToStaticMarkup(createElement(ComposicaoEbia,{...props,dados:faltante}));expect(html).not.toContain('class="saa-composicao-barra"');expect(html).toContain('não está disponível');});
 it('o exercício parcial do PNAE fica separado da linha dos anos encerrados',()=>{const dados=base('escolar.json');const pontos=dados.observacoes.filter(o=>o.indicadorId==='pnae-repasses'&&o.territorioId==='1'&&o.grupo==='Conjunto das redes'&&['2024','2025','2026'].includes(o.periodo));const html=renderToStaticMarkup(createElement(SerieAlimentar,{pontos,unidade:'R$',periodo:'2025',parciais:['2026']}));const path=html.match(/<path d="([^"]+)"/)!;expect(path[1].match(/M/g)).toHaveLength(2);expect(html).toContain('fill="var(--cor-superficie)"');});
 it('o IPCA preserva centésimos no valor principal e a exportação preserva nota, fórmula e denominadores',()=>{expect(numeroIndicadorAlimentar(4.18,{id:'ipca-7170-2265',unidade:'%'})).toBe('4,18%');const dados=base('snapshot.json');const obs=dados.observacoes.find(o=>o.status==='calculado')!;const csv=csvAlimentar(dados,[obs]);expect(csv).toContain('numerador');expect(csv).toContain('denominador');expect(csv).toContain('formula');expect(csv).toContain(obs.formula!);expect(csv).toContain(obs.nota!);});
 it('CSV progressivo de toda a base EBIA preserva exatamente bytes, ordem e todos os registros',async()=>{const dados=base('snapshot.json');const esperado=csvAlimentar(dados,dados.observacoes);expect(await textoStream(streamCsvAlimentar(dados))).toBe(esperado);expect(Array.from(partesCsvAlimentar(dados))).toHaveLength(1+Math.ceil(dados.observacoes.length/250));expect(esperado.match(/\uFEFF/g)).toHaveLength(1);});
 it('o capítulo MUNIC conserva seu ano próprio mesmo quando o PAA seleciona 2025',()=>{const dados=base('aquisicao.json');const html=renderToStaticMarkup(createElement(ComplementoMunicipalAlimentar,{dados,territorio:'1'}));expect(html).toContain('referência 2023');expect(html).toContain('3.040');expect(html).toContain('Soma das respostas municipais conhecidas');expect(html).not.toContain('referência 2025');});
 it('o rótulo do total respeita o universo da medida, sem chamar famílias cadastradas de domicílios',()=>{expect(rotuloDimensaoAlimentar('total','ebia-grave')).toBe('Total dos domicílios');expect(rotuloDimensaoAlimentar('total','cadinsan-risco-familias')).toBe('Famílias cadastradas analisadas');expect(rotuloDimensaoAlimentar('total','munic-paa')).toBe('Declarações municipais');expect(rotuloDimensaoAlimentar('total','paa-fornecedores')).toBe('Registros do programa');});
 it('a captura cruza a meia-noite UTC sem alterar a data civil de Brasília nem períodos anuais',()=>{expect(diaCapturaAlimentar('2026-10-10T00:30:00Z')).toBe('09/10/2026');expect(diaCapturaAlimentar('2026-10-10T03:30:00Z')).toBe('10/10/2026');expect(diaCapturaAlimentar('2026-10-09T21:30:00-03:00')).toBe('09/10/2026');});
 it('a rota filtra a fonte oficial sem truncar e rejeita nomes externos ao catálogo',async()=>{const dados=base('snapshot.json');const observacoes=dados.observacoes.filter(o=>o.territorioId==='1'&&o.indicadorId==='ebia-grave'&&o.dimensao==='sexo-responsavel');const response=await GET(new Request('http://localhost/eficiencia-estatal/seguranca-alimentar/dados.csv?base=snapshot.json&ter=1&med=ebia-grave&dim=sexo-responsavel'));expect(await textoStream(response.body!)).toBe(csvAlimentar(dados,observacoes));expect(response.headers.has('content-length')).toBe(false);expect((await GET(new Request('http://localhost/dados.csv?base=../../arquivo'))).status).toBe(400);});
});
