import {describe,it,expect} from 'vitest';
import {consultaCursos,csvCursos,streamCsvCursos,type Curso} from '@/lib/eficiencia/trabalho-renda/cursos';
import {GET} from '@/app/eficiencia-estatal/trabalho-renda/qualificacao/dados.csv/route';
async function textoStream(stream:ReadableStream<Uint8Array>){const reader=stream.getReader();const decoder=new TextDecoder('utf-8',{ignoreBOM:true});let texto='';let blocos=0;while(true){const {done,value}=await reader.read();if(done)break;texto+=decoder.decode(value,{stream:true});blocos++;}texto+=decoder.decode();return {texto,blocos};}
describe('CSV progressivo de cursos',()=>{
 it('o recorte nacional completo mantém byte a byte a serialização, a ordem, BOM e cabeçalho únicos',async()=>{const {selecionados}=consultaCursos({status:'todos'});expect(selecionados.length).toBeGreaterThan(90000);const referencia=csvCursos(selecionados);const {texto,blocos}=await textoStream(streamCsvCursos(selecionados));expect(texto).toBe(referencia);expect(blocos).toBe(1+Math.ceil(selecionados.length/250));expect(texto.match(/\uFEFF/g)).toHaveLength(1);expect(texto.match(/"Código do curso"/g)).toHaveLength(1);},20000);
 it('104 registros filtrados atravessam fronteiras de bloco sem truncamento, inclusive aspas e quebras em campos',async()=>{const {selecionados}=consultaCursos({uf:'SP',status:'vigente',q:'Sumaré',modalidade:'Presencial'});expect(selecionados).toHaveLength(104);const recorte=selecionados.map((c,i)=>i===53?{...c,nome:'Curso "especial"; com\r\nquebra'}:c) as Curso[];expect(recorte).toHaveLength(104);const {texto,blocos}=await textoStream(streamCsvCursos(recorte,100));expect(texto).toBe(csvCursos(recorte));expect(blocos).toBe(3);expect(texto).toContain('"Curso ""especial""; com\r\nquebra"');expect(texto).toContain('"'+recorte.at(-1)!.id+'"');});
 it('a rota preserva o filtro integral e entrega um corpo em stream sem Content-Length',async()=>{const filtro={uf:'SP',status:'vigente',q:'Sumaré',modalidade:'Presencial'};const {selecionados}=consultaCursos(filtro);expect(selecionados).toHaveLength(104);const response=GET(new Request('http://localhost/eficiencia-estatal/trabalho-renda/qualificacao/dados.csv?'+new URLSearchParams(filtro)));expect(response.headers.get('content-type')).toContain('text/csv');expect(response.headers.has('content-length')).toBe(false);expect(response.body).not.toBeNull();const {texto}=await textoStream(response.body!);expect(texto).toBe(csvCursos(selecionados));});
 it('um recorte vazio exporta somente BOM e cabeçalho, sem inventar linha de dados',async()=>{const {texto,blocos}=await textoStream(streamCsvCursos([]));expect(texto).toBe(csvCursos([]));expect(blocos).toBe(1);expect(texto).not.toContain('\r\n');});
});
