import Link from "next/link";
import contrato from "@/lib/eficiencia/escores/contrato.json";
const rotas: Record<string,string> = { education:"educacao-municipal-capitais", health:"saude-capitais", work:"trabalho-renda", food:"seguranca-alimentar", assistance:"assistencia-social" };
const nomes: Record<string,string> = { access:"Acesso", response:"Resposta e continuidade", quality:"Qualidade da entrega" };
export function EscoresServicos({ capitulo }: { capitulo?: string }) {
  const capitulos = contrato.chapters.filter(c => !capitulo || c.id === capitulo);
  return <section id="escores-servicos" aria-labelledby={`titulo-escores-${capitulo ?? "geral"}`} className="my-10 scroll-mt-6 border-y border-linha py-7">
    <p className="rotulo text-obee">Qualidade dos serviços públicos · proposta experimental</p>
    <h2 id={`titulo-escores-${capitulo ?? "geral"}`} className="mt-2 font-serif text-2xl md:text-3xl">{capitulo ? "Como avaliar este serviço?" : "Um panorama dos escores de cada capítulo."}</h2>
    <p className="mt-3 max-w-prose2 text-sm leading-relaxed text-carvao-muted">Escala proposta de 0 a 100: acesso, resposta e qualidade da entrega. Os escores ainda não são calculáveis. Faltam cobertura dos três componentes e referências validadas; ter dados publicados não equivale a ter um escore de serviço.</p>
    {!capitulo && <p className="mt-4 font-serif text-xl">Escore agregado: não calculável <span className="font-sans text-sm text-carvao-muted">· cesta fixa de {contrato.basket.length} capítulos, edição experimental v0.4</span></p>}
    <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="pb-3 text-left text-xs text-carvao-muted">Situação do cálculo nesta edição; ausência não recebe nota zero.</caption><thead><tr className="border-b border-linha">{["Capítulo","Acesso","Resposta","Qualidade","Escore"].map(n => <th key={n} scope="col" className="px-3 py-3 font-medium">{n}</th>)}</tr></thead><tbody>{capitulos.map(c => <tr key={c.id} className="border-b border-linha"><th scope="row" className="px-3 py-4 font-medium"><Link href={`/eficiencia-estatal/${rotas[c.id]}`} className="text-obee-dark underline underline-offset-4">{c.name}</Link></th>{["Acesso","Resposta","Qualidade"].map(n => <td key={n} className="px-3 py-4 text-carvao-muted">Pendente</td>)}<td className="whitespace-nowrap px-3 py-4">Não calculável</td></tr>)}</tbody></table></div>
    <div className="mt-4 space-y-3">{capitulos.map(c => <details key={c.id} className="border-b border-linha py-2"><summary className="flex min-h-[44px] cursor-pointer items-center font-medium">{c.name}: critérios, dados e lacunas</summary><div className="pb-4 text-sm leading-relaxed"><dl className="mt-3 grid gap-4 md:grid-cols-3">{Object.entries(c.pillars).map(([k,v]) => <div key={k}><dt className="font-semibold">{nomes[k]}</dt><dd className="mt-1 text-carvao-muted">{v}.</dd></div>)}</dl><p className="mt-4">{c.review}</p><p className="mt-3"><strong>Cobertura da avaliação:</strong> {c.id === "work" ? "As séries de condições de trabalho e renda estão no capítulo; atendimento, continuidade e resultados atribuíveis aos serviços ainda não completam a avaliação." : c.available}</p></div></details>)}</div>
    <p className="mt-4 max-w-prose2 text-xs leading-relaxed text-carvao-muted">Proposta: média geométrica dos três pilares com pesos iguais e, depois, dos {contrato.basket.length} capítulos completos. Ausências bloqueiam o cálculo e os pesos não são redistribuídos. Um zero válido produz zero. Território e períodos precisam ser compatíveis; capítulos novos exigem nova edição e recálculo histórico. Gastos e equipamentos são contexto; equidade acompanha os componentes e satisfação exige pesquisa própria.</p>
    <Link href="/eficiencia-estatal/seguranca-alimentar/metodos" className="mt-3 inline-flex min-h-[44px] items-center text-sm text-obee-dark underline underline-offset-4">Metodologia, referências e memória de cálculo →</Link>
  </section>;
}
