'use client';
import {useId,useState} from 'react';
import type {Metric,Summary} from '@/lib/eficiencia/assistencia/dados';
const fmt=(v:number|null)=>v===null?'Não informado':v.toLocaleString('pt-BR',{maximumFractionDigits:1});
export function DistribuicaoSuas({metrics,stats,ufs}:{metrics:Metric[];stats:Record<string,Record<string,Summary>>;ufs:string[]}){
 const id=useId();const [scope,setScope]=useState('Brasil'),[metric,setMetric]=useState(metrics[0].id);const ficha=metrics.find(m=>m.id===metric)!;const s=stats[scope][metric];
 return <section className="mt-7 border-t border-linha pt-6" aria-labelledby={`${id}-title`}><h2 id={`${id}-title`} className="font-serif text-2xl">Compare as respostas da rede.</h2><div className="mt-5 flex flex-wrap gap-4"><label className="text-sm" htmlFor={`${id}-uf`}>Território<select id={`${id}-uf`} value={scope} onChange={e=>setScope(e.target.value)} className="mt-2 block min-h-[44px] border border-carvao-muted bg-superficie px-3"><option>Brasil</option>{ufs.map(uf=><option key={uf}>{uf}</option>)}</select></label><label className="min-w-0 max-w-full text-sm" htmlFor={`${id}-metric`}>Medida e tipo de unidade<select id={`${id}-metric`} value={metric} onChange={e=>setMetric(e.target.value)} className="mt-2 block min-h-[44px] w-full max-w-full border border-carvao-muted bg-superficie px-3">{metrics.map(m=><option key={m.id} value={m.id}>{m.kind} · {m.name}</option>)}</select></label></div><p className="mt-5 text-sm font-medium">{ficha.kind} · {scope} · {ficha.period}</p><p className="mt-2 max-w-prose2 text-sm text-carvao-muted">{fmt(s.observed)} respostas observadas de {fmt(s.total)} unidades: {fmt(s.missing)} não informadas e {fmt(s.notApplicable)} não aplicáveis. Fonte: {ficha.source}. Inclui unidades regionais ou estaduais quando presentes; a seleção é pela UF da rede.</p>
 {s.categories.length>0?<><figure className="mt-6" aria-label={`${ficha.name}; percentuais entre respostas observadas, escala de zero a cem`}><figcaption className="mb-5 text-sm">{ficha.name} · % das respostas observadas</figcaption><div className="space-y-5">{s.categories.map(c=><div key={c.label}><div className="flex items-start justify-between gap-4 text-sm"><span className="max-w-prose2">{c.label}</span><span className="shrink-0 tabular-nums">{fmt(c.percent)}%</span></div><div className="mt-2 h-3 bg-marfim" aria-hidden="true"><div className="h-3 bg-obee" style={{width:c.percent+'%'}}/></div></div>)}</div><p className="mt-3 text-xs text-carvao-muted">Escala comum de 0 a 100%. Não é escore de serviço.</p></figure><details className="mt-5 border-y border-linha py-3"><summary className="flex min-h-[44px] cursor-pointer items-center text-sm font-medium">Tabela equivalente e denominadores</summary><div className="overflow-x-auto"><table className="mt-3 w-full text-left text-sm"><caption className="pb-3 text-left">{ficha.name} · {ficha.period} · {scope}</caption><thead><tr><th scope="col" className="py-3">Resposta</th><th scope="col" className="px-3 text-right">Unidades</th><th scope="col" className="px-3 text-right">% observado</th></tr></thead><tbody>{s.categories.map(c=><tr key={c.label} className="border-t border-linha"><th scope="row" className="py-3 font-normal">{c.label}</th><td className="px-3 text-right tabular-nums">{fmt(c.count)}</td><td className="px-3 text-right tabular-nums">{fmt(c.percent)}%</td></tr>)}</tbody></table></div></details></>:<dl className="mt-6 grid gap-5 border-y border-linha py-5 sm:grid-cols-2">{ficha.unit!=='dias'&&<div><dt className="text-sm">Soma das contagens observadas nas unidades</dt><dd className="mt-2 font-serif text-3xl">{fmt(s.sum)}</dd><dd className="mt-2 text-xs text-carvao-muted">Pode haver pessoas ou vínculos em mais de uma unidade. Não é cobertura populacional.</dd></div>}<div><dt className="text-sm">Mediana entre respostas observadas</dt><dd className="mt-2 font-serif text-3xl">{fmt(s.median)} {ficha.unit==='dias'?'dias':''}</dd><dd className="mt-2 text-xs text-carvao-muted">Referência descritiva do recorte, sem interpretação de meta.</dd></div></dl>}
 {s.observed===0&&<p className="mt-4 text-sm" role="status">Não há respostas observadas para esta medida neste recorte.</p>}<p className="mt-5 max-w-prose2 text-sm leading-relaxed text-carvao-muted">{ficha.limitations}</p><a href="/eficiencia/assistencia-social/unidades.csv" download className="mt-4 inline-flex min-h-[44px] items-center text-sm text-obee-dark underline">Baixar recorte nacional completo, todas as variáveis · CSV ↓</a></section>
}
