'use client';
import {useEffect,useId,useMemo,useState} from 'react';
import type {Metric,Unit} from '@/lib/eficiencia/assistencia/dados';
type Payload={units:Unit[];monthly:(string|number|null)[][]};
const labels:Record<string,string>={OBSERVADO:'Observado',NAO_INFORMADO:'Não informado',NAO_APLICAVEL:'Não aplicável'};
const fmt=(v:string|number|null|undefined)=>v===null||v===undefined?'Não informado':typeof v==='number'?v.toLocaleString('pt-BR'):v;
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function ExploradorSuas({catalog,ufs}:{catalog:Metric[];ufs:string[]}){
 const id=useId();const [uf,setUf]=useState(''),[source,setSource]=useState('Censo'),[metric,setMetric]=useState('CRAS.q9_1'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[month,setMonth]=useState(''),[retry,setRetry]=useState(0);const [payload,setPayload]=useState<Payload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{setPayload(null);setError('');if(!uf){setLoading(false);return;}const abort=new AbortController();setLoading(true);fetch(`/eficiencia/assistencia-social/uf-${uf}.json`,{signal:abort.signal}).then(async r=>{if(!r.ok)throw Error('HTTP '+r.status);const p=await r.json();if(!Array.isArray(p.units)||!Array.isArray(p.monthly))throw Error('Arquivo inesperado');setPayload(p);}).catch(e=>{if(e.name!=='AbortError')setError('Não foi possível carregar os dados desta UF.');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return ()=>abort.abort();},[uf,retry]);
 const ficha=catalog.find(c=>c.id===metric)!;
 const rows=useMemo(()=>{if(!payload)return [];const q=normalize(query);if(source==='Censo')return payload.units.filter(u=>u.kind===ficha.kind&&normalize([u.city,u.code,u.id].join(' ')).includes(q)).map(u=>({key:u.kind+u.id,city:u.city,code:u.code,id:u.id,scope:u.scope,period:ficha.period,value:u.values[ficha.variable]?.value,raw:u.values[ficha.variable]?.raw,status:labels[u.values[ficha.variable]?.status]??'Não informado'}));const index={a1:4,a2:6,c1:8,c5:10}[ficha.variable as 'a1'|'a2'|'c1'|'c5'];const cities=new Map(payload.units.filter(u=>u.code).map(u=>[u.code,u.city]));return payload.monthly.filter(r=>(!month||String(r[3])===month)&&normalize([r[0],r[1],cities.get(String(r[1]))].join(' ')).includes(q)).map(r=>({key:String(r[0])+':'+r[3],city:cities.get(String(r[1]))??'Nome não ligado ao Censo',code:String(r[1]),id:String(r[0]),scope:'RMA CRAS',period:String(r[3]).padStart(2,'0')+'/2025',value:r[index],raw:r[index+1],status:r[index]===null?'Não informado na base tratada':'Observado'}));},[payload,query,source,ficha,month]);
 const pages=Math.ceil(rows.length/50);const current=Math.min(page,Math.max(0,pages-1));
 const changeSource=(s:string)=>{setSource(s);setMetric(s==='Censo'?'CRAS.q9_1':'RMA.a1');setPage(0);};
 return <section className="mt-7"><div className="flex flex-wrap gap-4 border-y border-linha py-5"><label className="text-sm" htmlFor={`${id}-s`}>Base<select id={`${id}-s`} value={source} onChange={e=>changeSource(e.target.value)} className="mt-2 block min-h-[44px] border border-carvao-muted bg-superficie px-3"><option>Censo</option><option>RMA</option></select></label><label className="text-sm" htmlFor={`${id}-uf`}>UF<select id={`${id}-uf`} value={uf} onChange={e=>{setUf(e.target.value);setPage(0);}} className="mt-2 block min-h-[44px] border border-carvao-muted bg-superficie px-3"><option value="">Selecione uma UF</option>{ufs.map(u=><option key={u}>{u}</option>)}</select></label><label className="max-w-full text-sm" htmlFor={`${id}-var`}>Variável<select id={`${id}-var`} value={metric} onChange={e=>{setMetric(e.target.value);setPage(0);}} className="mt-2 block min-h-[44px] w-full border border-carvao-muted bg-superficie px-3">{catalog.filter(c=>source==='RMA'?c.kind==='RMA':c.kind!=='RMA').map(c=><option key={c.id} value={c.id}>{c.kind} · {c.name}</option>)}</select></label><label className="text-sm" htmlFor={`${id}-q`}>Município, código IBGE ou unidade<input id={`${id}-q`} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} className="mt-2 block min-h-[44px] max-w-full border border-carvao-muted bg-superficie px-3" type="search"/></label>{source==='RMA'&&<label className="text-sm" htmlFor={`${id}-month`}>Mês de 2025<select id={`${id}-month`} value={month} onChange={e=>{setMonth(e.target.value);setPage(0);}} className="mt-2 block min-h-[44px] border border-carvao-muted bg-superficie px-3"><option value="">Todos os meses</option>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{String(i+1).padStart(2,'0')}</option>)}</select></label>}</div>
 <p className="mt-5 max-w-prose2 text-sm leading-relaxed">{ficha.definition}. {ficha.period}. Fonte: {ficha.source}. {ficha.limitations}</p><p className="mt-3 text-sm" role="status">{loading?'Carregando a UF…':!uf?'Selecione uma UF para consultar os registros.':error||`${rows.length.toLocaleString('pt-BR')} registros no recorte; até 50 por página.`}</p>{error&&<button type="button" onClick={()=>setRetry(x=>x+1)} className="mt-3 min-h-[44px] border border-carvao-muted px-4 text-sm">Tentar novamente</button>}
 {payload&&<><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="pb-3 text-left">{ficha.name} · {uf} · página {current+1} de {pages||1}. Role a tabela para ver todas as colunas.</caption><thead><tr>{['Município / rede','Código IBGE','Unidade','Competência / base','Período','Valor padronizado / tratado','Valor original','Situação'].map(n=><th key={n} scope="col" className="px-3 py-3 font-medium">{n}</th>)}</tr></thead><tbody>{rows.slice(current*50,(current+1)*50).map(r=><tr key={r.key} className="border-t border-linha"><th scope="row" className="px-3 py-3 font-normal">{r.city}</th><td className="px-3">{r.code??'Não municipal'}</td><td className="px-3 tabular-nums">{r.id}</td><td className="px-3">{r.scope}</td><td className="whitespace-nowrap px-3">{r.period}</td><td className="px-3">{fmt(r.value)}</td><td className="px-3">{fmt(r.raw)}</td><td className="px-3">{r.status}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="mt-4 text-sm">Nenhum registro corresponde à seleção. Limpe a busca ou escolha outra variável.</p>}<div className="mt-4 flex flex-wrap items-center gap-4"><button type="button" disabled={current===0} onClick={()=>setPage(current-1)} className="min-h-[44px] border border-carvao-muted px-4 disabled:opacity-50">Anterior</button><span className="text-sm">{current+1} / {pages||1}</span><button type="button" disabled={current+1>=pages} onClick={()=>setPage(current+1)} className="min-h-[44px] border border-carvao-muted px-4 disabled:opacity-50">Próxima</button></div></>}
 <a href={`/eficiencia/assistencia-social/${source==='Censo'?'unidades':'rma-cras'}.csv`} download className="mt-5 inline-flex min-h-[44px] items-center text-sm text-obee-dark underline">Baixar recorte nacional completo, todas as variáveis · CSV ↓</a><p className="mt-2 text-xs text-carvao-muted">O download inclui todos os registros integrados desta base, sem o filtro ou a paginação da tela.</p></section>
}
