import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {PAGINAS_ALIMENTARES,type SlugAlimentar} from '@/lib/eficiencia/seguranca-alimentar/paginas';
import type {SnapshotAlimentar} from '@/lib/eficiencia/seguranca-alimentar/tipos';
import {PainelAlimentar,EscopoAlimentar} from './PainelAlimentar';
import type {MalhaAlimentar} from './MapaAlimentar';
import {MetodosAlimentares} from './MetodosAlimentares';
const pasta=path.join(process.cwd(),'public/eficiencia/seguranca-alimentar');
export async function PaginaAlimentar({slug,base}:{slug:SlugAlimentar;base?:string}){const config=PAGINAS_ALIMENTARES.find(p=>p.slug===slug)!;const permitidos=slug==='territorios'?['snapshot.json','cadinsan.json','aquisicao.json']:slug==='comparar'?['snapshot.json','cadinsan.json','sisan.json','aquisicao.json','paa.json','precos.json','escolar.json','saude.json']:[];const arquivo=permitidos.includes(base??'')?base!:config.arquivo;if(slug==='metodos'){const arquivos=Array.from(new Set([...PAGINAS_ALIMENTARES.map(p=>p.arquivo),'cadinsan.json','aquisicao.json']));const resultados=await Promise.all(arquivos.map(async arquivo=>{try{return {arquivo,dados:JSON.parse(await readFile(path.join(pasta,'indices',arquivo),'utf8')) as SnapshotAlimentar}}catch{return null}}));return <MetodosAlimentares bases={resultados.filter((b):b is NonNullable<typeof b>=>b!==null)}/>;}let dados:SnapshotAlimentar;try{dados=JSON.parse(await readFile(path.join(pasta,'indices',arquivo),'utf8')) as SnapshotAlimentar}catch{return <EscopoAlimentar slug={slug}/>;}if(config.ids&&arquivo===config.arquivo){const usados=new Set(config.ids);dados={...dados,indicadores:dados.indicadores.filter(i=>usados.has(i.id)),observacoes:dados.observacoes.filter(o=>usados.has(o.indicadorId))};}let malha:MalhaAlimentar|undefined;if(slug==='territorios'){try{malha=JSON.parse(await readFile(path.join(process.cwd(),'public/energia/geo/uf.json'),'utf8')) as MalhaAlimentar}catch{}}const nomes:Record<string,string>={'snapshot.json':'EBIA · pesquisa domiciliar','cadinsan.json':'CadINSAN · risco modelado no cadastro','sisan.json':'MUNIC · governança e equipamentos','paa.json':'PAA · pagamentos e fornecedores registrados','aquisicao.json':'MUNIC · ações de aquisição e distribuição','precos.json':'IPCA · preços ao consumidor','escolar.json':'PNAE · transferências e registros','saude.json':'SISVAN · acompanhamento'};const escolhaBase=permitidos.length?<form className="saa-controls" method="get"><label>Conjunto de dados<select name="base" defaultValue={arquivo}>{permitidos.map(a=><option key={a} value={a}>{nomes[a]}</option>)}</select></label><button type="submit">Aplicar conjunto</button><p className="saa-status">Cada conjunto conserva seu próprio universo. Trocar a fonte reinicia o recorte da análise.</p></form>:undefined;let acoesComplementares:SnapshotAlimentar|undefined;if(slug==='aquisicao-abastecimento'){try{acoesComplementares=JSON.parse(await readFile(path.join(pasta,'indices','aquisicao.json'),'utf8')) as SnapshotAlimentar}catch{}}return <PainelAlimentar acoesComplementares={acoesComplementares} key={arquivo+slug} dados={dados} escolhaBase={escolhaBase} slug={slug} malha={malha} arquivo={arquivo} municipalProgressivo={['sisan.json','cadinsan.json','aquisicao.json','paa.json','escolar.json'].includes(arquivo)}/>}
