import type {Metadata} from 'next';
import Link from 'next/link';
import {consultaCursos,type RecorteCursos} from '@/lib/eficiencia/trabalho-renda/cursos';
import {NavegacaoTrabalho} from '@/components/eficiencia/trabalho-renda/NavegacaoTrabalho';
export const metadata:Metadata={title:'Qualificação: cursos autorizados de aprendizagem',description:'Explore os registros de cursos de aprendizagem profissional autorizados pelo MTE, por localidade, entidade, modalidade e prazo de validade.'};
export const dynamic='force-dynamic';
const BASE='/eficiencia-estatal/trabalho-renda/qualificacao';
const inteiro=(v:number)=>v.toLocaleString('pt-BR');
const data=(v:string|null)=>v?new Date(v+'T12:00:00Z').toLocaleDateString('pt-BR',{timeZone:'UTC'}):'Não informada';
export default function Qualificacao({searchParams={}}:{searchParams?:RecorteCursos}){
 const {indice,uf,selecionados,recorte}=consultaCursos(searchParams);
 const pag=Math.min(Math.max(1,Number.parseInt(recorte.pagina??'1')||1),Math.max(1,Math.ceil(selecionados.length/30)));
 const exibidos=selecionados.slice((pag-1)*30,pag*30);const filtro=new URLSearchParams();if(uf)filtro.set('uf',uf);if(recorte.q)filtro.set('q',recorte.q.slice(0,200));if(recorte.modalidade)filtro.set('modalidade',recorte.modalidade);if(recorte.status)filtro.set('status',recorte.status);
 const urlPagina=(n:number)=>{const q=new URLSearchParams(filtro);q.set('pagina',String(n));return BASE+'?'+q.toString();};
 const modalidades=Array.from(new Set(selecionados.map(c=>c.modalidade))).map(m=>({nome:m,n:selecionados.filter(c=>c.modalidade===m).length}));const maior=Math.max(1,...modalidades.map(m=>m.n));
 return <><p className="tr-kicker">Formação e oportunidades · Cadastro Nacional da Aprendizagem Profissional</p><h1>Onde encontrar cursos de aprendizagem?</h1><p className="tr-lead">Consulte autorizações de cursos por localidade, instituição e modalidade. A fonte informa aprovação e validade; disponibilidade de turmas, matrículas e vagas precisa ser confirmada com a entidade.</p><NavegacaoTrabalho/>
 <form key={JSON.stringify([uf,recorte.q,recorte.modalidade,recorte.status])} action={BASE} method="get" className="tr-controls" aria-label="Filtrar cursos de aprendizagem">
 <label>Buscar curso, ocupação ou cidade<input type="search" name="q" defaultValue={recorte.q??''} maxLength={200} placeholder="Ex.: logística, Recife, 411005"/></label>
 <label>Unidade da Federação<select name="uf" defaultValue={uf}><option value="">Todas as UFs</option>{indice.porUF.map(r=><option value={r.uf} key={r.uf}>{r.uf}</option>)}</select></label>
 <label>Modalidade<select name="modalidade" defaultValue={recorte.modalidade??''}><option value="">Todas as modalidades</option>{indice.modalidades.map(m=><option key={m}>{m}</option>)}</select></label>
 <label>Prazo da autorização<select name="status" defaultValue={recorte.status??'vigente'}><option value="vigente">Vigente na data de captura</option><option value="vencido">Prazo vencido no recorte</option><option value="futuro">Aprovação posterior ao recorte</option><option value="sem-data">Datas não informadas</option><option value="todos">Todos os registros</option></select></label>
 <div className="tr-actions"><button type="submit">Aplicar filtros</button><Link className="tr-button secondary" href={BASE}>Limpar filtros</Link></div>
 </form>
 <p className="tr-source">{indice.fonte.referencia}. A classificação de vigência usa as datas declaradas, não uma verificação de funcionamento atual.</p>
 <dl className="tr-kpis"><div className="tr-kpi"><dt>Registros no recorte</dt><dd><strong>{inteiro(selecionados.length)}</strong><p>Autorizações e localidades indicadas; um curso pode aparecer em mais de uma linha.</p></dd></div><div className="tr-kpi"><dt>Códigos de curso distintos</dt><dd><strong>{inteiro(new Set(selecionados.map(c=>c.id)).size)}</strong><p>Deduplicação apenas pelo código declarado pelo MTE.</p></dd></div><div className="tr-kpi"><dt>Localidades indicadas</dt><dd><strong>{inteiro(new Set(selecionados.map(c=>c.uf+'|'+c.cidade.toLocaleUpperCase('pt-BR'))).size)}</strong><p>Sede ou localidade da autorização a distância, conforme a planilha.</p></dd></div></dl>
 <section className="tr-section"><h2>Como as autorizações se distribuem por modalidade?</h2><p className="tr-chart-description">Quantidade de registros no mesmo recorte da consulta. Registros não são matrículas nem pessoas atendidas. As grafias “À distância” e “À Distância” são agrupadas; a exportação preserva a modalidade original.</p>{modalidades.length?<ul className="tr-barlist">{modalidades.map(m=><li key={m.nome}><span>{m.nome||'Não informada'}</span><div className="tr-bartrack" aria-hidden="true"><div className="tr-bar" style={{width:`${100*m.n/maior}%`}}/></div><strong>{inteiro(m.n)}</strong></li>)}</ul>:<p className="tr-empty">Nenhum registro corresponde aos filtros. Experimente ampliar a localidade ou retirar um termo da busca.</p>}</section>
 <section className="tr-section"><div className="tr-section-head"><div><h2>Cursos e entidades no seu recorte</h2><p>{selecionados.length?`Registros ${(pag-1)*30+1} a ${Math.min(pag*30,selecionados.length)} de ${inteiro(selecionados.length)}. Página ${pag} de ${Math.max(1,Math.ceil(selecionados.length/30))}.`:'Nenhum registro encontrado.'}</p></div><a className="tr-button" download="cursos-aprendizagem-recorte.csv" href={BASE+'/dados.csv?'+filtro.toString()}>Exportar todo o recorte CSV</a></div>
 {exibidos.length>0&&<div className="tr-table-scroll" tabIndex={0} role="region" aria-label="Tabela dos cursos de aprendizagem, com rolagem horizontal"><table><caption>Autorizações de aprendizagem · {uf||'Brasil'} · referência da planilha de outubro de 2026</caption><thead><tr><th scope="col">Curso e programa</th><th scope="col">Entidade e localidade</th><th scope="col">Modalidade e carga</th><th scope="col">Validade e detalhes</th></tr></thead><tbody>{exibidos.map(c=><tr key={c.originalLinha}><th scope="row"><strong>{c.nome}</strong><p className="tr-source">Código {c.id} · {c.programa}</p></th><td>{c.entidade}<p className="tr-source">{c.cidade} ({c.uf}) · {c.localidade==='oferta-ead'?'localidade indicada para oferta a distância':'sede declarada da entidade'}</p></td><td>{c.modalidade||'Não informada'}<p className="tr-source">{c.horasTotal===null?'Carga horária não informada':inteiro(c.horasTotal)+' horas totais'}</p></td><td><span className="tr-tag">{c.status==='vigente'?'Vigente no recorte':c.status==='vencido'?'Prazo vencido':c.status==='futuro'?'Aprovação futura':'Sem datas'}</span><p className="tr-source">Até {data(c.validadeISO)}</p><details><summary>Ocupações e aprovação</summary><p>Aprovação: {data(c.aprovacaoISO)}.</p><p>CBO: {c.cbo||'Não informada'}.</p><p>{c.ocupacoes||'Título das ocupações não informado.'}</p></details></td></tr>)}</tbody></table></div>}
 <nav aria-label="Páginas de resultados" className="tr-footer-nav">{pag>1?<Link className="tr-button" href={urlPagina(pag-1)}>← Página anterior</Link>:<span/>}{pag*30<selecionados.length&&<Link className="tr-button" href={urlPagina(pag+1)}>Próxima página →</Link>}</nav></section>
 <section className="tr-section"><h2>O que este cadastro permite observar?</h2><div className="tr-grid"><div><h3>Autorizações e presença territorial</h3><p className="tr-chart-description">A planilha permite localizar instituições, cursos, ocupações associadas, modalidades e prazos. O recorte distingue linhas de autorização e códigos de curso.</p></div><div><h3>O que falta para medir resultados</h3><p className="tr-chart-description">Vagas disponíveis, matrículas, concluintes, colocações pelo Sine e renda após o curso não são informados nesta base. A presença de um curso não demonstra atendimento ou efeito sobre o emprego.</p></div></div><details><summary>Fonte, reprodução e limites</summary><p><a href={indice.fonte.pagina}>Ministério do Trabalho e Emprego — Aprendizagem Profissional</a>. Captura: {new Date(indice.fonte.capturadoEm).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} (Brasília).</p><ul>{indice.fonte.limitacoes.map(l=><li key={l}>{l}</li>)}</ul><p>SHA-256 do CSV original: <code style={{overflowWrap:'anywhere'}}>{indice.fonte.sha256Csv}</code>.</p><a className="tr-button" href={indice.fonte.bruto} download>Baixar planilha original ZIP</a></details></section>
 <div className="tr-footer-nav"><Link href="/eficiencia-estatal/trabalho-renda/metodos">Método e cobertura →</Link><Link href="/eficiencia-estatal/trabalho-renda">Voltar ao panorama →</Link></div></>;
}
