/** Mapa editorial de escopos. Não constitui inventário de indicadores coletados. */
export const GRUPOS = ["Vida e desenvolvimento", "Proteção e direitos", "Cidade e infraestrutura", "Cidadania e convivência"] as const;
export type GrupoDimensao = typeof GRUPOS[number];
export type Dimensao = {
  id: string; titulo: string; verbo: string; grupo: GrupoDimensao;
  descricao: string; recursos: string; acesso: string; resultados: string;
  href?: string;
};
export const DIMENSOES: Dimensao[] = [
  { id: "educacao", titulo: "Educação", verbo: "Aprender", grupo: GRUPOS[0], descricao: "Da primeira infância à formação ao longo da vida.", recursos: "Aplicação em ensino, infraestrutura escolar e financiamento das redes.", acesso: "Matrículas, vagas, condições de atendimento e permanência na escola.", resultados: "Aprendizagem, aprovação e conclusão dos estudos.", href: "/eficiencia-estatal/educacao-municipal-capitais" },
  { id: "saude", titulo: "Saúde", verbo: "Cuidar da saúde", grupo: GRUPOS[0], descricao: "Prevenção, atenção primária e cuidado especializado.", recursos: "Aplicação em saúde, financiamento e estrutura da rede.", acesso: "Unidades, equipes, cobertura, consultas e tempo de espera.", resultados: "Condições de saúde e internações evitáveis por atenção primária.", href: "/eficiencia-estatal/saude-capitais" },
  { id: "trabalho", titulo: "Trabalho e renda", verbo: "Trabalhar", grupo: GRUPOS[0], descricao: "Qualificação, oportunidades e inclusão produtiva.", recursos: "Financiamento da qualificação e dos serviços de emprego.", acesso: "Vagas intermediadas, cursos e atendimento a trabalhadores.", resultados: "Inserção no trabalho e evolução da renda, com contexto econômico.", href: "/eficiencia-estatal/trabalho-renda" },
  { id: "alimentacao", titulo: "Segurança alimentar", verbo: "Alimentar-se", grupo: GRUPOS[0], descricao: "Acesso regular a alimentos e nutrição adequada.", recursos: "Financiamento da alimentação escolar, abastecimento e equipamentos públicos.", acesso: "Refeições, famílias atendidas e acesso a alimentos.", resultados: "Segurança alimentar e condições nutricionais.", href: "/eficiencia-estatal/seguranca-alimentar" },
  { id: "assistencia", titulo: "Assistência social", verbo: "Receber apoio", grupo: GRUPOS[1], descricao: "Proteção às famílias e às pessoas em situação de vulnerabilidade.", recursos: "Financiamento de benefícios, serviços e equipamentos socioassistenciais.", acesso: "Cadastro, cobertura, atendimento e acolhimento.", resultados: "Proteção social e condições de vida das famílias atendidas." },
  { id: "previdencia", titulo: "Previdência", verbo: "Ter segurança de renda", grupo: GRUPOS[1], descricao: "Aposentadorias, pensões e proteção em situações de incapacidade.", recursos: "Contribuições, despesas e financiamento dos regimes previdenciários.", acesso: "Cobertura, benefícios concedidos e prazos de análise.", resultados: "Proteção da renda e continuidade do pagamento dos benefícios." },
  { id: "seguranca", titulo: "Segurança pública", verbo: "Viver com segurança", grupo: GRUPOS[1], descricao: "Prevenção da violência, resposta a ocorrências e proteção civil.", recursos: "Financiamento, equipes e estrutura de segurança e defesa civil.", acesso: "Presença territorial e resposta a ocorrências e emergências.", resultados: "Violência registrada, vitimização e resposta a desastres." },
  { id: "justica", titulo: "Justiça e direitos", verbo: "Fazer valer direitos", grupo: GRUPOS[1], descricao: "Acesso à justiça, assistência jurídica e garantia de direitos.", recursos: "Recursos do Judiciário, defensorias e instituições de proteção de direitos.", acesso: "Assistência jurídica, atendimento e duração dos processos.", resultados: "Resolução de demandas e efetividade da proteção de direitos." },
  { id: "habitacao", titulo: "Habitação", verbo: "Morar com dignidade", grupo: GRUPOS[2], descricao: "Moradia adequada, urbanização e regularização fundiária.", recursos: "Financiamento habitacional, obras e subsídios.", acesso: "Famílias atendidas, moradias entregues e regularização.", resultados: "Déficit habitacional e adequação das condições de moradia." },
  { id: "saneamento", titulo: "Saneamento", verbo: "Ter água e saneamento", grupo: GRUPOS[2], descricao: "Água, esgoto, resíduos e drenagem urbana.", recursos: "Investimentos, despesas operacionais e infraestrutura.", acesso: "Cobertura, continuidade e qualidade dos serviços.", resultados: "Tratamento de esgoto, destinação de resíduos e exposição a alagamentos." },
  { id: "mobilidade", titulo: "Mobilidade e transporte", verbo: "Chegar aonde precisa", grupo: GRUPOS[2], descricao: "Deslocamentos, transporte público e acessibilidade urbana.", recursos: "Investimentos em infraestrutura e financiamento do transporte.", acesso: "Oferta, frequência, acessibilidade e tarifa.", resultados: "Tempo de deslocamento e segurança no trânsito." },
  { id: "energia", titulo: "Energia e conectividade", verbo: "Conectar-se", grupo: GRUPOS[2], descricao: "Infraestrutura essencial de energia e comunicação.", recursos: "Investimentos, subsídios e infraestrutura de energia e telecomunicações.", acesso: "Cobertura, continuidade do fornecimento e acesso à internet.", resultados: "Qualidade, confiabilidade e acessibilidade econômica dos serviços." },
  { id: "ambiente", titulo: "Meio ambiente e clima", verbo: "Viver em um ambiente saudável", grupo: GRUPOS[2], descricao: "Conservação, qualidade ambiental e adaptação climática.", recursos: "Aplicação em conservação, fiscalização e adaptação.", acesso: "Áreas verdes, monitoramento e proteção de áreas de risco.", resultados: "Qualidade do ar e da água e exposição a riscos ambientais." },
  { id: "cultura", titulo: "Cultura", verbo: "Criar e participar", grupo: GRUPOS[3], descricao: "Patrimônio, bibliotecas, espaços culturais e produção artística.", recursos: "Financiamento de equipamentos, patrimônio e produção cultural.", acesso: "Oferta territorial, programação e participação do público.", resultados: "Participação cultural e preservação do patrimônio." },
  { id: "esporte", titulo: "Esporte e lazer", verbo: "Mover-se e conviver", grupo: GRUPOS[3], descricao: "Atividade física, espaços de lazer e convivência comunitária.", recursos: "Aplicação em instalações, programas e manutenção.", acesso: "Espaços disponíveis, atividades e pessoas atendidas.", resultados: "Participação em atividades físicas e uso dos espaços públicos." },
  { id: "servicos", titulo: "Serviços e cidadania", verbo: "Acessar o Estado", grupo: GRUPOS[3], descricao: "Documentos, serviços digitais, transparência e participação.", recursos: "Financiamento de atendimento, tecnologia e administração pública.", acesso: "Disponibilidade dos serviços, acessibilidade e tempo de resposta.", resultados: "Resolução de solicitações e participação cidadã." },
];
export function normalizaBusca(texto: string) {
  return texto.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR");
}
export function filtraDimensoes(busca: string, grupo: GrupoDimensao | "Todas", somentePublicados = false) {
  const termos = normalizaBusca(busca).trim().split(/\s+/).filter(Boolean);
  return DIMENSOES.filter(d => (grupo === "Todas" || grupo === d.grupo) && (!somentePublicados || !!d.href) && termos.every(t => normalizaBusca([d.titulo, d.verbo, d.descricao, d.recursos, d.acesso, d.resultados].join(" ")).includes(t)));
}
