import type {SnapshotAlimentar,TerritorioAlimentar} from './tipos';
export const EBIA_CATEGORIAS=[{id:'ebia-segura',nome:'Segurança alimentar',classe:'segura'},{id:'ebia-leve',nome:'Insegurança leve',classe:'leve'},{id:'ebia-moderada',nome:'Insegurança moderada',classe:'moderada'},{id:'ebia-grave',nome:'Insegurança grave',classe:'grave'}];
const UF:Record<string,string>={'11':'RO','12':'AC','13':'AM','14':'RR','15':'PA','16':'AP','17':'TO','21':'MA','22':'PI','23':'CE','24':'RN','25':'PB','26':'PE','27':'AL','28':'SE','29':'BA','31':'MG','32':'ES','33':'RJ','35':'SP','41':'PR','42':'SC','43':'RS','50':'MS','51':'MT','52':'GO','53':'DF'};
export function rotuloTerritorio(t:TerritorioAlimentar){const uf=t.uf??UF[t.id.slice(0,2)];return t.nivel==='municipio'&&uf&&!new RegExp(`(?:[-–]\\s*${uf}|\\(${uf}\\))$`).test(t.nome.trim())?`${t.nome} (${uf})`:t.nome;}
export function numeroAlimentar(v:number|null|undefined,unidade:string){if(v===null||v===undefined)return 'Não disponível';if(unidade==='%')return `${v.toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;if(unidade==='R$')return `R$ ${v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}`;return v.toLocaleString('pt-BR',{maximumFractionDigits:unidade.includes('índice')?3:2});}
export function dataAlimentar(data:string){return new Date(data).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})+' (Brasília)';}
export const normalizaAlimentar=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').trim();
export function csvAlimentar(dados:SnapshotAlimentar,observacoes:SnapshotAlimentar['observacoes']){const territorios=new Map(dados.territorios.map(t=>[t.id,t]));const indicadores=new Map(dados.indicadores.map(i=>[i.id,i]));const fontes=new Map(dados.fontes.map(f=>[f.id,f]));const quote=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;return '\uFEFF'+[['territorio','nivel','indicador','unidade','periodo','dimensao','grupo','valor','estado','cv_percentual','universo','limitacao','fonte','nota_material','numerador','denominador','formula','municipios_com_dado','municipios_universo','capturado_em'],...observacoes.map(o=>{const t=territorios.get(o.territorioId);const i=indicadores.get(o.indicadorId);const f=fontes.get(o.fonteId);return[t?rotuloTerritorio(t):o.territorioId,t?.nivel,i?.nome,i?.unidade,o.periodoNome,o.dimensao,o.grupo,o.valor===null?'':String(o.valor).replace('.',','),o.status,o.cv,i?.universo,i?.limitacao,f?.consulta??f?.url,o.nota,o.numerador,o.denominador,o.formula,o.municipiosComDado,o.municipiosUniverso,f?.capturadoEm??dados.capturadoEm]})].map(r=>r.map(quote).join(';')).join('\r\n');}

export function numeroIndicadorAlimentar(v:number|null|undefined,indicador:{id:string;unidade:string}){return indicador.id.startsWith('ipca-')&&v!==null&&v!==undefined?`${v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}%`:numeroAlimentar(v,indicador.unidade);}

export function rotuloDimensaoAlimentar(dim:string,indicadorId=''){if(dim==='total'){if(indicadorId.startsWith('ebia-'))return 'Total dos domicílios';if(indicadorId.startsWith('cadinsan-'))return 'Famílias cadastradas analisadas';if(indicadorId.startsWith('munic-'))return 'Declarações municipais';if(indicadorId.startsWith('paa-'))return 'Registros do programa';return 'Total do recorte';}const nomes:Record<string,string>={total:'Total do recorte',area:'Situação do domicílio','sexo-responsavel':'Sexo da pessoa responsável','cor-responsavel':'Cor ou raça da pessoa responsável','instrucao-responsavel':'Instrução da pessoa responsável','ocupacao-responsavel':'Ocupação da pessoa responsável',moradores:'Número de moradores',renda:'Renda domiciliar por pessoa','menores-5':'Presença de menores de 5 anos',idosos:'Presença de idosos','menores-18':'Presença de menores de 18 anos'};return nomes[dim]??dim;}
export function rotuloPeriodoAlimentar(periodo:string){if(/^\d{6}$/.test(periodo)){const ano=Number(periodo.slice(0,4));const mes=Number(periodo.slice(4));if(mes>=1&&mes<=12)return new Date(Date.UTC(ano,mes-1,1)).toLocaleDateString('pt-BR',{month:'long',year:'numeric',timeZone:'UTC'});}return periodo;}

/** Instante de captura na data civil de Brasília; não reinterpretar referências anuais. */
export function diaCapturaAlimentar(instante:string){return new Date(instante).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'});}
