export const BASE_ALIMENTAR='/eficiencia-estatal/seguranca-alimentar';
export type SlugAlimentar=''|'inseguranca-alimentar'|'desigualdades'|'territorios'|'precos-poder-de-compra'|'alimentacao-escolar'|'equipamentos-atendimento'|'aquisicao-abastecimento'|'alimentacao-saude'|'gestao-recursos'|'comparar'|'metodos';
export const PAGINAS_ALIMENTARES:{slug:SlugAlimentar;nome:string;titulo:string;pergunta:string;arquivo:string;ids?:string[];limite:string}[]=[
 {slug:'',nome:'Panorama',titulo:'A alimentação na vida das pessoas.',pergunta:'A alimentação chega com regularidade e qualidade? Explore a situação dos domicílios, os preços e as políticas públicas, mantendo os universos de cada fonte separados.',arquivo:'snapshot.json',ids:['ebia-segura','ebia-leve','ebia-moderada','ebia-grave','ebia-insan-total','ebia-moderada-grave'],limite:'A EBIA mede a experiência de acesso à alimentação no domicílio. Não mede, sozinha, qualidade da dieta, estado nutricional ou eficiência da gestão.'},
 {slug:'inseguranca-alimentar',nome:'Insegurança alimentar',titulo:'Como os domicílios vivem o acesso à alimentação?',pergunta:'Segurança alimentar e insegurança leve, moderada e grave são categorias da mesma escala. Compare períodos e estados com o mesmo universo.',arquivo:'snapshot.json',ids:['ebia-insan-total','ebia-segura','ebia-leve','ebia-moderada','ebia-grave','ebia-moderada-grave'],limite:'Domicílios particulares permanentes, não pessoas ou famílias cadastradas. Estimativas amostrais; diferenças pequenas não demonstram, por si, mudança estatisticamente significativa.'},
 {slug:'desigualdades',nome:'Desigualdades',titulo:'Em quais grupos o acesso à alimentação é diferente?',pergunta:'Compare domicílios segundo características da pessoa responsável, renda e composição familiar. Os recortes sociais desta publicação têm cobertura nacional.',arquivo:'snapshot.json',ids:['ebia-insan-total','ebia-grave','ebia-moderada-grave','ebia-segura','ebia-leve','ebia-moderada'],limite:'Características da pessoa responsável classificam os domicílios; não medem insegurança individual dessa pessoa. Prevalências são calculadas com numerador e total do mesmo grupo.'},
 {slug:'territorios',nome:'Territórios',titulo:'Onde o acesso à alimentação exige atenção?',pergunta:'Explore estados pela EBIA e o recorte municipal do cadastro administrativo, em universos separados. Um registro administrativo não substitui a pesquisa domiciliar.',arquivo:'snapshot.json',limite:'EBIA, CadINSAN e adesão ao SISAN descrevem fenômenos distintos. Não formam uma escala comum ou um ranking de eficiência.'},
 {slug:'precos-poder-de-compra',nome:'Preços e poder de compra',titulo:'Como os preços dos alimentos mudam?',pergunta:'Acompanhe as medidas oficiais de preços e seus recortes. Variação de preço não é gasto realizado por uma família nem medida direta de insegurança alimentar.',arquivo:'precos.json',ids:['ipca-7171-2265','ipca-7170-2265','ipca-7432-2265','ipca-7169-2265','ipca-7171-63','ipca-7170-63','ipca-7432-63','ipca-7169-63'],limite:'Índices de preços descrevem uma cesta e uma população de referência. Não permitem calcular o orçamento de um domicílio específico sem informação de consumo e renda compatível.'},
 {slug:'alimentacao-escolar',nome:'Alimentação escolar',titulo:'Que recursos chegam à alimentação escolar?',pergunta:'Explore a cobertura e os recursos oficiais do programa, distinguindo transferências federais, execução local e estudantes ou matrículas conforme a definição da fonte.',arquivo:'escolar.json',limite:'Transferência não equivale a refeição servida, execução total da política ou qualidade da alimentação. Matrículas não são necessariamente pessoas únicas.'},
 {slug:'equipamentos-atendimento',nome:'Equipamentos e atendimento',titulo:'Que estrutura pública apoia o acesso à alimentação?',pergunta:'Conheça os registros de oferta, adesão e estrutura disponíveis. Diferencie existência de um equipamento, capacidade, atendimento e acesso efetivo.',arquivo:'sisan.json',ids:['munic-restaurante-quantidade','munic-cozinha-quantidade','munic-banco-quantidade','munic-central-quantidade','munic-restaurante','munic-cozinha','munic-banco','munic-central'],limite:'Um cadastro de presença institucional não demonstra funcionamento, vagas, horários, refeições entregues ou tempo de espera.'},
 {slug:'aquisicao-abastecimento',nome:'Aquisição e abastecimento',titulo:'O que é pago e registrado na aquisição pública?',pergunta:'Explore pagamentos e registros anuais de fornecedores do PAA. Ações autodeclaradas na MUNIC aparecem em capítulo separado, com outro universo e outra referência.',arquivo:'paa.json',ids:['paa-pagamentos','paa-fornecedores'],limite:'Recursos, alimentos adquiridos, agricultores e pessoas atendidas são medidas distintas. Não calcular custo por beneficiário sem denominadores e períodos conciliados.'},
 {slug:'alimentacao-saude',nome:'Alimentação e saúde',titulo:'O que se observa entre as pessoas acompanhadas?',pergunta:'Explore registros de acompanhamento alimentar e nutricional, preservando etapa de vida, cobertura e universo da vigilância.',arquivo:'saude.json',limite:'Registros do SISVAN descrevem pessoas acompanhadas e os critérios da fonte. Não representam automaticamente toda a população, nem equivalem às categorias da EBIA.'},
 {slug:'gestao-recursos',nome:'Gestão e recursos',titulo:'Que estruturas sustentam a política municipal?',pergunta:'Explore declarações municipais sobre gestão, conselho, plano, lei e fundo de segurança alimentar. As transferências federais do PNAE estão em painel separado; não há orçamento consolidado nesta tela.',arquivo:'sisan.json',ids:['munic-gestor','munic-lei','munic-plano','munic-conselho','munic-camara','munic-fundo'],limite:'Adesão institucional, despesa e atendimento têm contratos próprios. Mais recursos ou mais adesões não demonstram, isoladamente, maior eficiência.'},
 {slug:'comparar',nome:'Comparar',titulo:'Compare com o mesmo contrato.',pergunta:'Escolha uma medida, território, período e recorte. As comparações preservam fonte, unidade e população elegível.',arquivo:'snapshot.json',limite:'Comparações entre medidas, períodos ou universos diferentes não são convertidas em uma nota composta.'},
 {slug:'metodos',nome:'Método e cobertura',titulo:'O que os dados permitem dizer.',pergunta:'Definições, fontes, recortes e lacunas para interpretar e reproduzir cada número, sem confundir pesquisa, cadastro, financiamento e atendimento.',arquivo:'snapshot.json',limite:'Ausência de dado publicado não significa ausência de serviço ou de política. Zero só aparece quando é um valor observado.'},
];
