"use client";
import { useEffect, useMemo, useState } from "react";
import type { Ficha } from "@/lib/eficiencia/alimentar/dados";
type Municipio = { code:string; city:string; uf:string; values:Record<string,{code:string;raw:string|number|null;status:string}> };
const BASE="/eficiencia/seguranca-alimentar";
const rotulos:Record<string,string>={OBSERVADO:"Observado",AUSENTE:"Ausente",NAO_APLICAVEL_OU_SEM_REGISTRO:"Traço original; consultar dicionário",NAO_SABE_INFORMAR:"Não sabe informar",NAO_INFORMADO:"Não informado"};
const normaliza=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR");
export function ExploradorAlimentar({ fichas, ufs }: { fichas:Ficha[]; ufs:string[] }) {
  const [uf,setUf]=useState("PE"),[variavel,setVariavel]=useState(fichas[0].variavel),[busca,setBusca]=useState(""),[pagina,setPagina]=useState(0),[linhas,setLinhas]=useState<Municipio[]>([]),[estado,setEstado]=useState("Carregando registros…"),[tentativa,setTentativa]=useState(0);
  useEffect(()=>{const controller=new AbortController();setLinhas([]);setEstado("Carregando registros…");fetch(`${BASE}/uf-${uf}.json`,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error("Falha no download");return r.json() as Promise<Municipio[]>}).then(rows=>{setLinhas(rows);setEstado("")}).catch(e=>{if(e.name!=="AbortError")setEstado("Não foi possível carregar a base. Tente novamente ou baixe o CSV completo.")});return ()=>controller.abort();},[uf,tentativa]);
  const selecionadas=useMemo(()=>linhas.filter(r=>normaliza(`${r.city} ${r.code}`).includes(normaliza(busca))).sort((a,b)=>a.city.localeCompare(b.city,"pt-BR")),[linhas,busca]);
  const ficha=fichas.find(f=>f.variavel===variavel)!;const paginas=Math.max(1,Math.ceil(selecionadas.length/50));const atual=Math.min(pagina,paginas-1);
  return <div><div className="mt-6 grid gap-4 md:grid-cols-[2fr_1fr_1.5fr]">
    <div><label htmlFor="san-variavel" className="block text-xs">Indicador</label><select id="san-variavel" value={variavel} onChange={e=>{setVariavel(e.target.value);setPagina(0)}} className="mt-2 min-h-[44px] w-full border border-mineral bg-superficie px-3 text-sm">{fichas.map(f=><option key={f.variavel} value={f.variavel}>{f.nome}</option>)}</select></div>
    <div><label htmlFor="san-uf" className="block text-xs">Unidade da Federação</label><select id="san-uf" value={uf} onChange={e=>{setUf(e.target.value);setPagina(0)}} className="mt-2 min-h-[44px] w-full border border-mineral bg-superficie px-3 text-sm">{ufs.map(u=><option key={u}>{u}</option>)}</select></div>
    <div><label htmlFor="san-busca" className="block text-xs">Município ou código IBGE</label><input id="san-busca" type="search" value={busca} onChange={e=>{setBusca(e.target.value);setPagina(0)}} placeholder="Ex.: Recife ou 2611606" className="mt-2 min-h-[44px] w-full border border-mineral bg-superficie px-3 text-sm"/></div>
  </div><details open className="my-6 border-y border-linha py-3"><summary className="min-h-[44px] cursor-pointer text-sm font-medium">Ficha do indicador · {ficha.variavel}</summary><div className="space-y-2 pb-3 text-sm"><p>{ficha.definicao}</p><p><strong>Período:</strong> {ficha.periodo} · <strong>Unidade:</strong> {ficha.unidade} · <strong>Fonte:</strong> {ficha.fonte} · {ficha.registro}</p><p><strong>Universo:</strong> {ficha.universo}</p><p><strong>Fórmula:</strong> {ficha.formula} Numerador e denominador: não se aplicam à variável descritiva.</p><p><strong>Papel no escore:</strong> {ficha.papel_escore} Peso e referência de pontuação não definidos.</p><p>{ficha.ausencias} {ficha.limitacoes}</p><p className="text-xs text-carvao-muted">Frequência: {ficha.frequencia} Cobertura: 5.570 registros, incluindo respostas sem valor válido. {ficha.quebras}</p></div></details>
  {estado ? <div role="status" className="my-6 border border-linha p-4 text-sm"><p>{estado}</p>{estado.startsWith("Não")&&<button onClick={()=>setTentativa(t=>t+1)} className="mt-3 min-h-[44px] underline">Tentar novamente</button>}</div> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="pb-3 text-left text-xs">{ficha.nome} · {ficha.periodo} · {selecionadas.length.toLocaleString("pt-BR")} registros no filtro</caption><thead><tr>{["Município","UF","Valor original","Estado do dado"].map(t=><th key={t} scope="col" className="border-b border-linha px-3 py-3 font-medium">{t}</th>)}</tr></thead><tbody>{selecionadas.slice(atual*50,(atual+1)*50).map(t=>{const r=t.values[variavel];return <tr key={t.code} className="border-b border-linha"><th scope="row" className="px-3 py-3 font-normal">{t.city}<span className="block text-xs text-carvao-muted">{t.code}</span></th><td className="px-3 py-3">{t.uf}</td><td className="px-3 py-3">{r.raw??"Não informado"}</td><td className="px-3 py-3">{rotulos[r.status]??r.status}</td></tr>})}{selecionadas.length===0&&<tr><td colSpan={4} className="py-6">Nenhum município encontrado.</td></tr>}</tbody></table></div><div className="my-4 flex flex-wrap items-center justify-between gap-3"><button onClick={()=>setPagina(atual-1)} disabled={atual===0} className="min-h-[44px] border border-mineral px-4 text-sm disabled:opacity-40">← Anterior</button><span role="status" className="text-xs">Página {atual+1} de {paginas} · até 50 registros por página</span><button onClick={()=>setPagina(atual+1)} disabled={atual===paginas-1} className="min-h-[44px] border border-mineral px-4 text-sm disabled:opacity-40">Próxima →</button></div></>}
  <p className="mt-5 text-xs leading-relaxed text-carvao-muted">“Não” é uma resposta observada; “não sabe informar” é desconhecimento. O traço original pode representar salto do questionário ou falta de registro e não é convertido em zero. O CSV completo preserva todos os 55.700 registros.</p><a href={`${BASE}/municipios.csv`} download className="mt-3 inline-flex min-h-[44px] items-center text-sm text-obee-dark underline">Baixar base municipal completa · CSV ↓</a><noscript><p>Os filtros precisam de JavaScript. O CSV completo e o dicionário permanecem disponíveis para consulta.</p></noscript></div>;
}
