import Link from 'next/link';
import {dadosOportunidades} from '@/lib/eficiencia/mobilidade/oportunidades-dados';
import {dadosMobilidade} from '@/lib/eficiencia/mobilidade/dados';
import {MODOS_AOP,HORARIOS_AOP,recorteAop,rotuloGrupoAop,fontesAop,type GrupoAop} from '@/lib/eficiencia/mobilidade/oportunidades';
import {PAGINAS_MOBILIDADE,ROTA_MOBILIDADE,type Parametros} from '@/lib/eficiencia/mobilidade/modelo';
import s from './mobilidade.module.css';
const url=ROTA_MOBILIDADE+'/oportunidades';
const f=(n:number|null,d=1)=>n===null?'Não disponível':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:d}).format(n);
const pct=(n:number|null)=>n===null?'Não disponível':n>99.99&&n<100?'>99,99%':n>0&&n<0.01?'<0,01%':f(n,2)+'%';
function Barra({label,value,max,unit,detail}:{label:string;value:number|null;max:number;unit:string;detail?:string}){return <div className={s.linha}><div className={s.linhaTopo}><span>{label}</span><strong>{f(value)}{value!==null?' '+unit:''}</strong></div>{value!==null&&<div className={s.trilho} aria-hidden="true"><span className={value===0?s.zero:s.barra} style={value===0?undefined:{width:100*value/max+'%'}}/></div>}{detail&&<p className={s.legenda}>{detail}</p>}</div>;}
function TabelaGrupos({grupos,unit}:{grupos:GrupoAop[];unit:string}){return <div className={s.tabela} tabIndex={0} role="region" aria-label="Tabela por área de renda"><table><caption>Mesmos grupos do gráfico, incluindo áreas sem decil válido. População de referência de 2010.</caption><thead><tr><th scope="col">Áreas de renda</th><th scope="col" data-number>Média ({unit})</th><th scope="col" data-number>Cobertura populacional</th><th scope="col" data-number>População coberta</th><th scope="col" data-number>População de referência</th><th scope="col" data-number>Zero oportunidades entre cobertos</th></tr></thead><tbody>{grupos.map(x=><tr key={x.group}><th scope="row">{rotuloGrupoAop(x.group)}</th><td data-number>{f(x.mean)}</td><td data-number>{pct(x.coverage)}</td><td data-number>{f(x.coveredPopulation,0)}</td><td data-number>{f(x.totalPopulation,0)}</td><td data-number>{pct(x.zeroShare)}</td></tr>)}</tbody></table></div>;}
export function PainelOportunidades({p}:{p:Parametros}){
 const {base:g,hash}=dadosOportunidades(),r=recorteAop(g,p),nomes=new Map(dadosMobilidade().base.territories.map(t=>[t.id,t.name]));
 const nome=(id:string)=>nomes.get(id)??g.cities.find(c=>c.id===id)?.name??id;
 const rows=[...r.rows].sort((a,b)=>nome(a.city.id).localeCompare(nome(b.city.id),'pt-BR'));
 const validos=rows.flatMap(x=>x.record?.groups.find(v=>v.group==='all')?.mean!=null?[x]:[]);
 const max=Math.max(1,...validos.map(x=>x.record!.groups[0].mean!));
 const query=new URLSearchParams({escopo:'recorte',modo:r.mode,pico:r.peak,indicador:r.metric.id,...(r.city?{cidade:r.city.id}:{})});
 const registro=r.city?rows[0]?.record:null;
 const renda=registro?.groups.filter(x=>x.group!=='all')??[],maxRenda=Math.max(1,...renda.map(x=>x.mean??0));
 const sources=registro?fontesAop(g,registro):[];
 return <><Link className={s.acao} href="/eficiencia-estatal">← Panorama do OBEE</Link><nav className={s.nav} aria-label="Mobilidade e transporte">{PAGINAS_MOBILIDADE.map(x=><Link key={x.slug} href={ROTA_MOBILIDADE+(x.slug?'/'+x.slug:'')} aria-current={x.slug==='oportunidades'?'page':undefined}>{x.nome}</Link>)}</nav>
 <p className="rotulo text-obee">Mobilidade e transporte · acesso espacial</p><h1 id="titulo-mobilidade" className="font-serif mt-3">O que cabe no alcance de uma viagem?</h1><p className={s.intro}>Compare quantos empregos, escolas e serviços podem ser alcançados a partir de onde as pessoas moram. A cidade, o modo de transporte e o tempo de viagem definem o recorte.</p>
 <p className={s.aviso}><strong>Retrato histórico:</strong> acessibilidade de {g.referenceYear}, ponderada pela distribuição espacial da população de {g.populationYear}. Não descreve a rede nem a população atuais. Acesso espacial não garante contratação, matrícula, consulta ou atendimento.</p>
 <form action={url} method="get" className={s.controles}><label>Oportunidade e tempo<select name="indicador" defaultValue={r.metric.id}>{g.metrics.map(m=><option key={m.id} value={m.id}>{m.opportunity} · {m.minutes} minutos</option>)}</select></label><label>Modo de transporte<select name="modo" defaultValue={r.mode}>{Object.entries(MODOS_AOP).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Cidade<select name="cidade" defaultValue={r.city?.id??''}><option value="">Todas as cidades da base</option>{[...g.cities].sort((a,b)=>nome(a.id).localeCompare(nome(b.id),'pt-BR')).map(c=><option key={c.id} value={c.id}>{nome(c.id)}</option>)}</select></label><label>Horário dos modos motorizados<select name="pico" defaultValue={r.peak==='na'?'1':r.peak}><option value="1">Pico</option><option value="0">Fora do pico</option></select></label><button type="submit">Aplicar oportunidades</button><Link href={url}>Limpar filtros</Link></form>
 <p className={s.nota}>A pé e de bicicleta não há distinção de horário nesta base; o campo de horário só afeta automóvel e transporte público. Cidades fora da cobertura de um modo continuam identificadas, sem valor inventado.</p>{r.avisos.map(a=><p className={s.aviso} key={a}>{a}</p>)}
 <section className={s.secao}><h2 className="font-serif">{r.metric.opportunity} em até {r.metric.minutes} minutos</h2><p className={'mt-3 '+s.nota}>{MODOS_AOP[r.mode]} · {HORARIOS_AOP[r.peak]} · {g.referenceYear}. <strong>{validos.length} de {rows.length} cidades do recorte com estimativa.</strong></p><p className={'mt-3 '+s.nota}>A média pondera cada ponto de partida pelo número de moradores na base de {g.populationYear}. Não é o total de oportunidades da cidade. A cobertura informa qual parcela dessa população entra no cálculo.</p>
 {validos.length>0&&<figure className="mt-5" aria-label="Oportunidades alcançáveis por cidade"><figcaption className={s.nota}>Média de {r.metric.unit} alcançáveis por origem, ponderada pelos moradores. Escala de zero a {f(max)}. Ordem alfabética, sem classificação de desempenho.</figcaption>{rows.filter(x=>x.record).map(x=>{const a=x.record!.groups[0];return <Barra key={x.city.id} label={nome(x.city.id)} value={a.mean} max={max} unit={r.metric.unit} detail={'Cobertura populacional: '+pct(a.coverage)+' · Sem oportunidade alcançável entre os cobertos: '+pct(a.zeroShare)}/>;})}</figure>}
 {rows.some(x=>!x.record)&&<p className={s.aviso}><strong>Sem estimativa para este modo:</strong> {rows.filter(x=>!x.record).map(x=>nome(x.city.id)).join(', ')}. Não significa ausência de transporte ou de oportunidades.</p>}
 <details><summary>Tabela equivalente: valores, cobertura e denominadores</summary><div className={s.tabela} role="region" aria-label="Comparação de acesso a oportunidades" tabIndex={0}><table><caption>{r.metric.opportunity} · {r.metric.minutes} min · {MODOS_AOP[r.mode]} · {HORARIOS_AOP[r.peak]} · {g.referenceYear}. Pesos populacionais de {g.populationYear}.</caption><thead><tr><th scope="col">Cidade</th><th scope="col" data-number>Média ({r.metric.unit})</th><th scope="col" data-number>Cobertura</th><th scope="col" data-number>População coberta</th><th scope="col" data-number>População de referência</th><th scope="col">Estado</th></tr></thead><tbody>{rows.map(x=>{const a=x.record?.groups[0];return <tr key={x.city.id}><th scope="row">{nome(x.city.id)}</th><td data-number>{f(a?.mean??null)}</td><td data-number>{pct(a?.coverage??null)}</td><td data-number>{f(a?.coveredPopulation??null,0)}</td><td data-number>{f(a?.totalPopulation??null,0)}</td><td>{a?.mean!=null?'Estimativa histórica':a?'Sem valor elegível':'Modo não coberto'}</td></tr>;})}</tbody></table></div></details>
 <div className={s.acoes}><a className={s.acao} href={'/api/eficiencia-mobilidade/oportunidades?'+query}>Baixar recorte e grupos de renda (CSV)</a><a className={s.acao} href="/api/eficiencia-mobilidade/oportunidades">Baixar todos os cálculos (CSV)</a></div><p className={s.nota}>O download por recorte contém todas as linhas de cálculo existentes para os filtros. Cidade sem estimativa não produz linha de cálculo; sua ausência permanece indicada na tabela.</p></section>
 <section className={s.secao}><h2 className="font-serif">O acesso muda entre áreas de renda?</h2><p className={'mt-3 '+s.nota}>Os decis ordenam áreas de cada cidade pela renda domiciliar per capita em {g.populationYear}: o primeiro reúne áreas de menor renda; o décimo, de maior renda. Não são grupos de renda individual nem os mesmos valores de renda entre cidades.</p>{registro?<><h3 className="font-serif text-2xl mt-5">{nome(registro.city)} · {r.metric.minutes} minutos</h3><figure className="mt-5" aria-label="Acesso por decil de renda da área"><figcaption className={s.nota}>Mesma medida, modo e horário do recorte acima. Escala de zero a {f(maxRenda)} {r.metric.unit}. Grupos sem população elegível não recebem barra.</figcaption>{renda.map(x=><Barra key={x.group} label={rotuloGrupoAop(x.group)} value={x.mean} max={maxRenda} unit={r.metric.unit} detail={'Cobertura: '+pct(x.coverage)}/>)}</figure><details><summary>Tabela completa por área de renda</summary><TabelaGrupos grupos={registro.groups} unit={r.metric.unit}/></details></>:<p className={s.faixa}>{r.city?'A cidade selecionada não possui estimativa neste modo. Escolha outro modo para consultar os recortes disponíveis.':'Selecione uma cidade no filtro acima para comparar suas áreas de renda, sem misturar classificações de cidades diferentes.'}</p>}</section>
 <section className={s.secao}><h2 className="font-serif">Como ler e reproduzir</h2><p className={'mt-3 '+s.nota}>Fonte: Ipea, Projeto Acesso a Oportunidades. Cálculos de agregação: OBEE. O arquivo populacional e o arquivo de acesso são vinculados pela cidade e pela célula espacial H3. As áreas sem estimativa não viram zero; áreas sem decil válido permanecem separadas.</p><div className={s.acoes}><a className={s.acao} href="https://www.ipea.gov.br/acessooportunidades/dados/">Dados oficiais do Ipea</a><a className={s.acao} href="https://ipea.github.io/aopdata/articles/data_dic_pt.html">Dicionário oficial</a><a className={s.acao} href="/api/eficiencia-mobilidade/oportunidades?formato=json">Resumo completo (JSON)</a><a className={s.acao} href="/api/eficiencia-mobilidade/oportunidades?formato=seed">Semente de reprodução (JSON comprimido)</a></div><details><summary>Fórmulas, limitações e fontes do recorte</summary><div>{g.notes.map(n=><p key={n} className={'mt-3 '+s.nota}>{n}</p>)}<p className={'mt-3 '+s.nota}>{g.sources.length} arquivos originais; {f(g.accessRows,0)} registros de origem, modo e horário; {f(g.populationRows,0)} células populacionais, incluindo células desabitadas. Não são contagens de viagens ou pessoas distintas.</p>{sources.length?sources.map(src=><p key={src.arquivo} className={'mt-3 '+s.nota}><a className={s.acao} href={src.url}>{src.type==='population'?'População espacial de 2010':'Acessibilidade de 2019'} · {src.arquivo}</a><br/><span className={s.mono}>SHA-256: {src.sha256}</span></p>):<p className={'mt-3 '+s.nota}>Selecione uma cidade para abrir seus dois arquivos originais. O JSON completo contém todas as fontes e os hashes.</p>}<p className={'mt-3 '+s.nota}>Os estudos originais são de Pereira e colaboradores (Ipea, 2022), Textos para Discussão 2772 e 2800. Os arquivos representam as hipóteses de rede e oportunidades daquela edição, não viagens observadas.</p><p className={'mt-3 '+s.mono}>SHA-256 do resumo: {hash}</p></div></details></section>
 <section className={s.secao+' '+s.faixa}><h2 className="font-serif text-2xl">Chegar não é ser atendido</h2><p className={'mt-3 '+s.nota}>Conecte o acesso espacial às condições de atendimento registradas nos outros capítulos.</p><div className={s.acoes}><Link className={s.acao} href="/eficiencia-estatal/educacao-municipal-capitais">Educação</Link><Link className={s.acao} href="/eficiencia-estatal/saude-capitais">Saúde</Link><Link className={s.acao} href="/eficiencia-estatal/assistencia-social">Assistência social</Link><Link className={s.acao} href={ROTA_MOBILIDADE+'/acesso'}>Acessibilidade física</Link></div></section></>;
}
