'use client';
import {useMemo,useState} from 'react';
import {useLargura} from '@/components/eficiencia/graficos';
import Link from 'next/link';
import {campo,tiposUrl} from '@/lib/energia/estadoUrl';
import {useEstadoUrl} from '@/components/energia/useEstadoUrl';
import {BASE,formato,nomeTerritorio,type Snapshot} from './modelo';
import {DistribuicaoRendaTrabalho} from './DistribuicaoRendaTrabalho';
import {GruposOcupacoes} from './GruposOcupacoes';
import {SeletorTerritorioTrabalho} from './SeletorTerritorioTrabalho';
import {RecorteTrabalho} from './RecorteTrabalho';
import {NavegacaoTrabalho} from './NavegacaoTrabalho';

type Props={dados:Snapshot;titulo:string;pergunta:string;ids:string[];censo?:boolean};
function baixar(nome:string,conteudo:string){const url=URL.createObjectURL(new Blob(['\uFEFF'+conteudo],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=nome;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function celula(v:unknown){return `"${String(v??'').replaceAll('"','""')}"`}
export function ExploradorTrabalho({dados,titulo,pergunta,ids}:Props){
 const idsKey=ids.join(',');
 const indicadores=useMemo(()=>idsKey.split(',').map(id=>dados.indicadores.find(i=>i.id===id)).filter((i):i is Snapshot['indicadores'][number]=>Boolean(i)),[dados,idsKey]);
 const territorios=dados.territorios;
 const grupos=useMemo(()=>Array.from(new Set(dados.observacoes.map(o=>o.grupo))).sort((a,b)=>a==='Total'?-1:b==='Total'?1:a.localeCompare(b,'pt-BR')),[dados]);
 const nacional=territorios.find(t=>t.nivel==='brasil')??territorios[0];
 const esquema=useMemo(()=>({med:campo(tiposUrl.opcao(indicadores.map(i=>i.id)),indicadores[0]?.id??''),ter:campo(tiposUrl.opcao(territorios.map(t=>t.id)),nacional?.id??''),per:campo(tiposUrl.texto({max:20}),''),sexo:campo(tiposUrl.opcao(['total','homens','mulheres'] as const),'total' as const),grp:campo(tiposUrl.opcao(grupos),'Total'),vis:campo(tiposUrl.opcao(['grafico','tabela'] as const),'grafico' as const)}),[indicadores,territorios,nacional?.id,grupos]);
 const [estado,definir]=useEstadoUrl(esquema);const [aviso,setAviso]=useState('');
 const med=indicadores.find(i=>i.id===estado.med)??indicadores[0];
 const ter=territorios.find(t=>t.id===estado.ter)??nacional;
 const baseMed=dados.observacoes.filter(o=>o.indicadorId===med?.id);
 const elegiveis=new Set(baseMed.map(o=>o.territorioId));
 const gruposMed=Array.from(new Set(baseMed.filter(o=>o.territorioId===ter?.id).map(o=>o.grupo)));
 const sexosMed=Array.from(new Set(baseMed.filter(o=>o.territorioId===ter?.id&&o.grupo===estado.grp).map(o=>o.sexo)));
 const linhas=baseMed.filter(o=>o.sexo===estado.sexo&&o.grupo===estado.grp);
 const estrutural=med?.fonteId.startsWith('censo');
 const formal=['estoque-formal','saldo-formal'].includes(med?.id??'');
 const periodos=Array.from(new Map(linhas.map(o=>[o.periodo,o.periodoNome])).entries()).sort((a,b)=>a[0].localeCompare(b[0]));
 const periodo=periodos.some(p=>p[0]===estado.per)?estado.per:periodos.at(-1)?.[0]??'';
 const serie=linhas.filter(o=>o.territorioId===ter?.id).sort((a,b)=>a.periodo.localeCompare(b.periodo));
 const selecionado=serie.find(o=>o.periodo===periodo);
 const anterior=serie.filter(o=>o.periodo<periodo&&o.valor!==null).at(-1);
 const fonte=dados.fontes.find(f=>f.id===(selecionado?.fonteId??linhas.find(o=>o.territorioId===ter?.id)?.fonteId??med?.fonteId));
 const quebraVisita=fonte?.limitacoes.some(n=>n.includes('2020')&&n.includes('visita'))??false;
 const pares=linhas.filter(o=>o.periodo===periodo&&territorios.some(t=>t.id===o.territorioId&&t.nivel==='uf')).map(o=>({...o,nome:territorios.find(t=>t.id===o.territorioId)?.nome??o.territorioId})).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));
 const max=Math.max(...pares.map(p=>p.valor??0),1);
 const disponiveis=serie.filter(o=>o.valor!==null);
 const ult=disponiveis.at(-1);const primeiro=disponiveis[0];
 const porcentagem=med?.unidade.includes('%')||med?.unidade.toLowerCase().includes('percent');
 const diferenca=selecionado?.valor!==null&&selecionado?.valor!==undefined&&anterior?.valor!==null&&anterior?.valor!==undefined?selecionado.valor-anterior.valor:null;
 const csv=(obs:typeof linhas)=>['territorio;indicador;unidade;periodo;sexo;grupo;valor;estado;cv_percentual;fonte;universo;limitacao;capturado_em',...obs.map(o=>[territorios.find(t=>t.id===o.territorioId)?.nome,med?.nome,med?.unidade,o.periodoNome,o.sexo,o.grupo??'total',o.valor===null?'':String(o.valor).replace('.',','),o.status,o.cv,dados.fontes.find(f=>f.id===o.fonteId)?.consulta??fonte?.url,med?.universo,med?.limitacao,dados.capturadoEm].map(celula).join(';'))].join('\r\n');
 if(!med||!ter)return <div className="tr-empty"><h1>Base indisponível</h1><p>Nenhum valor é exibido no lugar dos dados ausentes.</p></div>;
 return <><header className="tr-hero"><p className="tr-kicker">Trabalho e renda · {estrutural?'Retrato estrutural':formal?'Emprego formal':'Conjuntura'}</p><h1>{titulo}</h1><p className="tr-lead">{pergunta}</p></header><NavegacaoTrabalho/><RecorteTrabalho resumo={`${med.nome} · ${nomeTerritorio(ter)} · ${periodos.find(p=>p[0]===periodo)?.[1]??'Sem período'} · ${estado.sexo} · ${estado.grp}`}><div className="tr-controls"><label>Indicador<select value={med.id} onChange={e=>definir({med:e.target.value,per:''})}>{indicadores.map(i=><option value={i.id} key={i.id}>{i.nome}</option>)}</select></label><SeletorTerritorioTrabalho territorios={territorios} elegiveis={elegiveis} selecionado={ter.id} onChange={id=>definir({ter:id})}/><label>Período<select value={periodo} onChange={e=>definir({per:e.target.value})}>{periodos.map(p=><option key={p[0]} value={p[0]}>{p[1]}</option>)}</select></label><label>População<select value={estado.sexo} onChange={e=>definir({sexo:e.target.value as typeof estado.sexo,per:''})}><option value="total">Total</option><option value="homens" disabled={!sexosMed.includes("homens")}>Homens{!sexosMed.includes("homens")?" · indisponível":""}</option><option value="mulheres" disabled={!sexosMed.includes("mulheres")}>Mulheres{!sexosMed.includes("mulheres")?" · indisponível":""}</option></select></label><label>{med.id==='renda-por-decil'?'Faixa de renda':med.id.startsWith('ocupacoes')?'Grupo ocupacional':med.id==='jornada-habitual'?'Grupo de idade':'Grupo da população'}<select value={estado.grp} onChange={e=>definir({grp:e.target.value,per:''})}>{grupos.filter(g=>gruposMed.includes(g)||g===estado.grp).map(g=><option key={g} value={g}>{g}{!gruposMed.includes(g)?' · indisponível':''}</option>)}</select></label></div><div className="tr-actions"><button className="secondary" onClick={()=>definir({med:indicadores[0].id,ter:nacional.id,per:'',sexo:'total',grp:'Total',vis:'grafico'})}>Limpar recorte</button><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.href);setAviso('Link do recorte copiado.')}catch{setAviso('Copie o endereço da página para compartilhar o recorte.')}}}>Copiar link do recorte</button><span role="status">{aviso}</span></div></RecorteTrabalho>{(!elegiveis.has(ter.id)||!sexosMed.includes(estado.sexo)||!gruposMed.includes(estado.grp))&&<p className="tr-note"><strong>Recorte fora da cobertura.</strong> Esta combinação de território, população e medida não tem observações nesta publicação. Nenhum valor de outro território é colocado no lugar. Escolha um território ou população disponível.</p>}
 <div className="tr-kpis"><div className="tr-kpi"><span>{med.nome} · {nomeTerritorio(ter)}</span><strong>{formato(selecionado?.valor??null,med.unidade)}</strong><span>{selecionado?.periodoNome??periodos.find(p=>p[0]===periodo)?.[1]} · {estado.sexo} · {estado.grp}{selecionado?.cv!==null&&selecionado?.cv!==undefined?` · CV ${selecionado.cv.toLocaleString('pt-BR')}%`:''}</span></div><div className="tr-kpi"><span>{estrutural?'Referência estrutural':'Diferença para o período anterior disponível'}</span><strong>{estrutural?'2022':diferenca===null?'Não disponível':porcentagem?`${diferenca>0?'+':''}${diferenca.toLocaleString('pt-BR',{maximumFractionDigits:1})} p.p.`:med.unidade==='índice'?`${diferenca>0?'+':''}${diferenca.toLocaleString('pt-BR',{maximumFractionDigits:3})} pontos de índice`:formato(diferenca,med.unidade)}</strong><span>{estrutural?'Censo · semana de referência em julho de 2022':`${anterior?.periodoNome??'Sem referência anterior'} · mesma medida e território`}</span></div><div className="tr-kpi"><span>{formal?'Âmbito da série':'Cobertura na comparação estadual'}</span><strong>{formal?'Brasil':`${pares.filter(p=>p.valor!==null).length} / ${Array.from(elegiveis).filter(id=>territorios.some(t=>t.id===id&&t.nivel==='uf')).length}`}</strong><span>{formal?'Vínculos por estabelecimento · cobertura nacional':'Unidades da Federação com valor disponível no recorte'}</span></div></div><p className="tr-note"><strong>Universo da medida:</strong> {med.universo} {med.limitacao} {selecionado?.cv!==null&&selecionado?.cv!==undefined?'CV é o coeficiente de variação da estimativa; não é um intervalo de confiança.':''} {estrutural?'O Censo é um retrato de 2022: não descreve a conjuntura atual.':'Resultados por residência nas pesquisas do IBGE; vínculos por estabelecimento no Novo Caged. Diferenças observadas não demonstram efeito de uma política pública.'}</p>{dados.indicadores.some(i=>i.id==='renda-por-decil')&&<DistribuicaoRendaTrabalho dados={dados} territorio={ter.id} periodo={periodo} nome={nomeTerritorio(ter)}/>} {med.id.startsWith('ocupacoes')&&<GruposOcupacoes dados={dados} territorio={ter.id} sexo={estado.sexo} periodo={periodo} nome={nomeTerritorio(ter)}/>}
 <section className="tr-section" aria-labelledby="tr-evolucao"><div className="tr-section-head"><h2 id="tr-evolucao">{estrutural?'O retrato do período':'Como evoluiu?'}</h2><p>{med.nome} · {med.unidade} · {nomeTerritorio(ter)}. {estrutural?'Sem série temporal compatível nesta publicação.':'Cada ponto mantém o período da fonte, sem interpolação de ausências.'}</p></div>{fonte?.limitacoes.filter(n=>n.includes('visita')||n.includes('percentis')||n.includes('coexistir')).map((n,i)=><p className="tr-note" key={i}>{n}{n.includes('visita')?' A linha é interrompida nas fronteiras de 2020 e 2023 para sinalizar a alteração de coleta.':''}</p>)}<div className="tr-actions"><button className={estado.vis==='grafico'?'':'secondary'} aria-pressed={estado.vis==='grafico'} onClick={()=>definir({vis:'grafico'})}>Gráfico</button><button className={estado.vis==='tabela'?'':'secondary'} aria-pressed={estado.vis==='tabela'} onClick={()=>definir({vis:'tabela'})}>Tabela equivalente</button><button className="secondary" onClick={()=>baixar(`trabalho-renda-${med.id}-${ter.id}-serie.csv`,csv(serie))}>Baixar série CSV</button></div>{estado.vis==='tabela'?<Tabela linhas={serie.map(o=>({nome:o.periodoNome,valor:o.valor,status:o.status}))} titulo={`Série de ${med.nome} · ${nomeTerritorio(ter)}`} unidade={med.unidade}/>:<div className="tr-chart">{disponiveis.length>1?<GraficoSerie pontos={serie} unidade={med.unidade} selecionado={periodo} quebras={quebraVisita?[2020,2023]:[]}/>:<p className="tr-empty">{formato(selecionado?.valor??null,med.unidade)} · {selecionado?.periodoNome??'Sem observação no recorte'}. Uma única referência temporal está disponível; não há uma linha de evolução.</p>}<p className="tr-source">Fonte: <a href={fonte?.url}>{fonte?.nome}</a> · {med.universo}.</p></div>}{primeiro&&ult&&primeiro!==ult&&<p className="tr-chart-description">A série disponível vai de {primeiro.periodoNome} ({formato(primeiro.valor,med.unidade)}) a {ult.periodoNome} ({formato(ult.valor,med.unidade)}). O período selecionado pode ser anterior ao último disponível.</p>}</section>
 {!formal?<section className="tr-section" aria-labelledby="tr-comparacao"><div className="tr-section-head"><h2 id="tr-comparacao">Como se comparam os estados?</h2><p>Mesma medida, período e população. Ordem alfabética; o destaque identifica a seleção. {med.fonteId.startsWith('mds')?'Brasil e estados são somas dos registros municipais extraídos do Cadastro Único. A cobertura depende dos registros presentes na captura.':'Brasil é uma estimativa própria, não a média simples dos estados.'}</p></div><div className="tr-chart">{formal&&<p className="tr-note">Esta série tem cobertura nacional. Não há comparação estadual publicada para o Novo Caged neste conjunto.</p>}<ul className="tr-barlist">{pares.map(p=><li key={p.territorioId} data-foco={p.territorioId===ter.id}><span>{p.nome}</span><div aria-hidden="true" className="tr-bartrack"><div className="tr-bar" style={{width:p.valor===null?0:`${p.valor/max*100}%`}}/></div><strong>{formato(p.valor,med.unidade)}</strong></li>)}</ul>{!pares.length&&<p className="tr-empty">Nenhum estado com observação para esta população e período. Selecione outro recorte.</p>}<p className="tr-source">Barras começam em zero · unidade: {med.unidade} · fonte: {fonte?.nome}.</p></div><details><summary>Tabela equivalente · {pares.length} estados</summary><Tabela linhas={pares.map(p=>({nome:p.nome,valor:p.valor,status:p.status}))} titulo={`Comparação estadual · ${selecionado?.periodoNome??periodo}`} unidade={med.unidade}/></details><div className="tr-actions"><button className="secondary" onClick={()=>baixar(`trabalho-renda-${med.id}-${periodo}-estados.csv`,csv(pares))}>Baixar comparação CSV</button></div></section>:<ComplementoEmpregoFormal dados={dados} indicadorAtual={med.id} periodo={periodo}/>}
 <section className="tr-section"><h2>Antes de interpretar</h2><div className="tr-grid"><div><h3>O que este número permite</h3><p className="tr-chart-description">Comparar a mesma medida no tempo ou entre territórios compatíveis. O recorte por população altera o universo e deve acompanhar qualquer comparação.</p></div><div><h3>O que ele não demonstra</h3><p className="tr-chart-description">Não identifica causas, qualidade da gestão ou trajetória de uma pessoa. Média e mediana são medidas distintas; o rendimento real do trabalho não equivale à renda domiciliar por pessoa.</p></div></div><details><summary>Fonte, captura e método da medida</summary><p><strong>{fonte?.nome}</strong> · <a href={fonte?.url}>Abrir fonte oficial</a></p><p>Universo: {med.universo}. Unidade: {med.unidade}. Captura do conjunto: {new Date(dados.capturadoEm).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} (Brasília). Períodos de referência são os de cada observação, não a data da captura.</p><p>{med.limitacao}</p><p>{fonte?.limitacoes?.join(' ')}</p></details><div className="tr-footer-nav"><Link href={`${BASE}/metodos`}>Método e cobertura completa →</Link><Link href={BASE}>Voltar ao panorama →</Link></div></section></>;
}
function Tabela({linhas,titulo,unidade}:{linhas:{nome:string;valor:number|null;status:string}[];titulo:string;unidade:string}){return <div className="tr-table-scroll" tabIndex={0} role="region" aria-label={titulo}><table><caption>{titulo}</caption><thead><tr><th scope="col">Referência</th><th scope="col">Estado do dado</th><th scope="col">Valor · {unidade}</th></tr></thead><tbody>{linhas.map((p,i)=><tr key={i}><th scope="row">{p.nome}</th><td>{p.valor===null?'Ausente':p.status==='observado'?'Observado':p.status}</td><td>{formato(p.valor,unidade)}</td></tr>)}</tbody></table></div>}
export function GraficoSerie({pontos,unidade,selecionado,quebras=[]}:{pontos:Snapshot['observacoes'];unidade:string;selecionado:string;quebras?:number[]}){const [ref,largura]=useLargura<HTMLDivElement>(600);const validos=pontos.filter(p=>p.valor!==null);const max=unidade==='índice'?1:Math.max(...validos.map(p=>p.valor as number),1)*1.12;const min=Math.min(0,...validos.map(p=>p.valor as number));const w=Math.max(largura,240),h=280,left=70,right=20,top=20,bottom=45;const tempo=(p:string)=>p.includes('-')?Number(p.slice(0,4))*12+Number(p.slice(5,7))-1:p.length===6?Number(p.slice(0,4))*12+(Number(p.slice(4))-1)*3:Number(p)*12;const inicio=tempo(pontos[0].periodo),fim=tempo(pontos.at(-1)!.periodo);const x=(i:number)=>left+(tempo(pontos[i].periodo)-inicio)*(w-left-right)/Math.max(1,fim-inicio);const y=(v:number)=>h-bottom-(v-min)/(max-min)*(h-bottom-top);let path='';let lacuna=true;pontos.forEach((p,i)=>{const intervalo=p.periodo.includes('-')?1:p.periodo.length===6?3:12;if(i>0&&(tempo(p.periodo)-tempo(pontos[i-1].periodo)>intervalo||quebras.includes(Number(p.periodo.slice(0,4)))))lacuna=true;if(p.valor===null){lacuna=true;return;}path+=`${lacuna?'M':'L'}${x(i)},${y(p.valor)} `;lacuna=false});const ticks=[min,min+(max-min)/3,min+(max-min)*2/3,max];return <div ref={ref}><p className="tr-chart-description">{unidade}. O círculo maior marca o período selecionado. Lacunas na cobertura interrompem a linha. É possível consultar os valores de cada período na tabela equivalente.</p><svg role="img" aria-label={`Evolução temporal: ${validos.length} observações disponíveis; unidade ${unidade}. Valores exatos na tabela equivalente.`} viewBox={`0 0 ${w} ${h}`}><title>Série temporal sem interpolação de valores ausentes</title>{ticks.map(v=><g key={v}><line x1={left} x2={w-right} y1={y(v)} y2={y(v)} stroke="var(--cor-linha)"/><text x={left-10} y={y(v)+4} textAnchor="end" fill="var(--cor-carvao-muted)" fontSize="14">{v.toLocaleString('pt-BR',{notation:Math.abs(v)>=10000?'compact':'standard',maximumFractionDigits:unidade==='índice'?2:1})}</text></g>)}<path d={path} fill="none" stroke="var(--cor-obee)" strokeWidth="3"/>{pontos.map((p,i)=>p.valor===null?null:<circle key={p.periodo} cx={x(i)} cy={y(p.valor)} r={p.periodo===selecionado?6:3} fill={p.periodo===selecionado?'var(--cor-obee-tinta)':'var(--cor-obee)'}><title>{`${p.periodoNome}: ${formato(p.valor,unidade)}`}</title></circle>)}{(w<350?[0,pontos.length-1]:[0,Math.floor((pontos.length-1)/2),pontos.length-1]).filter((v,i,a)=>a.indexOf(v)===i).map(i=><text key={i} x={x(i)} y={h-12} textAnchor={i===0?'start':i===pontos.length-1?'end':'middle'} fill="var(--cor-carvao-muted)" fontSize="14">{w<500?pontos[i].periodoNome.replace(/(\d)º trimestre (\d+)/,'T$1/$2').replace(' de ','/').replace(/^(\w{3})\w+\//,'$1/'):pontos[i].periodoNome}</text>)}</svg></div>}

function ComplementoEmpregoFormal({dados,indicadorAtual,periodo}:{dados:Snapshot;indicadorAtual:string;periodo:string}){const id=indicadorAtual==='estoque-formal'?'saldo-formal':'estoque-formal';const med=dados.indicadores.find(i=>i.id===id);const pontos=dados.observacoes.filter(o=>o.indicadorId===id&&o.territorioId==='1'&&o.sexo==='total'&&o.grupo==='Total').sort((a,b)=>a.periodo.localeCompare(b.periodo));const fonte=dados.fontes.find(f=>f.id===med?.fonteId);if(!med)return null;return <section className="tr-section"><h2>{id==='saldo-formal'?'A variação mensal do estoque':'O estoque de vínculos'}</h2><p className="tr-chart-description">Brasil · {med.universo} {med.limitacao}</p><div className="tr-chart"><GraficoSerie pontos={pontos} unidade={med.unidade} selecionado={periodo}/><p className="tr-source">Fonte: <a href={fonte?.url}>{fonte?.nome}</a>. Cobertura nacional nesta publicação; sem comparação estadual.</p></div><details><summary>Tabela equivalente · {med.nome}</summary><Tabela linhas={pontos.map(o=>({nome:o.periodoNome,valor:o.valor,status:o.status}))} titulo={med.nome+' · Brasil'} unidade={med.unidade}/></details><div className="tr-actions"><button className="secondary" onClick={()=>baixar(`novo-caged-${id}-brasil.csv`,['periodo;indicador;unidade;valor;fonte;universo',...pontos.map(o=>[o.periodoNome,med.nome,med.unidade,o.valor,dados.fontes.find(f=>f.id===o.fonteId)?.consulta,med.universo].map(celula).join(';'))].join('\r\n'))}>Baixar série complementar CSV</button></div><p className="tr-note">Estoque é a quantidade de vínculos em um momento. A variação mensal apresentada é a diferença entre o estoque do mês e o do mês anterior na série SGS 28763; não é uma série oficial de admissões menos desligamentos. Vínculos não equivalem a pessoas únicas. As séries podem ser revisadas e não recebem ajuste sazonal.</p></section>}
