import type {SnapshotTrabalhoRenda} from '@/lib/eficiencia/trabalho-renda/tipos';
export type Snapshot=SnapshotTrabalhoRenda;
export const BASE='/eficiencia-estatal/trabalho-renda';
export const PAGINAS=[{slug:'',nome:'Panorama'},{slug:'acesso-ao-trabalho',nome:'Acesso ao trabalho'},{slug:'ocupacoes',nome:'Ocupações'},{slug:'qualificacao',nome:'Qualificação'},{slug:'qualidade-do-trabalho',nome:'Qualidade'},{slug:'renda-do-trabalho',nome:'Renda do trabalho'},{slug:'renda-das-familias',nome:'Renda das famílias'},{slug:'desigualdade',nome:'Desigualdade'},{slug:'cadastro-unico',nome:'Cadastro Único'},{slug:'protecao-da-renda',nome:'Proteção da renda'},{slug:'emprego-formal',nome:'Emprego formal'},{slug:'recursos',nome:'Recursos públicos'},{slug:'comparar',nome:'Comparar'},{slug:'metodos',nome:'Método e cobertura'}];
export const DIMENSOES=[
 {nome:'Panorama do território',pergunta:'Como estão trabalho e renda aqui?',slug:'',estado:'publicado',nota:'Síntese da conjuntura e do retrato estrutural, em calendários separados.'},
 {nome:'Acesso ao trabalho',pergunta:'Quem participa e quem encontra trabalho?',slug:'acesso-ao-trabalho',estado:'publicado',nota:'Participação, desocupação e subutilização na PNAD Contínua.'},
 {nome:'Emprego formal',pergunta:'Como evolui o estoque de vínculos formais?',slug:'emprego-formal',estado:'parcial',nota:'Estoque nacional de vínculos e variação mensal calculada a partir da série divulgada no SGS. Recortes estaduais, municipais e ocupacionais ainda não integrados.'},
 {nome:'Qualidade do trabalho',pergunta:'Quanto do trabalho está na informalidade?',slug:'qualidade-do-trabalho',estado:'parcial',nota:'Informalidade e jornada habitual observadas. Jornada sem referências de 2020 a 2022. Proteção e estabilidade ainda não integradas.'},
 {nome:'Ocupações e oportunidades',pergunta:'Que trabalhos existem e quanto remuneram?',slug:'ocupacoes',estado:'parcial',nota:'Grupos ocupacionais, rendimento e pessoas com rendimento no Censo 2022. Não mostra vagas disponíveis ou salários de admissão.'},
 {nome:'Renda das famílias',pergunta:'Como a renda se distribui entre os domicílios?',slug:'renda-das-familias',estado:'parcial',nota:'Média e mediana da renda domiciliar por pessoa no Censo 2022. Composição ainda não integrada.'},
 {nome:'Desigualdade e vulnerabilidade',pergunta:'Quem participa menos dos ganhos?',slug:'desigualdade',estado:'parcial',nota:'Índice de Gini da PNAD e média/mediana do Censo em calendários separados. Sem linha de pobreza nesta publicação.'},
 {nome:'Poder de compra',pergunta:'O rendimento cresceu em termos reais?',slug:'renda-do-trabalho',estado:'parcial',nota:'Rendimento real habitual do trabalho. Orçamento e despesas essenciais ainda não integrados.'},
 {nome:'Proteção da renda',pergunta:'Que proteção chega às famílias?',slug:'protecao-da-renda',estado:'parcial',nota:'Estimativa PNAD de domicílios que declararam receber programas sociais e Cadastro Único em painel separado. Sem valores de benefícios ou taxa de cobertura de elegíveis.'},
 {nome:'Qualificação e intermediação',pergunta:'Como os serviços ajudam a chegar ao emprego?',slug:'qualificacao',estado:'parcial',nota:'Catálogo de cursos de aprendizagem autorizados, com vigência e localidade. Não indica vagas disponíveis, concluintes, encaminhamentos ou colocações.'},
 {nome:'Recursos e entregas públicas',pergunta:'Quanto se aplica e o que se entrega?',slug:'recursos',estado:'parcial',nota:'Despesa municipal na função Trabalho nas 26 capitais estaduais, com conferência DCA × RREO. Não há custo por atendimento ou cobertura de toda a política pública.'},
 {nome:'Trajetórias e mobilidade',pergunta:'As pessoas conseguem melhorar sua situação?',estado:'não publicado',nota:'Transições individuais exigem desenho longitudinal; séries agregadas não mostram mobilidade pessoal.'},
];
export function formato(valor:number|null,unidade:string){if(valor===null)return 'Não disponível';return unidade.includes('%')||unidade.toLowerCase().includes('percent')?`${valor.toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`:unidade.includes('R$')||unidade.toLowerCase().includes('real')?`R$ ${valor.toLocaleString('pt-BR',{maximumFractionDigits:2})}`:valor.toLocaleString('pt-BR',{maximumFractionDigits:unidade==='índice'?3:2});}
export function total(grupo?:string){return !grupo||grupo==='total'||grupo==='Total';}

const UF_POR_CODIGO:Record<string,string>={'11':'RO','12':'AC','13':'AM','14':'RR','15':'PA','16':'AP','17':'TO','21':'MA','22':'PI','23':'CE','24':'RN','25':'PB','26':'PE','27':'AL','28':'SE','29':'BA','31':'MG','32':'ES','33':'RJ','35':'SP','41':'PR','42':'SC','43':'RS','50':'MS','51':'MT','52':'GO','53':'DF'};
export function nomeTerritorio(t:Snapshot['territorios'][number]){const uf=UF_POR_CODIGO[t.id.slice(0,2)]??t.id.slice(0,2);return t.nivel==='municipio'&&!new RegExp(`(?:[-–]\\s*${uf}|\\(${uf}\\))$`).test(t.nome.trim())?`${t.nome} (${uf})`:t.nome;}
