"""Métricas do módulo Conta de luz (P047 a P050). A fórmula roda em
pipeline/energia/modulos/conta.py; a interface lê o valor calculado e esta definição."""

_GOLD = "conta.json"
_PAG = ["/setor-eletrico/conta-de-luz"]
_TARIFAS = ["aneel_tarifas_aplicacao"]
_AUSENCIA_TARIFA = ("Distribuidora sem vigência cobrindo a data fica fora e é listada em sem_vigente; TE e TUSD iguais "
                    "a zero na mesma linha (',00' na fonte) são tarifa não homologada para a subclasse e não entram; "
                    "nunca se repete a vigência anterior.")
_SEM_TRIBUTOS = "Sem ICMS, PIS/Pasep, Cofins, contribuição de iluminação pública e bandeira."

METRICAS = [
    {
        "id": "conta_tarifa_b1_aplicacao",
        "titulo": "Tarifa de aplicação residencial B1 convencional",
        "pergunta": "Quanto a distribuidora cobra por kWh de um consumidor residencial comum, antes de tributos?",
        "definicao": "Soma da Tarifa de Energia (TE) e da Tarifa de Uso do Sistema de Distribuição (TUSD) de aplicação homologadas pela ANEEL para o subgrupo B1, subclasse residencial, modalidade convencional, na vigência que cobre a data de referência. " + _SEM_TRIBUTOS,
        "unidade": "R$/MWh (divida por 1000 para R$/kWh)",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "vigência (resolução homologatória)",
        "fontes": _TARIFAS,
        "formula": "TE_aplicação + TUSD_aplicação",
        "regra_agregacao": "Não se soma entre distribuidoras. Resumo nacional = mediana, 25º e 75º percentis entre distribuidoras (quantil tipo 7), sem ponderação por consumo.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "vigência", "base tarifária (aplicação ou base econômica)"],
        "regras_comparabilidade": ["Só compara a mesma modalidade (convencional), subgrupo e subclasse.",
                                   "Tarifa de aplicação e base econômica não se misturam.",
                                   "Não é tarifa média de fornecimento nem conta final."],
        "regra_cobertura": "Distribuidoras com linha B1 residencial convencional de aplicação, unidade MWh, cuja vigência cobre a data de referência.",
        "politica_ausencia": _AUSENCIA_TARIFA,
        "validacoes": ["TE e TUSD iguais no conjunto de tarifas e no de componentes (tolerância 0,005 R$/MWh).",
                       "Unidade MWh conferida linha a linha; linha em kW fica fora e é contada.",
                       "Vigências sobrepostas com valores diferentes resolvidas pela regra publicada e listadas em conflitos_fonte."],
        "limitacoes": ["Mediana entre distribuidoras não representa o consumidor médio do país.",
                       "Permissionárias com vigência encerrada e sucessora ainda não publicada no conjunto ficam fora na data."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "conta_custo_perfil",
        "titulo": "Custo da energia para um perfil de consumo de referência",
        "pergunta": "Quanto custaria, antes de tributos, consumir 100, 200 ou 300 kWh em cada distribuidora?",
        "definicao": "Consumo do perfil (kWh/mês) multiplicado pela tarifa de aplicação B1 residencial convencional. Perfis definidos pelo observatório para comparação; não são consumo médio. " + _SEM_TRIBUTOS,
        "unidade": "R$/mês",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "vigência",
        "fontes": _TARIFAS,
        "formula": "kWh_perfil × (TE + TUSD) ÷ 1000",
        "numerador": "kWh do perfil × (TE + TUSD) em R$/MWh",
        "denominador": "1000 kWh por MWh",
        "regra_agregacao": "Por distribuidora; resumo nacional pela mediana da tarifa aplicada ao perfil.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "perfil (100, 200, 300 kWh)"],
        "regras_comparabilidade": ["Mesmo perfil e mesma data de referência para todas as distribuidoras.",
                                   "Perfis a partir de 100 kWh não são afetados pelo custo de disponibilidade (mínimo de 30, 50 ou 100 kWh)."],
        "regra_cobertura": "Igual à da tarifa B1.",
        "politica_ausencia": _AUSENCIA_TARIFA,
        "validacoes": ["Custo = perfil × tarifa conferido por releitura do CSV original no teste."],
        "limitacoes": ["Sem bandeira: a bandeira vigente é mostrada à parte.", "Não inclui descontos sociais."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "conta_composicao_grupo",
        "titulo": "Composição da tarifa B1 por grupo de componentes",
        "pergunta": "Para onde vai o valor pago por kWh: energia, transmissão, distribuição, perdas ou encargos?",
        "definicao": "Soma das componentes tarifárias oficiais da TE e da TUSD de aplicação B1 residencial, agrupadas por código em energia comprada, transmissão e conexão, distribuição (fio B), perdas e receitas irrecuperáveis, encargos setoriais e outros ajustes. O agrupamento é do observatório; cada código fica visível.",
        "unidade": "R$/MWh e % da tarifa",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "vigência",
        "fontes": ["aneel_componentes_tarifarias", "aneel_tarifas_aplicacao"],
        "formula": "grupo(g) = Σ componentes com GRUPO = g; participação = grupo ÷ (TE + TUSD)",
        "numerador": "Σ das componentes do grupo (R$/MWh)",
        "denominador": "TE + TUSD de aplicação (R$/MWh)",
        "regra_agregacao": "Por distribuidora; resumo nacional pela mediana de cada grupo (as medianas não somam o total).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "grupo", "componente"],
        "regras_comparabilidade": ["Componentes já estão dentro da TE e da TUSD: nada é somado por fora.",
                                   "Componentes negativas (devoluções) reduzem o grupo e são mantidas."],
        "regra_cobertura": "Distribuidoras com tarifa B1 vigente e componentes publicadas para o mesmo ato e vigência.",
        "politica_ausencia": "Componente ausente não vira zero; distribuidora sem componentes para o ato vigente fica listada em reconciliacao.sem_componentes.",
        "validacoes": ["Soma das parcelas = TE e TUSD publicadas no próprio conjunto (tolerância 0,01 R$/MWh).",
                       "TE e TUSD do conjunto de componentes = TE e TUSD do conjunto de tarifas (tolerância 0,005 R$/MWh)."],
        "limitacoes": ["O PRORET 7.1, que define as componentes, não pôde ser lido (acesso bloqueado); o grupo é classificação do observatório.",
                       "Tributos e iluminação pública não fazem parte da tarifa."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "conta_simulacao",
        "titulo": "Estimativa do valor da energia na fatura (simulador)",
        "pergunta": "Como o valor da energia na minha conta varia com o consumo, a classe e a bandeira?",
        "definicao": "Estimativa mensal para uma unidade de baixa tensão: energia faturada pelas faixas da classe (Tarifa Social: 100% de desconto até 80 kWh; Desconto Social: faixa sem CDE até 120 kWh), custo de disponibilidade (30, 50 ou 100 kWh) onde se aplica, e adicional de bandeira por kWh consumido. " + _SEM_TRIBUTOS.replace(" e bandeira", ""),
        "unidade": "R$/mês",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "vigência na data de referência",
        "fontes": ["aneel_tarifas_aplicacao", "aneel_bandeiras_tarifarias", "normas_conta"],
        "formula": "Σ faixas (kWh da faixa × (TE + TUSD) da faixa ÷ 1000) − descontos + kWh sujeitos à bandeira × adicional ÷ 1000",
        "regra_agregacao": "Não se agrega: é uma estimativa por cenário.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["distribuidora", "classe", "consumo (kWh)", "tipo de ligação", "bandeira"],
        "regras_comparabilidade": ["Resultado rotulado como estimativa sem tributos; não é a fatura."],
        "regra_cobertura": "Distribuidoras com tarifa da classe publicada na vigência; classe sem tarifa devolve indisponível com motivo.",
        "politica_ausencia": "Tarifa da classe ausente torna a simulação indisponível para aquela classe; não se usa tarifa de outra classe.",
        "validacoes": ["Casos de referência calculados no pipeline (casos_referencia) devem ser reproduzidos pela interface.",
                       "Trechos das normas conferidos a cada captura (simulador.normas)."],
        "limitacoes": ["Desconto Social por parcela e bandeira na Tarifa Social são leituras declaradas (REN não lida por bloqueio de acesso).",
                       "Custo de disponibilidade da Tarifa Social acima de 80 kWh não modelado."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "conta_variacao_tarifa_b1",
        "titulo": "Variação da tarifa B1 entre vigências e comparação com o IPCA",
        "pergunta": "Quanto a tarifa residencial mudou em cada ato e em relação à inflação do mesmo período?",
        "definicao": "Variação percentual da tarifa de aplicação B1 residencial convencional (TE + TUSD) entre pedaços contíguos da linha do tempo; comparação com o IPCA do IBGE no mesmo intervalo (índices do mês anterior a cada data) e, nas janelas de 12, 60 e 120 meses, entre as tarifas vigentes no último dia dos meses inicial e final do IPCA.",
        "unidade": "%",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "evento tarifário; janelas de 12, 60 e 120 meses",
        "fontes": ["aneel_tarifas_aplicacao", "ibge_ipca"],
        "formula": "variação = total_depois ÷ total_antes − 1; IPCA = I(mês final) ÷ I(mês inicial) − 1; real = (1 + variação) ÷ (1 + IPCA) − 1",
        "numerador": "tarifa depois (R$/MWh)",
        "denominador": "tarifa antes (R$/MWh)",
        "regra_agregacao": "Por distribuidora; resumo por mediana e quartis entre distribuidoras; contagem das acima e abaixo do IPCA.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "evento", "janela"],
        "regras_comparabilidade": ["Tarifa e IPCA sempre nos mesmos meses.",
                                   "Não é o efeito médio do processo tarifário (que pondera todas as classes).",
                                   "Diferença entre PLD e tarifa não é margem da distribuidora."],
        "regra_cobertura": "Distribuidoras com tarifa nas duas datas; as demais são contadas como excluídas.",
        "politica_ausencia": "Sem tarifa em uma das datas ou sem índice publicado no mês, a variação fica vazia.",
        "validacoes": ["IPCA de 12 meses pela razão de índices conferido com a variação publicada pelo IBGE (tolerância 0,01 ponto percentual)."],
        "limitacoes": ["O conjunto não diz se o ato é reajuste, revisão periódica ou extraordinária."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "conta_bandeira_adicional",
        "titulo": "Bandeira tarifária acionada e adicional por patamar",
        "pergunta": "Qual bandeira vigorou em cada mês e quanto ela acrescenta por kWh?",
        "definicao": "Bandeira acionada pela ANEEL para cada mês de competência e o adicional por MWh consumido definido na resolução vigente para cada patamar.",
        "unidade": "R$/MWh",
        "grao_geografico": "Sistema Interligado Nacional (consumidores cativos, exceto sistemas isolados)",
        "grao_temporal": "mensal",
        "fontes": ["aneel_bandeiras_tarifarias"],
        "regra_agregacao": "Valor publicado; contagem de meses por patamar e ano.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["mês", "patamar"],
        "regras_comparabilidade": ["Adicionais mudam por resolução: comparar meses de resoluções diferentes exige a tabela de adicionais."],
        "regra_cobertura": "Meses publicados no recurso de acionamento.",
        "politica_ausencia": "Mês não publicado não é preenchido nem repetido.",
        "validacoes": ["Valor acionado confere com a tabela de adicionais do mesmo conjunto.",
                       "Adicional da amarela confere com a página oficial da ANEEL (R$ 0,01885/kWh)."],
        "limitacoes": ["O dicionário descreve o campo como reais por kWh, mas os valores são R$/MWh."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "conta_subsidio_anual",
        "titulo": "Subsídios tarifários custeados pela CDE por categoria",
        "pergunta": "Quanto a CDE repassa às distribuidoras para cobrir descontos tarifários, e para quais categorias?",
        "definicao": "Soma, por ano de competência, dos repasses mensais homologados (montante Total = previsão + ajuste) a todas as distribuidoras, por categoria de desconto. Não são transferências a famílias; a Tarifa Social não integra o conjunto.",
        "unidade": "R$ nominais",
        "grao_geografico": "nacional e distribuidora",
        "grao_temporal": "anual (competência)",
        "fontes": ["aneel_subsidios_tarifarios"],
        "formula": "Σ distribuidoras Σ meses do ano do repasse Total da categoria",
        "regra_agregacao": "Soma de valores monetários nominais; a linha de categoria Total publicada é usada só como conferência.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["ano", "categoria", "distribuidora"],
        "regras_comparabilidade": ["Valores nominais: comparar anos distantes exige correção monetária.",
                                   "Ano com menos de 12 meses de competência é parcial."],
        "regra_cobertura": "Competências até o mês de referência; competências futuras homologadas ficam fora.",
        "politica_ausencia": "Célula vazia não entra na soma e não vira zero.",
        "validacoes": ["Categorias somam o Total publicado por distribuidora e mês (tolerância R$ 0,05).",
                       "Total = previsão + ajuste por categoria (tolerância R$ 0,05)."],
        "limitacoes": ["Valores homologados em resolução, não desembolso realizado."],
        "gold": _GOLD, "paginas": _PAG,
    },
]
