"""Métricas do módulo Expansão da oferta e da rede (P040 a P043). A fórmula roda em
pipeline/energia/modulos/expansao.py (com as funções de pipeline/energia/fontes/aneel_expansao.py
e pipeline/energia/fontes/epe_pde.py); a interface lê o valor calculado e esta definição,
nunca refaz a conta.

Três camadas nunca se misturam: o realizado (SIGA, liberações comerciais, obras
energizadas do SIGET), a carteira e suas previsões (RALIE, com a data da fotografia em
que cada previsão foi registrada) e o cenário (PDE 2035, edição fixa). MW é potência,
não energia; km de circuito, MVA e reais são grandezas diferentes e nunca somadas."""

_GOLD = "expansao.json"
_PAG = ["/setor-eletrico/expansao"]
_SIGA = ["aneel_siga"]
_RALIE = ["aneel_ralie"]
_LIB = ["aneel_liberacao_comercial"]
_ATOS = ["aneel_atos_outorga_geracao"]
_LEILOES = ["aneel_leiloes_transmissao"]
_SIGET = ["aneel_siget"]
_AGREG = ["aneel_capacidade_agregada"]
_PDE = ["epe_pde"]

_MW_NAO_ENERGIA = ("MW é potência instalada ou outorgada, não energia: a produção depende do fator de capacidade de cada "
                   "fonte, e garantia física ou energia firme são outras grandezas.")
_OUTORGA = ("Outorga não é capacidade que certamente entrará: parte da carteira é revogada ou sai do acompanhamento sem "
            "operar (ver o desfecho das coortes do RALIE).")
_UF_PRINCIPAL = ("Usina multiestadual é atribuída à UF principal informada pelo SIGA; a potência não é dividida entre UFs "
                 "(o número e a potência dessas usinas saem na gold, em capacidade_instalada.multiestaduais).")
_MARCADORES_SIGA = ("O SIGA usa 1900-01-03 para usina sem data de entrada em operação e coordenada 0 para localização não "
                    "informada: os dois viram ausência, nunca data ou ponto (0, 0).")
_DATA_BASE = ("Toda previsão tem data-base: a fotografia do RALIE (DatRalie) em que foi publicada. Nenhuma promessa antiga "
              "é reconstruída com o estoque atual; o histórico publicado pela ANEEL começa em 17/06/2021 e o histórico "
              "próprio do observatório, na primeira captura do RALIE atual.")
_PREVISAO_CONVENCIONAL = ("Datas atribuídas em bloco a milhares de unidades sem licença, sem acesso à rede ou com revogação "
                          "em avaliação (ex.: 13/09/2031 na fotografia de 18/09/2026) indicam previsão convencional da "
                          "fiscalização, não cronograma de obra.")
_RALIE_UNIVERSO = ("O RALIE cobre usinas em implantação acompanhadas pela fiscalização; unidades liberadas para operação "
                   "comercial deixam o relatório nas fotografias seguintes.")
_KM_CIRCUITO = ("km de circuito: no SIGET cada circuito é um módulo de linha com a extensão da linha (NumEtnLinTms), então "
                "linha de circuito duplo ou bipolo conta cada circuito.")
_REAIS_NOMINAIS = "Reais nominais da data de cada leilão, sem correção monetária."
_CENARIO = ("PDE 2035 é cenário de planejamento de uma edição específica (data-base das premissas janeiro de 2025, aprovado "
            "pela Portaria MME nº 923/2026), nunca realizado nem previsão; é publicado com selo CENÁRIO em camada separada.")
_PARCIAL = "O ano corrente é parcial e é marcado (ano_parcial); não compete com anos completos."
_DATA_EM_BLOCO = ("Data em bloco: previsão atribuída a pelo menos 100 usinas distintas na mesma fotografia (o maior complexo do "
                  "RALIE tem 41 usinas). Ela anda com a fotografia, cerca de 5 anos depois dela (13/09/2031 na fotografia de "
                  "18/09/2026), e por isso os números saem também sem essas unidades.")
_EPE_REDE = _EPE = ["epe_webmap_rede"]

METRICAS = [
    {
        "id": "expansao_capacidade_operacao",
        "titulo": "Capacidade instalada em operação (SIGA)",
        "pergunta": "Quanta potência de geração está em operação no Brasil, por fonte e por UF?",
        "definicao": "Soma da potência fiscalizada (MdaPotenciaFiscalizadaKw, potência em operação) das usinas do SIGA na fase Operação, uma por núcleo de CEG, convertida de kW para MW.",
        "unidade": "MW",
        "grao_geografico": "Brasil; UF principal da usina",
        "grao_temporal": "fotografia diária do SIGA (data de geração do arquivo)",
        "fontes": _SIGA,
        "formula": "capacidade(g) = Σ MdaPotenciaFiscalizadaKw das usinas em Operação no grupo g ÷ 1.000",
        "regra_agregacao": "Soma simples de potência das usinas do grupo (tipo, origem, fonte ou UF); participação = 100 × capacidade do grupo ÷ capacidade total.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["tipo de geração", "origem", "fonte", "UF"],
        "regras_comparabilidade": [_MW_NAO_ENERGIA, _UF_PRINCIPAL,
                                   "Capacidade cadastrada não se compara com geração verificada (ONS) sem converter por duração e fator de capacidade."],
        "regra_cobertura": "Todas as usinas do arquivo diário do SIGA na fase Operação (geração centralizada; a micro e minigeração distribuída não está no SIGA).",
        "politica_ausencia": "Potência vazia não soma; núcleo de CEG repetido na fonte conta uma vez (as repetições são registradas no silver).",
        "validacoes": ["Potência negativa é violação crítica (a gold não é publicada).",
                       "Reconciliação por tipo com o agregado oficial 'empreendimentos em operação' e por UF com 'capacidade instalada por UF', descontando as liberações comerciais do intervalo: resíduo dentro de 1% do grupo ou ressalva publicada.",
                       "Usina com potência fiscalizada mais de 20% acima da outorgada é mantida e contada em ressalva."],
        "limitacoes": [_UF_PRINCIPAL, _MARCADORES_SIGA, "A MMGD fica fora do SIGA (ver módulo Transição)."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_potencia_por_estagio",
        "titulo": "Potência por estágio do empreendimento (SIGA)",
        "pergunta": "Quanto do parque outorgado já opera, está em obra ou ainda não começou a ser construído?",
        "definicao": "Número de usinas e soma da potência outorgada (MdaPotenciaOutorgadaKw) por fase do SIGA: Operação, Construção e Construção não iniciada (outorgado sem obra). A potência fiscalizada de usina em construção é a parcela que já opera.",
        "unidade": "MW e usinas",
        "grao_geografico": "Brasil; UF principal; tipo de geração",
        "grao_temporal": "fotografia diária do SIGA",
        "fontes": _SIGA,
        "formula": "MW(estágio) = Σ MdaPotenciaOutorgadaKw das usinas na fase ÷ 1.000",
        "regra_agregacao": "Soma por estágio; estágios são disjuntos e exaustivos (cada núcleo de CEG tem uma fase).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["estágio", "tipo de geração", "UF"],
        "regras_comparabilidade": [_OUTORGA, _MW_NAO_ENERGIA],
        "regra_cobertura": "Fases presentes no arquivo aberto do SIGA. Usina com outorga revogada ou extinta pode sair do arquivo ou continuar nele: em 30/09/2026, 196 usinas com ato de encerramento seguem na fase Operação (165 sob registro). Estágios e encerramentos não são disjuntos.",
        "politica_ausencia": "Fase não prevista é preservada como 'outro' com o rótulo original, nunca descartada.",
        "validacoes": ["Soma das usinas nos estágios igual ao número de núcleos de CEG do arquivo."],
        "limitacoes": [_OUTORGA, "O dicionário do SIGA descreve fases até a revogação, mas o arquivo aberto só traz as três fases ativas."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_encerramentos_outorga",
        "titulo": "Encerramentos de outorga (revogação e extinção)",
        "pergunta": "Quanta potência outorgada foi revogada ou extinta, e quando?",
        "definicao": "Atos da ANEEL do conjunto 'Atos de Outorgas de Geração' cujo objeto é revogação de autorização ou extinção de concessão. A potência conta uma vez por usina (núcleo do CEG) em cada ano de publicação e uma vez por usina no total, pelo maior valor conferido entre os atos da usina; a contagem de atos fica à parte. A potência de cada ato (MdaPotenciaInstaladaMW) é conferida contra a potência outorgada da mesma usina no SIGA e no RALIE histórico e contra o limite legal da CGH (5 MW).",
        "unidade": "atos, usinas e MW",
        "grao_geografico": "Brasil; tipo de geração",
        "grao_temporal": "ano de publicação do ato",
        "fontes": _ATOS + _SIGA + _RALIE,
        "formula": "MW(ano) = Σ por usina com ato no ano de max(potência conferida dos atos da usina no ano); MW(total) = Σ por usina de max(potência conferida de todos os atos da usina)",
        "regra_agregacao": "Uma vez por usina (núcleo do CEG) por ano e no total; atos contados à parte. Ato sem núcleo do CEG conta como uma unidade (não pode ser deduplicado).",
        "versao_formula": "2",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["ano", "tipo de encerramento", "tipo de geração", "situação no SIGA"],
        "regras_comparabilidade": [_PARCIAL, "Revogação de registros anteriores à outorga (DRO, DRI, DRS) não entra: não é outorga de usina.",
                                   "Usina com atos em anos diferentes aparece em cada um desses anos; o total conta a usina uma vez."],
        "regra_cobertura": "Atos publicados desde 2015 (início do conjunto). Outorga encerrada não é usina retirada: os atos de usinas que seguem na fase Operação do SIGA são contados à parte (conversão de regime ou nova outorga).",
        "politica_ausencia": "Ato sem potência conta como ato, não como 0 MW. Potência com divergência de fator 1.000 sem confirmação de qual lado está certo sai da soma e é listada.",
        "validacoes": ["Ruído de ponto flutuante da fonte arredondado a 1 kW.",
                       "Valor do ato igual ao do cadastro da usina em kW (fator 1.000): corrigido pelo cadastro quando o valor como MW excede o limite legal do tipo ou outro ato de outorga da mesma usina cita a potência do cadastro; fora da soma quando não há confirmação.",
                       "Repetição medida: usinas com mais de um ato e MW que a soma por ato repetiria."],
        "limitacoes": ["Encerramentos anteriores a 2015 não constam do conjunto.", _PARCIAL,
                       "Atos sem núcleo nem código do CEG na fonte (320 em 30/09/2026, quase todos de 2025 e 2026) não se ligam a nenhuma usina e não são deduplicados.",
                       "Usina sem cadastro no SIGA nem no RALIE (734 atos em 30/09/2026) só tem a potência do ato e o limite do tipo como controle."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_ralie_potencia_implantacao",
        "titulo": "Potência em implantação acompanhada pelo RALIE",
        "pergunta": "Quanta potência está em implantação e em que situação de obra, viabilidade e cronograma?",
        "definicao": "Soma da potência unitária (MdaPotenciaUnitaria, kW) das unidades geradoras listadas na fotografia mais recente do RALIE, e soma da potência outorgada das usinas, agrupadas pelas classificações da fiscalização (situação da obra, viabilidade, situação do cronograma, justificativa da previsão).",
        "unidade": "MW, usinas e unidades geradoras",
        "grao_geografico": "Brasil; UF principal; tipo de geração",
        "grao_temporal": "fotografia do RALIE (DatRalie)",
        "fontes": _RALIE,
        "formula": "MW em implantação = Σ MdaPotenciaUnitaria das unidades listadas ÷ 1.000",
        "regra_agregacao": "Soma simples por classificação; potência por unidade geradora preservada no CSV.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["situação da obra", "viabilidade", "situação do cronograma", "justificativa", "tipo", "UF", "leilão"],
        "regras_comparabilidade": [_OUTORGA, _MW_NAO_ENERGIA, _RALIE_UNIVERSO],
        "regra_cobertura": "Usinas e unidades da fotografia mais recente do RALIE; série mensal desde junho de 2021 pelo Parquet histórico.",
        "politica_ausencia": "Classificação vazia vira '(vazio)', nunca é atribuída a outra categoria.",
        "validacoes": ["Chave (IdeNucleoCEG, NumUgUsina) única no arquivo.", "Potência unitária não negativa."],
        "limitacoes": [_RALIE_UNIVERSO, "A classificação de viabilidade e de cronograma é da fiscalização da ANEEL, não do empreendedor."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_previsao_operacao",
        "titulo": "Potência com previsão de operação comercial por ano",
        "pergunta": "Quando a fiscalização prevê que a potência em implantação entre em operação?",
        "definicao": "Soma da potência unitária das unidades do RALIE mais recente por ano (e por mês nos 24 meses seguintes) da previsão de operação comercial da fiscalização (DatPrevisaoOpComercialSFG), por viabilidade; unidades sem previsão são contadas à parte por justificativa.",
        "unidade": "MW",
        "grao_geografico": "Brasil",
        "grao_temporal": "ano (e mês) da previsão, com data-base na fotografia do RALIE",
        "fontes": _RALIE,
        "formula": "MW(ano) = Σ MdaPotenciaUnitaria das unidades com previsão no ano ÷ 1.000",
        "regra_agregacao": "Soma simples por ano e viabilidade.",
        "versao_formula": "1",
        "natureza_fonte": "PREVISTO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["ano ou mês previsto", "viabilidade"],
        "regras_comparabilidade": [_DATA_BASE, _PREVISAO_CONVENCIONAL, "Estoque de projetos não é projeção de entrada."],
        "regra_cobertura": "Unidades da fotografia mais recente do RALIE.",
        "politica_ausencia": "Unidade sem previsão não recebe data: fica na tabela 'sem previsão' com a justificativa da fonte.",
        "validacoes": ["Previsão e data outorgada lidas como data ISO; marcadores anteriores a 1901 viram ausência."],
        "limitacoes": [_PREVISAO_CONVENCIONAL, _DATA_BASE],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_atraso_previsto",
        "titulo": "Atraso previsto em relação ao cronograma outorgado",
        "pergunta": "Quanto da potência com previsão deve entrar depois da data outorgada, e com que atraso típico?",
        "definicao": "Para cada unidade do RALIE mais recente com previsão da fiscalização e data outorgada de operação comercial: diferença em dias entre a previsão e a data outorgada; publica-se a mediana ponderada por kW e a parcela da potência com previsão depois da data outorgada.",
        "unidade": "dias e % do MW com previsão",
        "grao_geografico": "Brasil; usina (CSV da carteira)",
        "grao_temporal": "fotografia do RALIE (data-base)",
        "fontes": _RALIE,
        "numerador": "Σ kW das unidades com previsão posterior à data outorgada",
        "denominador": "Σ kW das unidades com previsão e data outorgada",
        "formula": "atraso(u) = DatPrevisaoOpComercialSFG − DatUGInicioOpComerOutorgado; mediana ponderada por MdaPotenciaUnitaria",
        "regra_agregacao": "Mediana ponderada (menor valor cuja soma acumulada de pesos alcança metade do total); percentual como razão de somas.",
        "versao_formula": "1",
        "natureza_fonte": "PREVISTO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["usina", "unidade geradora"],
        "regras_comparabilidade": [_DATA_BASE, "É atraso previsto, não atraso realizado: a previsão muda a cada fotografia.", _DATA_EM_BLOCO],
        "regra_cobertura": "Unidades com as duas datas preenchidas na fotografia mais recente; publicado com e sem as unidades em data em bloco. Unidades sem previsão ficam fora do denominador.",
        "politica_ausencia": "Unidade sem previsão ou sem data outorgada fica fora (nunca atraso zero).",
        "validacoes": ["Data-base publicada em cada linha do CSV (data_base_ralie).", "Marca de data em bloco por unidade no CSV (previsao_em_bloco)."],
        "limitacoes": [_PREVISAO_CONVENCIONAL, "A parcela depois da data outorgada não se explica só pela data em bloco: sem ela, continua acima da metade da potência com previsão (61,0% em 18/09/2026)."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_desfecho_coortes",
        "titulo": "Desfecho das usinas que passaram pelo RALIE",
        "pergunta": "Das usinas que estavam em implantação, quantas entraram em operação, tiveram a outorga encerrada ou saíram sem desfecho?",
        "definicao": "Cada usina do Parquet histórico do RALIE é classificada, nesta ordem: em implantação (consta na fotografia mais recente); operação (fase Operação no SIGA ou todas as unidades da primeira fotografia liberadas para operação comercial); outorga encerrada (ato de revogação ou extinção publicado depois da primeira aparição); sem desfecho. Agrupadas por coorte (estoque da primeira fotografia e ano de entrada no RALIE), ponderadas pela potência outorgada na primeira aparição.",
        "unidade": "% do MW outorgado na primeira fotografia e usinas",
        "grao_geografico": "Brasil; usina (CSV)",
        "grao_temporal": "coorte (primeira fotografia ou ano de entrada)",
        "fontes": _RALIE + _SIGA + _LIB + _ATOS,
        "numerador": "Σ kW outorgado na primeira fotografia das usinas da coorte com o desfecho",
        "denominador": "Σ kW outorgado na primeira fotografia de todas as usinas da coorte",
        "formula": "pct(desfecho, coorte) = 100 × Σ kW(desfecho) ÷ Σ kW(coorte)",
        "regra_agregacao": "Razão de somas de potência; desfechos disjuntos e exaustivos (somam 100%).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["coorte", "desfecho", "tipo", "UF"],
        "regras_comparabilidade": [_OUTORGA, "Coortes recentes tiveram menos tempo para entrar em operação: comparar coortes de mesma idade."],
        "regra_cobertura": "Usinas presentes em alguma fotografia do Parquet histórico desde 17/06/2021; vínculo pelo núcleo do CEG.",
        "politica_ausencia": "Usina sem operação nem ato de encerramento fica em 'sem desfecho', nunca em operação.",
        "validacoes": ["Soma dos desfechos igual ao total da coorte."],
        "limitacoes": ["Usina em operação parcial que segue no RALIE conta como em implantação.",
                       "Sem desfecho não é abandono: pode ser mudança de CEG, saída do acompanhamento, ato fora do conjunto ou ato de revogação publicado sem núcleo nem código do CEG (320 atos e 13.446,8 MW em 30/09/2026, 293 de 2026 e 27 de 2025), que não se liga a nenhuma usina do RALIE."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_confiabilidade_previsoes",
        "titulo": "Confiabilidade das previsões de operação comercial em 12 meses",
        "pergunta": "Da potência que a fiscalização previa para os 12 meses seguintes, quanto entrou no prazo?",
        "definicao": "Para cada fotografia mensal S do RALIE (última do mês), a potência das unidades com previsão em (S, S + 365 dias] e quanto dela foi liberada para operação comercial até S + 365 dias, depois disso (até a data do arquivo de liberações) ou não foi liberada. Só janelas encerradas pelo menos 15 dias antes da data do arquivo de liberações.",
        "unidade": "MW e % do MW prometido",
        "grao_geografico": "Brasil; tipo de geração",
        "grao_temporal": "fotografia mensal do RALIE (data-base) e janela de 12 meses",
        "fontes": _RALIE + _LIB,
        "numerador": "Σ kW das unidades prometidas liberadas até o fim da janela",
        "denominador": "Σ kW com previsão na janela na fotografia S",
        "formula": "pct_no_prazo(S) = 100 × Σ kW liberado até S + 365 dias ÷ Σ kW prometido em S",
        "regra_agregacao": "Razão de somas de potência por fotografia; unidades já liberadas antes de S saem do denominador e são contadas à parte.",
        "versao_formula": "1",
        "natureza_fonte": "PREVISTO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["fotografia", "tipo de geração"],
        "regras_comparabilidade": [_DATA_BASE, "Janelas recentes têm menos tempo para liberação 'depois do prazo'."],
        "regra_cobertura": "Fotografias mensais desde junho de 2021 com janela encerrada.",
        "politica_ausencia": "Unidade sem liberação no arquivo conta como não liberada até a data do arquivo.",
        "validacoes": ["Partição: no prazo + depois + não liberada = prometida em todas as fotografias.",
                       "Vínculo exato por (IdeNucleoCEG, NumUgUsina); grupos '1 a 5' do arquivo de liberações são expandidos, texto não numérico não é vinculado."],
        "limitacoes": ["Unidade renumerada entre a fotografia e a liberação aparece como não liberada."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_deslizamento_previsoes",
        "titulo": "Revisão das previsões em 12 meses",
        "pergunta": "Quanto a previsão da fiscalização para a mesma unidade muda em 12 meses, sem contar a data convencional que anda com a fotografia?",
        "definicao": "Para a mesma unidade presente nas fotografias mensais S e S + 12 meses com previsão preenchida nas duas: variação da previsão em dias (positivo = adiada), com a parcela da potência adiada, mantida e antecipada e a mediana ponderada por kW. Publicada com todas as unidades e sem as unidades cuja previsão é data em bloco em S ou em S + 12 meses, com a parcela da potência em data em bloco de cada par: o adiamento dessas unidades é o deslocamento da data convencional, não revisão de cronograma de obra.",
        "unidade": "% do MW e dias",
        "grao_geografico": "Brasil",
        "grao_temporal": "par de fotografias mensais com 12 meses de distância",
        "fontes": _RALIE,
        "numerador": "Σ kW das unidades com previsão adiada (ou mantida, ou antecipada)",
        "denominador": "Σ kW das unidades presentes nas duas fotografias com previsão",
        "formula": "desl(u) = previsão(S + 12 meses) − previsão(S); mediana ponderada por MdaPotenciaUnitaria",
        "regra_agregacao": "Razão de somas de potência; mediana ponderada.",
        "versao_formula": "1",
        "natureza_fonte": "PREVISTO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["fotografia"],
        "regras_comparabilidade": [_DATA_BASE, "Só unidades que continuam em implantação 12 meses depois: as que entraram em operação saem do par."],
        "regra_cobertura": "Pares de fotografias mensais do Parquet histórico.",
        "politica_ausencia": "Unidade sem previsão em uma das fotografias fica fora do par.",
        "validacoes": ["Parcelas adiada + mantida + antecipada somam 100% do par."],
        "limitacoes": ["Viés de sobrevivência: o par só contém unidades que não entraram em operação no intervalo.", _PREVISAO_CONVENCIONAL, _DATA_EM_BLOCO,
                       "Mesmo sem as datas em bloco, a revisão mede a mudança da previsão da fiscalização, não a causa do atraso."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_desvio_prazo_vigente",
        "titulo": "Desvio da liberação comercial em relação ao prazo outorgado vigente",
        "pergunta": "Em relação ao prazo outorgado em vigor na publicação, quando a potência foi liberada para operação comercial?",
        "definicao": "Para cada linha do arquivo detalhado de liberações para operação comercial: data de liberação realizada menos a data outorgada de início da operação comercial da unidade, como publicada no arquivo (prazo vigente, sem data-base); por ano da liberação, mediana ponderada por kW e parcelas da potência liberada depois e antes do prazo. Não é atraso: em autorizações recentes a data outorgada é um prazo limite anos à frente. O que atrasou em relação a uma previsão datada está em expansao_confiabilidade_previsoes.",
        "unidade": "dias e % do MW liberado com data outorgada",
        "grao_geografico": "Brasil; tipo de geração",
        "grao_temporal": "ano da liberação comercial (desde 2014)",
        "fontes": _LIB,
        "numerador": "Σ kW liberado depois da data outorgada vigente",
        "denominador": "Σ kW liberado com data outorgada preenchida",
        "formula": "desvio = DatLiberOpComerRealizado − DatUGInicioOpComerOutorgado; mediana ponderada por MdaPotenciaLiberadaComercial",
        "regra_agregacao": "Mediana ponderada por potência; percentuais como razão de somas.",
        "versao_formula": "2",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["ano", "tipo de geração"],
        "regras_comparabilidade": [_PARCIAL, "Antes de 2014 o arquivo detalhado não cobre toda a potência liberada (nota do dicionário da ANEEL): a série começa em 2014.",
                                   "Não é publicado como destaque nem chamado de atraso: falta data-base à data outorgada."],
        "regra_cobertura": "Usinas acompanhadas pela fiscalização (o arquivo não cobre todo o SIGA).",
        "politica_ausencia": "Linha sem data outorgada fica fora da mediana e das parcelas.",
        "validacoes": ["Potência em kW do campo MdaPotenciaLiberadaComercial (o campo unitário mistura MW e kW em linhas antigas)."],
        "limitacoes": ["A data outorgada é a vigente na publicação: cronograma alterado por ato posterior é medido contra a data alterada.",
                       "Em autorizações recentes (sobretudo solares) a data outorgada é um prazo limite: em 2026, parcial, a mediana é de 1.209 dias antes do prazo."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_leiloes_transmissao",
        "titulo": "Leilões de transmissão por ano",
        "pergunta": "Quanta rede foi contratada em leilão e a que preço?",
        "definicao": "Soma por ano do leilão da extensão de linhas (km), da transformação (MVA), do investimento previsto e da receita anual permitida (RAP) do edital e do vencedor dos lotes contratados; deságio agregado pela RAP. Lotes sem vencedor ('SEM LANCE', 'SEM INSCRITO APTO', 'NÃO LEILOADO') são contados à parte, com investimento e RAP do edital como valores ofertados e não contratados.",
        "unidade": "km, MVA, R$ milhões nominais e %",
        "grao_geografico": "Brasil; lote (CSV)",
        "grao_temporal": "ano do leilão",
        "fontes": _LEILOES,
        "numerador": "Σ RAP vencedora dos lotes com as duas RAP",
        "denominador": "Σ RAP do edital dos mesmos lotes",
        "formula": "deságio(ano) = 100 × (1 − Σ RAP vencedora ÷ Σ RAP do edital)",
        "regra_agregacao": "Somas por grandeza, cada uma no seu campo; deságio como razão de somas, nunca média de deságios.",
        "versao_formula": "2",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["ano", "leilão", "lote", "UF", "contratado ou sem vencedor"],
        "regras_comparabilidade": [_REAIS_NOMINAIS, "km, MVA e reais nunca são somados entre si."],
        "regra_cobertura": "Lotes de leilões de transmissão desde 1999 até o último leilão presente no arquivo.",
        "politica_ausencia": "Ano sem linha no arquivo é ausência, não zero. Em lote sem vencedor, o 0 de km, MVA, prazo e RAP vencedora é marcador da fonte e vira ausência. Em lote contratado, 0 km só é zero quando a descrição não cita linha (LT ou km), e 0 MVA só quando não cita MVA; nos demais casos é campo não preenchido, fora da soma e contado (29 lotes sem km e 27 sem MVA em 30/09/2026).",
        "validacoes": ["Deságio publicado (PctDesagio, fração) conferido contra 1 − RAP vencedora ÷ RAP do edital com tolerância de 0,6 ponto percentual (arredondamento da fonte em duas casas); divergências publicadas."],
        "limitacoes": [_REAIS_NOMINAIS, "Investimento é o previsto no edital, não o realizado."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_obras_transmissao",
        "titulo": "Obras de transmissão: extensão, transformação e prazos",
        "pergunta": "Quanta rede está em obra e quanto dela já passou do prazo do ato legal?",
        "definicao": "Por empreendimento do SIGET: km de circuito dos módulos de linha e MVA dos transformadores de potência com obra do tipo Instalação; prazo do ato legal (DatOprComEpd) e data efetiva (DatEfeOprComEpd). Prazo vencido = empreendimento em andamento ou planejado com data do ato legal anterior à data do arquivo.",
        "unidade": "km de circuito, MVA, empreendimentos e dias",
        "grao_geografico": "empreendimento; UF das subestações (tabela por UF)",
        "grao_temporal": "fotografia diária do SIGET; ano de energização (DatOprComObr)",
        "fontes": _SIGET,
        "formula": "km(emp) = Σ NumEtnLinTms dos módulos LT distintos com obra de Instalação; MVA(emp) = Σ MdaPotAtvMdlEqp dos transformadores de potência",
        "regra_agregacao": "Somas por grandeza e situação; módulo listado em mais de um empreendimento conta uma vez, no empreendimento da obra de Instalação mais antiga; atraso realizado por ano como mediana e percentis de (efetiva − ato legal).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["situação", "UF", "ano de energização"],
        "regras_comparabilidade": [_KM_CIRCUITO, "Reatores e capacitores (Mvar) não entram no MVA de transformação.",
                                   "Linha interestadual aparece nas duas UFs na tabela por UF: a soma das UFs supera o total nacional."],
        "regra_cobertura": "Empreendimentos com contrato de concessão cadastrados no SIGET.",
        "politica_ausencia": "Módulo sem extensão ou sem potência não soma; empreendimento sem data do ato legal não entra no prazo vencido.",
        "validacoes": ["Extensão de cada módulo entre 0 e 3.000 km (o circuito mais longo do SIN tem 2.539 km)."],
        "limitacoes": [_KM_CIRCUITO, "A previsão informada pela transmissora não está no arquivo aberto: o atraso em andamento é medido contra o ato legal.",
                       "O SIGET não tem coordenadas: a territorialização das obras é por UF das subestações; a geometria das linhas vem do WebMap da EPE (expansao_rede_epe), sem chave comum com o SIGET."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_contratos_transmissao",
        "titulo": "Contratos de concessão de transmissão assinados por ano",
        "pergunta": "Quanta rede foi contratada depois do último leilão presente no arquivo de leilões?",
        "definicao": "Contratos de concessão de transmissão por ano de assinatura (DatAsnCcd do recurso 'SIGET - Contrato Agente'), com km de circuito e MVA de transformação das obras de Instalação do objeto original de cada contrato (linhas do arquivo de obras com a mesma data de fim do contrato).",
        "unidade": "contratos, km de circuito e MVA",
        "grao_geografico": "Brasil; contrato (CSV)",
        "grao_temporal": "ano de assinatura do contrato",
        "fontes": _SIGET,
        "formula": "km(ano) = Σ NumEtnLinTms dos módulos LT de obras de Instalação dos contratos assinados no ano (objeto original); MVA(ano) = Σ MdaPotAtvMdlEqp dos transformadores",
        "regra_agregacao": "Somas por ano de assinatura, cada grandeza no seu campo.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["ano de assinatura", "contrato"],
        "regras_comparabilidade": ["Contrato não é leilão: pode vir de leilão, relicitação ou outra origem; não tem RAP de lance nem deságio.", _KM_CIRCUITO],
        "regra_cobertura": "Todos os contratos de concessão cadastrados no SIGET (413 em 29/09/2026); ano do período sem contrato é zero observado.",
        "politica_ausencia": "Contrato sem empreendimento cadastrado tem km e MVA ausentes, não zero.",
        "validacoes": ["Contratos assinados em 28/06/2024 (15) e 09/12/2024 (3) iguais ao número de lotes dos leilões 001/2024 (15) e 002/2024 (3)."],
        "limitacoes": ["Reforço incorporado depois a contrato antigo, com prazo próprio, fica fora das somas.",
                       "O SIGET não informa o leilão de origem: a ligação com o arquivo de leilões é só temporal."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_rede_epe",
        "titulo": "Linhas de transmissão existentes e planejadas por UF (WebMap da EPE)",
        "pergunta": "Onde estão as linhas de transmissão existentes e as da expansão planejada?",
        "definicao": "Comprimento das linhas das camadas 21 (Base Existente) e 10 (Expansão Planejada) do WebMap da EPE, pela geometria publicada (generalizada pelo servidor a 0,005 grau), por tensão, ano e UF; cada segmento vai para a UF do seu ponto médio na malha de UF do IBGE.",
        "unidade": "km de traçado por feição",
        "grao_geografico": "UF; linha (JSON do mapa)",
        "grao_temporal": "ano de operação (existente) ou previsto (planejada), na data de captura",
        "fontes": _EPE_REDE,
        "formula": "km(UF) = Σ comprimento geodésico dos segmentos cujo ponto médio está na UF",
        "regra_agregacao": "Soma de comprimento por UF, tensão e ano.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["camada", "UF", "tensão", "ano"],
        "regras_comparabilidade": ["km por feição (traçado; há feições com dois circuitos), não km de circuito do SIGET: as duas medidas não se somam.",
                                   "A camada planejada é planejamento da EPE, não obra contratada."],
        "regra_cobertura": "Feições das duas camadas na data de captura (contagem conferida contra a informada pelo serviço).",
        "politica_ausencia": "Ano 0 e tensão 0 da fonte viram ausência; segmento fora da malha de UF fica em km_fora_de_uf.",
        "validacoes": ["Comprimento da geometria comparado ao campo Extensao feição por feição (mediana de 0,5% de diferença); campo acima de 3.000 km tratado como fora de escala (7 feições da camada planejada, em metros)."],
        "limitacoes": ["O serviço não informa a data de atualização das camadas.", "Sem chave comum com o SIGET ou com os leilões: a ligação é territorial."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_geracao_e_rede_por_uf",
        "titulo": "Geração em implantação e rede em obra por UF",
        "pergunta": "A expansão da geração em cada UF vem acompanhada de obras de rede?",
        "definicao": "Por UF, lado a lado e sem soma entre si: MW das unidades do RALIE em implantação (e com previsão nos 24 meses seguintes), km de circuito de linhas em obra que tocam a UF e MVA de transformação em obra na UF (SIGET), e km de traçado das linhas existentes e planejadas dentro da UF (WebMap da EPE).",
        "unidade": "MW, km de circuito, MVA e empreendimentos (campos separados)",
        "grao_geografico": "UF",
        "grao_temporal": "fotografias mais recentes do RALIE e do SIGET",
        "fontes": _RALIE + _SIGET + _EPE_REDE,
        "formula": "campos independentes: Σ MdaPotenciaUnitaria (RALIE) por UF; Σ km dos módulos LT em andamento com subestação na UF; Σ MVA em andamento na UF; Σ km das linhas da EPE dentro da UF",
        "regra_agregacao": "Cada grandeza agregada separadamente; nenhuma razão entre MW e km.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["UF"],
        "regras_comparabilidade": [_MW_NAO_ENERGIA, "MW nominal não indica capacidade firme de escoamento; a comparação é temporal e territorial, não de suficiência."],
        "regra_cobertura": "UFs com geração no RALIE ou obra de transmissão em andamento.",
        "politica_ausencia": "UF sem obra em andamento aparece com 0 empreendimentos (contagem real), não com ausência.",
        "validacoes": ["Nenhum campo soma grandezas de unidades diferentes."],
        "limitacoes": ["Não mede se a rede comporta a geração: isso exige estudos de acesso e margem de escoamento do ONS e da EPE."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_pde_cenarios",
        "titulo": "Cenário oficial do PDE 2035",
        "pergunta": "Como o planejamento oficial enxerga a matriz e a rede até 2035?",
        "definicao": "Valores das figuras 3-6, 3-23, 3-25, 4-19, 4-24, 4-27 e 12-4 do caderno de dados do relatório final do PDE 2035 (EPE e MME), lidos das planilhas publicadas, com título e rótulos das colunas conferidos.",
        "unidade": "GW, MW, km, MVA, R$ bilhões e TWh (por figura)",
        "grao_geografico": "Brasil ou SIN (conforme a figura)",
        "grao_temporal": "ano (ou mês de referência) da figura, 2025 a 2035",
        "fontes": _PDE,
        "regra_agregacao": "Nenhuma: valores como publicados; totais conferidos contra os rótulos do relatório.",
        "versao_formula": "1",
        "natureza_fonte": "CENARIO",
        "natureza_transformacao": "CENARIO",
        "dimensoes": ["figura", "categoria", "ano"],
        "regras_comparabilidade": [_CENARIO, "Categorias do PDE não correspondem uma a uma às do SIGA: só as correspondências diretas ficam lado a lado, sem diferença calculada."],
        "regra_cobertura": "Edição PDE 2035 (relatório final aprovado).",
        "politica_ausencia": "Célula vazia na planilha é ausência.",
        "validacoes": ["Soma da Figura 3-25 igual aos totais rotulados no relatório (249 GW em 2025 e 359 GW em 2035) com tolerância de 0,5 GW.",
                       "Soma da Figura 3-6 em 2025 igual a cerca de 251 GW do texto com tolerância de 1 GW: conferência de valor, não de universo (o texto fala em oferta centralizada e a figura inclui a MMGD na coluna Solar)."],
        "limitacoes": [_CENARIO],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "expansao_reconciliacao_siga_agregados",
        "titulo": "Reconciliação do SIGA com os agregados oficiais",
        "pergunta": "A soma do SIGA confere com os totais que a própria ANEEL publica?",
        "definicao": "Resíduo = capacidade do SIGA − agregado oficial do último mês publicado − potência liberada para operação comercial entre o fim desse mês e a data do SIGA, por tipo de geração e por UF.",
        "unidade": "MW e % do agregado",
        "grao_geografico": "tipo de geração; UF",
        "grao_temporal": "fotografia do SIGA contra o último mês do agregado",
        "fontes": _SIGA + _AGREG + _LIB,
        "numerador": "resíduo em kW",
        "denominador": "agregado oficial em kW",
        "formula": "resíduo_pct = 100 × (SIGA − agregado − liberado no intervalo) ÷ agregado",
        "regra_agregacao": "Comparação por grupo, sem ajuste.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["tipo de geração", "UF"],
        "regras_comparabilidade": ["O agregado tem mês de referência anterior ao SIGA; revisões de potência e desativações do intervalo não são datadas por arquivo aberto."],
        "regra_cobertura": "Tipos e UFs presentes no agregado oficial mais recente.",
        "politica_ausencia": "Grupo ausente do agregado não é comparado.",
        "validacoes": ["Tolerância de 1% do agregado do grupo; fora dela o grupo é listado em fora_da_tolerancia e a evidência vira ressalva."],
        "limitacoes": ["O resíduo não identifica a usina responsável: aponta onde conferir."],
        "gold": _GOLD, "paginas": _PAG,
    },
]
