"""Métricas do módulo Geração (detalhe), painéis P021 a P024. As fórmulas rodam em
pipeline/energia/modulos/geracao_detalhe.py; a interface lê o valor calculado e esta
definição.

Quatro grandezas que não se misturam: energia gerada (MWh e MWmed, Geração por Usina e
térmica por motivo do ONS), custo declarado para despacho (CVU, R$/MWh), energia não gerada
estimada por restrição (MWh, referência do ONS menos verificada) e capacidade (MW, unidades
em operação comercial). A MMGD é energia estimada pelo ONS, publicada como categoria
própria; sua capacidade (cadastro da ANEEL) não entra em nenhum denominador daqui."""

_GOLD = "geracao_detalhe.json"
_PAG = ["/setor-eletrico/geracao"]
_USINA = ["ons_geracao_usina"]
_TERM = ["ons_geracao_termica_motivo"]
_COFF = ["ons_coff_eolica", "ons_coff_fotovoltaica"]
_CAP = ["ons_capacidade_geracao", "ons_usina_conjunto", "ons_geracao_usina"]
_A11 = ("Desde 29/04/2023 a Geração por Usina inclui a estimativa de MMGD (grupos 'Pequenas Usinas (MMGD)'); comparação "
        "que atravessa a data só no perímetro sem MMGD.")
_GRUPOS = ("Grupos de pequenas usinas Tipo III e de MMGD são previsões e estimativas do ONS (dicionário da Geração por Usina, "
           "versão 1.2); a parcela de cada natureza é publicada à parte.")
_AUSENCIA = ("Valor vazio na fonte é ausência: não entra na soma nem nas horas daquela série; dia sem as 24 horas em todos os "
             "subsistemas fica fora das janelas; usina com todas as horas vazias no mês é contada como lacuna, nunca como zero.")
_UNIVERSO = ("Mudanças de universo na fonte (rótulos que aparecem, deixam de ter valor ou somem, usinas que passam a vir sem valor "
             "ou deixam de constar do arquivo, sequências longas de zero exato) são detectadas por regra publicada e listadas em "
             "'quebras' e em matriz.universo; cada janela, mês e ano traz em ressalvas_universo as categorias afetadas.")
# A geração publicada soma três naturezas: medição (usinas e conjuntos com relacionamento
# com o ONS), previsão do ONS (grupos Tipo III) e estimativa do ONS (MMGD). A fração de cada
# uma sai no próprio indicador (natureza_pct de cada janela e ano, natureza_mensal_sin).
_NATUREZA_MISTA = ("MISTO: OBSERVADO (geração verificada), PREVISTO (grupos de pequenas usinas Tipo III) e ESTIMADO "
                   "(MMGD estimada pelo ONS); fração de cada natureza publicada em natureza_pct")
_OUTROS = ("A categoria 'outras térmicas' segue o rótulo 'Resíduos Industriais' do ONS, que reúne gases de siderurgia (CEG UTE.CM) e "
           "licor negro de celulose (CEG UTE.FL, biomassa florestal na ANEEL): a decomposição por código do CEG sai em matriz.outros_por_ceg.")

METRICAS = [
    {
        "id": "geracao_categoria_mwmed",
        "titulo": "Geração por fonte e combustível",
        "pergunta": "Quanta energia cada fonte e cada combustível gerou no período?",
        "definicao": ("Soma da geração horária das usinas, conjuntos e grupos da Geração por Usina do ONS em cada categoria "
                      "(hidráulica, eólica, solar centralizada, solar MMGD, nuclear, gás natural, carvão, óleo, biomassa, outras "
                      "térmicas e térmicas sem combustível identificado), dividida pelas horas do período."),
        "unidade": "MWmed (MWh no CSV)",
        "grao_geografico": "SIN e subsistemas (SE, S, NE, N)",
        "grao_temporal": "hora (SIN), dia, mês, ano civil e janelas de 1, 7, 30 e 365 dias",
        "fontes": _USINA,
        "numerador": "Σ val_geracao × 1 h das linhas da categoria (MWh)",
        "denominador": "horas dos dias completos do período",
        "formula": "MWmed = Σ MWh ÷ horas",
        "regra_agregacao": "Soma de energia; SIN = soma dos quatro subsistemas; MWmed nunca é média de médias diárias.",
        "versao_formula": "2",
        "natureza_fonte": _NATUREZA_MISTA,
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["categoria", "subsistema", "natureza (verificada, grupo Tipo III, grupo MMGD)", "rótulo da fonte"],
        "regras_comparabilidade": [_A11, "Categoria pelo tipo da usina, como no Balanço de Energia: conjunto híbrido rotulado 'Fotovoltaica' dentro de usina eólica conta como eólica."],
        "regra_cobertura": "Arquivos de 2021 em diante (o anual de 2021 e os mensais seguintes); só dias com 24 instantes em todos os subsistemas.",
        "politica_ausencia": _AUSENCIA,
        "validacoes": ["Energia não negativa por categoria.", "Dia de referência não posterior à data de processamento.",
                       "Categoria sem nenhuma linha no período é nula, não zero (MMGD antes de 29/04/2023, grupos Tipo III térmicos antes de 03/2021).",
                       "Reconciliação diária com o Balanço de Energia nos Subsistemas por fonte, subsistema e dia (tolerância de 1 MWh)."],
        "limitacoes": [_GRUPOS, _UNIVERSO, _OUTROS,
                       "Grupos térmicos Tipo III ('Outras Multi-Combustível') não têm combustível na fonte: categoria própria, explícita."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_participacao",
        "titulo": "Participação na geração (matriz efetiva)",
        "pergunta": "Que fração da energia gerada veio de cada fonte e combustível?",
        "definicao": "Energia da categoria dividida pela energia de todas as categorias no mesmo período e região, em dois perímetros: com MMGD (igual ao total do Balanço) e sem MMGD.",
        "unidade": "% da geração",
        "grao_geografico": "SIN e subsistemas",
        "grao_temporal": "dia, janelas de 7, 30 e 365 dias, mês e ano civil",
        "fontes": _USINA,
        "numerador": "energia da categoria no período (MWh)",
        "denominador": "energia de todas as categorias no período (MWh), com ou sem a solar MMGD",
        "regra_agregacao": "Razão de somas de energia do mesmo perímetro; nunca média de participações diárias.",
        "versao_formula": "2",
        "natureza_fonte": _NATUREZA_MISTA,
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["categoria", "subsistema", "perímetro (com ou sem MMGD)"],
        "regras_comparabilidade": [_A11, "Participação de geração não se compara com participação de capacidade instalada."],
        "regra_cobertura": "Dias completos do período; o número de dias usados acompanha cada janela.",
        "politica_ausencia": _AUSENCIA,
        "validacoes": ["Participações somam 100% (tolerância 0,05 ponto percentual) em todas as janelas e regiões; falha derruba a publicação.",
                       "Categoria ausente no período tem participação nula, fora do total.",
                       "Ressalva de universo junto da participação: salto de universo dentro do período ou universo reduzido (até 75% do maior número de identificadores com valor dos 12 meses anteriores)."],
        "limitacoes": [_GRUPOS, _UNIVERSO, _OUTROS],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_reconciliacao_balanco",
        "titulo": "Reconciliação com o Balanço de Energia",
        "pergunta": "A soma das usinas fecha com o balanço do ONS?",
        "definicao": ("Diferença entre a geração do Balanço de Energia nos Subsistemas e a soma das usinas da Geração por Usina, "
                      "por fonte do balanço (hidráulica, térmica com nuclear, eólica e solar), subsistema e dia; a térmica do Norte "
                      "é ajustada pelas usinas de Roraima nos dias em que o balanço as exclui."),
        "unidade": "MWh e dias conciliados",
        "grao_geografico": "subsistema e SIN",
        "grao_temporal": "dia e mês",
        "fontes": _USINA + ["balanco_energia_subsistema_ho"],
        "formula": "diferença = balanço − Σ usinas; conciliado quando |diferença| ≤ 1 MWh",
        "regra_agregacao": "Soma das diferenças diárias; contagem de dias conciliados no subsistema e no SIN.",
        "versao_formula": "1",
        "natureza_fonte": "MISTO: OBSERVADO, PREVISTO e ESTIMADO nos dois lados (o Balanço e a soma das usinas incluem os grupos Tipo III e a MMGD)",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["fonte do balanço", "subsistema", "mês"],
        "regras_comparabilidade": ["Diferença de alocação entre subsistemas some no SIN; por isso a conciliação é publicada nos dois níveis."],
        "regra_cobertura": "Dias com 24 horas no balanço e dia completo na Geração por Usina.",
        "politica_ausencia": "Dia sem as 24 horas no balanço não entra na comparação.",
        "validacoes": ["Tolerância de 1 MWh por subsistema, fonte e dia, justificada pelo arredondamento dos dois arquivos."],
        "limitacoes": ["O balanço excluiu as térmicas de Roraima até 14/07/2025 (detectado no dado, não declarado na documentação).",
                       "Há dias isolados com grandes divergências (ex.: eólica do Nordeste em 16/01/2026); a plataforma publica, não corrige."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_termica_motivo",
        "titulo": "Geração térmica por motivo de despacho",
        "pergunta": "Por que as térmicas foram acionadas?",
        "definicao": ("Geração verificada das térmicas e nucleares despachadas pelo ONS repartida pelos motivos do próprio ONS, "
                      "sem dupla contagem: ordem de mérito acima da inflexibilidade, inflexibilidade (pura e embutida no mérito), "
                      "razão elétrica, garantia energética, GFOM, reposição de perdas, exportação, reserva de potência, "
                      "substituição e unit commitment; o resto é 'não classificado', com sinal."),
        "unidade": "MWmed e % da geração térmica verificada",
        "grao_geografico": "SIN, subsistema e usina (CEG)",
        "grao_temporal": "hora agregada por dia e mês; 12 meses completos",
        "fontes": _TERM,
        "numerador": "geração verificada pelo motivo (MWh)",
        "denominador": "geração verificada total, val_verifgeracao (MWh)",
        "regra_agregacao": "Soma de energia por motivo; parcela = soma do motivo ÷ soma do total.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["motivo", "combustível (dimensão separada)", "usina", "subsistema"],
        "regras_comparabilidade": ["Combustível e motivo são dimensões separadas: o combustível vem da própria fonte (2026) ou do mesmo CEG em outros conjuntos do ONS, com todos os CEGs que cada usina já publicou.",
                                   "Usina = identidade que liga CEGs com o mesmo número de empreendimento e elo publicado pelo ONS (mesmo código nos modelos ou mesmo identificador na Geração por Usina): a troca de CEG da fonte não quebra a série nem duplica a usina no ranking.",
                                   "O motivo é a classificação do ONS, nunca inferida do PLD ou do CMO.",
                                   "Unit commitment só existe a partir de janeiro de 2020 (DESSEM); antes é 'não se aplica'."],
        "regra_cobertura": "Arquivos anuais de 2013 a 2021 e mensais de 2022 em diante; os anuais de 2022 e 2023 duplicam os mensais e ficam de fora.",
        "politica_ausencia": "Coluna que não existia no período = não se aplica (nulo), não zero.",
        "validacoes": ["Partição fecha com a geração verificada: 'não classificado' publicado; até 0,5% do total = aprovado.",
                       "Mesmas usinas (CEG) somadas na Geração por Usina: diferença mensal até 1%."],
        "limitacoes": ["Valores negativos em anos antigos da fonte, que o dicionário não admite, mantidos e contados.",
                       "Usinas sem combustível identificado ficam na categoria 'não mapeada' (lista e energia em mapa_combustivel)."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_cvu",
        "titulo": "Custo variável unitário (CVU) das térmicas",
        "pergunta": "Quanto custa, declaradamente, despachar cada térmica nesta semana?",
        "definicao": "CVU considerado no Programa Mensal da Operação para a semana operativa (sábado a sexta), por usina, como o ONS publica.",
        "unidade": "R$/MWh",
        "grao_geografico": "usina (código do ONS nos modelos)",
        "grao_temporal": "semana operativa (vigência de sábado a sexta) e revisão do PMO",
        "fontes": ["ons_cvu_termica"],
        "regra_agregacao": "Distribuição por combustível (mínimo, quartis, máximo) na semana vigente; mediana mensal de usinas e semanas; no ranking térmico, CVU por parcela (código do ONS).",
        "versao_formula": "2",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["usina", "combustível", "semana operativa"],
        "regras_comparabilidade": ["CVU é custo declarado para despacho, não preço do combustível nem custo realizado."],
        "regra_cobertura": "Semanas operativas de 2005 em diante; na gold, a semana vigente na data de processamento.",
        "politica_ausencia": "Usina sem CVU na semana não aparece; linha repetida idêntica conta uma vez; conflito é registrado.",
        "validacoes": ["Conflito de CVU para a mesma usina e semana derruba a escolha (contado, nenhuma versão escolhida em silêncio).",
                       "Código do ONS ligado a mais de uma usina fica sem par e é contado (controle publicado)."],
        "limitacoes": ["O par com a usina da térmica por motivo é pelo código do ONS nos modelos, com todos os códigos (parcelas) que cada usina já teve; usina com várias parcelas tem um CVU por parcela, e o ranking publica cada um.",
                       "Usinas do CVU sem nenhum código na térmica por motivo ficam sem combustível identificado."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_restricao_energia",
        "titulo": "Energia não gerada por restrição de operação (constrained-off)",
        "pergunta": "Quanta geração eólica e solar foi cortada por ordem do ONS?",
        "definicao": ("Soma, nas meias horas em que o ONS limitou a usina ou conjunto, de max(geração de referência − geração "
                      "verificada, 0) × 0,5 h; é a Geração Não Realizada Apurada (GNRa) do dicionário, conferida contra o campo "
                      "publicado. Por razão oficial: REL (elétrica, indisponibilidade externa), CNF (confiabilidade), ENE "
                      "(energética), PAR (parecer de acesso), e origem LOC ou SIS."),
        "unidade": "MWh (GWh na interface)",
        "grao_geografico": "SIN, subsistema e usina ou conjunto (id do ONS)",
        "grao_temporal": "meia hora agregada por dia e mês; 12 meses completos",
        "fontes": _COFF,
        "formula": "Σ max(val_geracaoreferencia − val_geracao, 0) × 0,5 h, só onde val_geracaolimitada não é nula",
        "regra_agregacao": "Soma de energia; razão e origem como o ONS classifica cada meia hora.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["fonte (eólica, solar)", "razão", "origem", "subsistema", "usina"],
        "regras_comparabilidade": ["Restrição não é indisponibilidade nem falta de vento ou sol: meia hora sem limitação do ONS não entra.",
                                   "A série fotovoltaica começa em abril de 2024; a eólica, em outubro de 2021."],
        "regra_cobertura": "Usinas e conjuntos Tipo I, II-B e II-C presentes nos arquivos do ONS.",
        "politica_ausencia": "Meia hora limitada sem geração de referência fica fora da soma e é contada no controle.",
        "validacoes": ["Regra igual ao campo GNRa publicado (tolerância 0,001 MWmed por meia hora).",
                       "Razão dentro do domínio do dicionário (REL, CNF, ENE, PAR)."],
        "limitacoes": ["A geração de referência é estimativa do ONS (RO-AO.BR.13): a energia não gerada é estimada, não medida.",
                       "O ONS republica meses antigos; revisões entre capturas são detectadas."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_restricao_taxa",
        "titulo": "Taxa de restrição",
        "pergunta": "Que fração da geração possível foi cortada?",
        "definicao": "Energia não gerada estimada dividida pela soma da geração verificada e da energia não gerada, no mesmo universo de usinas e período.",
        "unidade": "%",
        "grao_geografico": "SIN, subsistema e usina",
        "grao_temporal": "mês e 12 meses completos",
        "fontes": _COFF,
        "numerador": "energia não gerada estimada (MWh)",
        "denominador": "geração verificada de todas as meias horas do universo + energia não gerada (MWh)",
        "regra_agregacao": "Razão de somas; nunca média de taxas mensais ou de usinas.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["fonte", "subsistema", "usina", "mês"],
        "regras_comparabilidade": ["O denominador é a geração possível estimada só nas meias horas restringidas mais a verificada; não é a capacidade instalada."],
        "regra_cobertura": "Universo de usinas e conjuntos dos arquivos de restrição (Tipo I, II-B e II-C).",
        "politica_ausencia": "Usina sem geração e sem corte no período não entra na lista; taxa sem denominador é nula.",
        "validacoes": ["Numerador e denominador do mesmo universo e período."],
        "limitacoes": ["Usinas Tipo III e MMGD não fazem parte do registro de restrições."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_restricao_potencia_max",
        "titulo": "Maior corte simultâneo",
        "pergunta": "Qual foi a maior potência cortada ao mesmo tempo?",
        "definicao": "Maior soma, numa mesma meia hora, dos cortes (referência − verificada) das usinas limitadas; potência média da meia hora, não energia.",
        "unidade": "MW",
        "grao_geografico": "SIN e subsistema",
        "grao_temporal": "meia hora (máximo diário e mensal)",
        "fontes": _COFF,
        "formula": "max sobre meias horas de Σ_usinas max(referência − verificada, 0)",
        "regra_agregacao": "Máximo; nunca somado entre dias.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["fonte", "subsistema", "dia", "mês"],
        "regras_comparabilidade": ["Potência (MW) não se compara com energia (MWh)."],
        "regra_cobertura": "Mesmo universo da energia não gerada.",
        "politica_ausencia": "Dia sem limitação tem corte zero (há linhas sem limitação), não ausência.",
        "validacoes": ["Corte simultâneo não excede a soma das referências das mesmas linhas na meia hora: contado na importação em todas as meias horas com corte, por subsistema, e conferido no silver no maior corte de cada dia (ressalva se violar)."],
        "limitacoes": ["Depende da referência estimada pelo ONS."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_potencia_operacional",
        "titulo": "Potência em operação comercial",
        "pergunta": "Quanta capacidade despachada pelo ONS estava em operação em cada mês?",
        "definicao": ("Soma da potência nominal das unidades geradoras (conjunto Capacidade Instalada de Geração do ONS) ponderada "
                      "pelos dias do mês entre a entrada em operação comercial e a desativação."),
        "unidade": "MW (média do mês)",
        "grao_geografico": "SIN, por categoria",
        "grao_temporal": "mês; retrato na data da captura",
        "fontes": ["ons_capacidade_geracao"],
        "formula": "Σ_unidades potência × dias em operação no mês ÷ dias do mês",
        "regra_agregacao": "Soma de potências de unidades distintas.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["categoria", "mês"],
        "regras_comparabilidade": ["Capacidade do ONS (usinas despachadas) não é a do SIGA da ANEEL nem inclui a MMGD: universos diferentes, nunca somados.",
                                   "A unidade entra na categoria da usina na Geração por Usina (mesmo CEG), a mesma do fator de capacidade: a turbina a vapor de ciclo combinado ('Resíduo Ciclo Combinado') de uma usina a gás é gás."],
        "regra_cobertura": "Unidades presentes no retrato do dia; o conjunto não tem histórico.",
        "politica_ausencia": "Unidade sem data de entrada em operação comercial fica fora.",
        "validacoes": ["Potência positiva em todas as unidades (o dicionário não admite zero): resultado tirado da contagem gravada na importação.",
                       "Capacidade-hora média do fator de capacidade não passa da potência média em operação da categoria (controle crítico)."],
        "limitacoes": ["Usinas que saíram do despacho centralizado não aparecem no retrato; potência atual aplicada a todo o histórico da unidade (repotenciações não reconstituídas)."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_fator_capacidade",
        "titulo": "Fator de capacidade",
        "pergunta": "Quanto as usinas produzem em relação ao que poderiam produzir a plena potência?",
        "definicao": ("Geração dividida pela potência em operação comercial média do mês vezes as horas com dado, só em grupos de "
                      "pareamento com unidades no conjunto de capacidade (mesmo CEG, CEG sem versão ou usinas do conjunto com "
                      "relacionamento vigente)."),
        "unidade": "%",
        "grao_geografico": "SIN por categoria; grupo de usinas",
        "grao_temporal": "mês e 12 meses completos",
        "fontes": _CAP,
        "numerador": "geração dos grupos pareados (MWh)",
        "denominador": "Σ potência em operação comercial média do mês × horas com dado (MWh)",
        "regra_agregacao": "Razão de somas por categoria; grupos com o mesmo CEG somam a geração e usam a potência uma vez.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["categoria", "mês", "grupo de usinas"],
        "regras_comparabilidade": ["Nunca a capacidade final para todo o histórico: cada mês usa as unidades em operação naquele mês.",
                                   "Eólica e solar conferidas contra o fator de capacidade publicado pelo ONS (tolerância de 2 pontos percentuais)."],
        "regra_cobertura": "Usinas e conjuntos despachados (natureza verificada); grupos Tipo III e MMGD ficam fora do numerador e do denominador.",
        "politica_ausencia": "Grupo sem unidade pareada fica fora; a cobertura (energia pareada ÷ energia da categoria) é publicada.",
        "validacoes": ["Mês de usina acima de 100% contado e listado, não descartado (unidade em teste, potência desatualizada).",
                       "Capacidade-hora média do denominador não passa da potência média em operação da categoria (mesma classificação nos dois)."],
        "limitacoes": ["Geração em teste antes da operação comercial infla o fator do mês de entrada.",
                       "Nucleares passam de 100% em vários meses: a potência nominal do ato da ANEEL é menor que a geração bruta verificada."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_a11_diferenca_solar",
        "titulo": "Conferência da solar do Balanço com a soma das usinas (achado A11)",
        "pergunta": "A quebra da solar em 29/04/2023 é a entrada da MMGD?",
        "definicao": "Diferença diária entre a solar do Balanço de Energia e a soma das usinas FOTOVOLTAICA da Geração por Usina, com e sem o grupo 'Pequenas Usinas (MMGD)'.",
        "unidade": "MWh por dia e MWmed",
        "grao_geografico": "SIN",
        "grao_temporal": "dia",
        "fontes": _USINA + ["balanco_energia_subsistema_ho"],
        "formula": "diferença = solar do balanço − Σ usinas fotovoltaicas (com MMGD)",
        "regra_agregacao": "Soma diária dos quatro subsistemas.",
        "versao_formula": "1",
        "natureza_fonte": "MISTO: OBSERVADO (usinas) e ESTIMADO (MMGD do ONS, a partir de 29/04/2023)",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["dia"],
        "regras_comparabilidade": ["A MMGD da Geração por Usina e a da API de carga verificada são estimativas de processos diferentes do ONS."],
        "regra_cobertura": "Dias completos desde 01/01/2021; janela de 22/04/2023 a 06/05/2023 para a confirmação.",
        "politica_ausencia": "Antes de 29/04/2023 não há linha do grupo MMGD: ausência, publicada como nula.",
        "validacoes": ["Todos os dias da janela da quebra dentro de 1 MWh no SIN."],
        "limitacoes": ["Fora da janela há divergências entre balanço e usinas (publicadas na reconciliação)."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "geracao_capacidade_ons_aneel",
        "titulo": "Potência do ONS e capacidade da ANEEL na mesma data",
        "pergunta": "Quanto da capacidade em operação registrada pela ANEEL está no retrato das usinas despachadas pelo ONS?",
        "definicao": ("Capacidade em operação por tipo de geração na série histórica da ANEEL (base do SIGA) e potência das unidades "
                      "do retrato da Capacidade Instalada do ONS em operação comercial no último dia do mesmo mês, por grupo "
                      "(hidráulica, eólica, solar centralizada, nuclear, térmicas); a parcela é ONS ÷ ANEEL."),
        "unidade": "MW e %",
        "grao_geografico": "Brasil (ANEEL) e SIN (ONS), por grupo de fonte",
        "grao_temporal": "datas de referência da série da ANEEL (trimestral desde 2021)",
        "fontes": [_CAP[0], "aneel_empreendimentos_operacao"],
        "numerador": "potência do ONS em operação comercial no último dia do mês (MW)",
        "denominador": "capacidade em operação da ANEEL na mesma data de referência (MW)",
        "regra_agregacao": "Soma de potências de unidades (ONS) e de tipos de geração (ANEEL) no grupo; razão na mesma data.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["grupo de fonte", "data de referência"],
        "regras_comparabilidade": ["Universos diferentes: a ANEEL inclui usinas não despachadas pelo ONS, sistemas isolados e autoprodução; nada é somado.",
                                   "Não é fator de capacidade: compara potência com potência na mesma data."],
        "regra_cobertura": "Datas da série da ANEEL a partir do primeiro mês da Geração por Usina integrada.",
        "politica_ausencia": "Data sem valor de um tipo na ANEEL fica nula no grupo.",
        "validacoes": ["Datas de referência só as publicadas pela ANEEL; nenhum valor interpolado entre elas."],
        "limitacoes": ["O retrato do ONS não tem histórico: a potência de cada data é reconstituída pelas datas de entrada e desativação das unidades atuais.",
                       "A série da ANEEL não separa combustível: as térmicas são comparadas juntas."],
        "gold": _GOLD, "paginas": _PAG,
    },
]
