"""Métricas do módulo Inclusão energética (painéis P059 a P062).

Cada medida publicada em public/energia/gold/inclusao.json tem aqui a definição única.
A fórmula roda em pipeline/energia/modulos/inclusao.py; a interface só lê.
Unidades nunca se misturam: unidade consumidora (UC), fatura, família, domicílio,
pessoa e real (R$) são contagens diferentes e cada métrica declara a sua.
"""

GOLD = "inclusao.json"
PAGINAS = ["/setor-eletrico/inclusao-energetica"]
AUSENCIA = "Ausência na fonte fica sem valor (nunca zero); o motivo aparece na evidência."

METRICAS = [
    {
        "id": "inclusao.tsee_uc",
        "titulo": "Unidades consumidoras com Tarifa Social",
        "pergunta": "Quantas unidades consumidoras recebem o desconto da Tarifa Social?",
        "definicao": "Soma das UC das cinco modalidades da subclasse residencial baixa renda (baixa renda, BPC, indígena, quilombola e multifamiliar) informadas pelas distribuidoras no SCS, nas cinco faixas de consumo, no despacho vigente.",
        "unidade": "unidades consumidoras",
        "grao_geografico": "distribuidora; Brasil (soma)",
        "grao_temporal": "mês de competência",
        "fontes": ["aneel_scs"],
        "numerador": "Σ NumConsBaixaRenda + NumConsIndigena + NumConsQuilombola + NumConsBPC + NumConsMultifamiliar",
        "regra_agregacao": "soma entre faixas e distribuidoras; série nacional só em meses completos (pelo menos 90 informantes e nenhuma distribuidora esperada faltando: lacuna entre dois informes ou ausência nos 3 últimos meses do arquivo; incorporação não conta como falta)",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["distribuidora (CNPJ)", "modalidade", "faixa de consumo", "mês"],
        "regras_comparabilidade": ["UC não é família nem pessoa", "meses incompletos não entram em comparação nacional",
                                   "concessão automática a partir de jan/2022 e nova regra de desconto a partir de 05/07/2025 mudam o regime"],
        "regra_cobertura": "distribuidoras que informaram o SCS no mês; o último mês do arquivo costuma estar incompleto",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["exatamente 5 faixas por despacho", "despacho vigente por competência",
                       "conferência com os Beneficiários da CDE no mês de conferência, ±2% por distribuidora",
                       "conferência com a série antiga da ANEEL nos trimestres comuns (2014 a 2019)"],
        "limitacoes": ["não distingue famílias com mais de uma UC (a regra permite uma só)", "sujeito a retificação pela distribuidora"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.tsee_participacao_residencial",
        "titulo": "Participação da Tarifa Social nas UC residenciais",
        "pergunta": "Que parte das unidades consumidoras residenciais tem a Tarifa Social?",
        "definicao": "UC com Tarifa Social divididas pelas UC da classe residencial das mesmas distribuidoras e mês.",
        "unidade": "%",
        "grao_geografico": "distribuidora; Brasil",
        "grao_temporal": "mês",
        "fontes": ["aneel_scs"],
        "numerador": "Σ UC com Tarifa Social das distribuidoras com total residencial consistente",
        "denominador": "Σ QtdConsResTotal das mesmas distribuidoras",
        "formula": "100 × Σ numerador ÷ Σ denominador",
        "regra_agregacao": "razão de somas; distribuidora com total residencial inconsistente sai das duas somas no mês",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês"],
        "regras_comparabilidade": ["nunca média simples das participações das distribuidoras", "não é cobertura do público elegível"],
        "regra_cobertura": ("total residencial inconsistente: ausente, zero, menor que as UC com Tarifa Social ou a mais de 25% da mediana de ±3 meses; "
                            "quando a distribuidora incorporou outra, a mediana só compara meses do mesmo lado da incorporação (incorporação detectada "
                            "no SCS: saída definitiva de uma distribuidora e salto da sucessora a até 25% do total residencial da incorporada)"),
        "politica_ausencia": AUSENCIA,
        "validacoes": ["caso real: ELETROPAULO dez/2021 (total residencial cai de 7,44 milhões para 2,55 milhões e volta) marcado como inconsistente",
                       "caso real de incorporação: RGE SUL fev/2020 (2.454.222 UC residenciais depois de incorporar a RGE, 1.279.372) fica na participação; "
                       "a mesma RGE SUL em jun/2020 (991.302, queda isolada) continua inconsistente"],
        "limitacoes": ["o total residencial é informado pela própria distribuidora no SCS"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.tsee_dmr",
        "titulo": "Diferença Mensal de Receita da Tarifa Social",
        "pergunta": "Quanto custa o desconto da Tarifa Social por mês?",
        "definicao": "Diferença Mensal de Receita (VlrDMR) aprovada pela ANEEL no despacho vigente: a receita que a distribuidora deixa de cobrar das UC com Tarifa Social e recebe da CDE.",
        "unidade": "R$ correntes",
        "grao_geografico": "distribuidora; Brasil",
        "grao_temporal": "mês de competência",
        "fontes": ["aneel_scs"],
        "numerador": "Σ VlrDMR (um valor por distribuidora e mês)",
        "regra_agregacao": "soma entre distribuidoras; o valor, repetido nas cinco linhas de faixa do arquivo, é lido uma vez",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["distribuidora", "mês"],
        "regras_comparabilidade": ["valores nominais", "não coincide com o valor anual da CDE (competência versus ano de referência do orçamento)"],
        "regra_cobertura": "distribuidoras com despacho no mês",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["DMR idêntica nas cinco faixas de cada despacho", "soma por faixa nunca usada"],
        "limitacoes": ["a DMR não é o desconto por família"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.tsee_dmr_por_uc",
        "titulo": "DMR por unidade consumidora",
        "pergunta": "Qual é, em média, o valor do desconto por UC beneficiada no mês?",
        "definicao": "DMR da distribuidora (ou do Brasil) dividida pelas UC com Tarifa Social no mesmo mês.",
        "unidade": "R$ por UC no mês",
        "grao_geografico": "distribuidora; Brasil",
        "grao_temporal": "mês",
        "fontes": ["aneel_scs"],
        "numerador": "Σ VlrDMR",
        "denominador": "Σ UC com Tarifa Social",
        "formula": "Σ DMR ÷ Σ UC",
        "regra_agregacao": "razão de somas",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês"],
        "regras_comparabilidade": ["depende da tarifa de cada distribuidora e da regra de desconto vigente"],
        "regra_cobertura": "UC > 0 e DMR informada",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["mesma competência e mesmo despacho no numerador e no denominador"],
        "limitacoes": ["média por UC, não valor de cada fatura"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.tsee_kwh_por_uc",
        "titulo": "Consumo faturado médio das UC com Tarifa Social",
        "pergunta": "Quanto consome, em média, uma UC com Tarifa Social?",
        "definicao": "Energia faturada das UC com Tarifa Social (soma das modalidades) dividida pelo número dessas UC.",
        "unidade": "kWh por UC no mês",
        "grao_geografico": "distribuidora; Brasil",
        "grao_temporal": "mês",
        "fontes": ["aneel_scs"],
        "numerador": "1.000 × Σ MdaMWh das modalidades",
        "denominador": "Σ UC com Tarifa Social",
        "formula": "1000 × Σ MWh ÷ Σ UC",
        "regra_agregacao": "razão de somas",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês"],
        "regras_comparabilidade": ["MWh convertido em kWh por 1.000"],
        "regra_cobertura": "UC > 0",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["unidade conferida no dicionário do SCS (MdaMWh em MWh)"],
        "limitacoes": ["energia faturada, não consumo medido de cada domicílio"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.cde_faturas_tsee",
        "titulo": "Faturas com desconto da Tarifa Social (Beneficiários da CDE)",
        "pergunta": "Onde, por município e UF, estão as unidades que recebem o desconto?",
        "definicao": "Número de linhas de faturamento (tipo 1) com subsídio baixa renda nas subclasses 3.2 a 3.6 do arquivo mensal de Beneficiários da CDE; cada linha é a fatura de uma UC no mês.",
        "unidade": "faturas de faturamento com desconto no mês (em regra uma por UC; a conferência com o SCS mede o desvio)",
        "grao_geografico": "município (código IBGE), UF, distribuidora",
        "grao_temporal": "mês do arquivo processado",
        "fontes": ["aneel_cde_beneficiarios"],
        "numerador": "contagem de linhas com DscTipoSubsidio = SubsBaixaRenda, IdcTipoFaturamento = 1, IdcSubclasse em 3.2 a 3.6",
        "regra_agregacao": "contagem por município; UF = soma dos municípios; linhas com código de município em formato inválido ou inexistente na lista de municípios do IBGE (Cadastro Único) só no total nacional",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["município", "UF", "distribuidora", "subclasse"],
        "regras_comparabilidade": ["mês do mapa: o mais recente com cobertura ≥ 99,5% das UC do SCS", "fatura não é família",
                                   "série mensal só com meses cujo original está no bronze; mês sondado abaixo da cobertura mínima publica só a cobertura"],
        "regra_cobertura": "cobertura = UC do SCS (mês de conferência) das distribuidoras presentes no arquivo ÷ UC do SCS de todas",
        "politica_ausencia": "Município sem fatura no arquivo aparece sem valor (ausente), não como zero.",
        "validacoes": ["nenhum campo pessoal lido ou publicado", "esquema do arquivo conferido a cada leitura",
                       "conferência com o SCS por distribuidora"],
        "limitacoes": ["base sujeita a retificação a qualquer momento, segundo a ANEEL"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.cde_desconto_tsee",
        "titulo": "Desconto da Tarifa Social nas faturas (Beneficiários da CDE)",
        "pergunta": "Quanto de desconto chegou às faturas em cada UF?",
        "definicao": "Soma de VlrSubsidio das faturas de faturamento (tipo 1) com subsídio baixa renda nas subclasses 3.2 a 3.6.",
        "unidade": "R$ correntes no mês",
        "grao_geografico": "município, UF, distribuidora",
        "grao_temporal": "mês do arquivo",
        "fontes": ["aneel_cde_beneficiarios"],
        "numerador": "Σ VlrSubsidio",
        "regra_agregacao": "soma; cancelamentos e refaturamentos (tipos 2 a 4) só no desconto líquido do mês (inclusao.cde_desconto_liquido)",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["município", "UF", "distribuidora"],
        "regras_comparabilidade": ["valores nominais", "regra de desconto mudou em 05/07/2025"],
        "regra_cobertura": "mesma do número de faturas",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["comparação com a DMR do SCS por distribuidora no mês de conferência"],
        "limitacoes": ["o desconto médio por fatura depende da tarifa local e do consumo"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.cde_desconto_liquido",
        "titulo": "Desconto líquido da Tarifa Social no mês (Beneficiários da CDE)",
        "pergunta": "Quanto de desconto ficou nas faturas da Tarifa Social depois de cancelamentos e refaturamentos?",
        "definicao": "Soma de VlrSubsidio das linhas SubsBaixaRenda das subclasses 3.2 a 3.6 nos tipos de faturamento 1 a 4 (faturamento, cancelamento e os dois refaturamentos), com o sinal da fonte. Linhas SubsBaixaRenda de outras subclasses (iluminação pública, industrial, comercial) ficam fora e são publicadas à parte como diagnóstico (desconto_fora_das_subclasses_reais).",
        "unidade": "R$ correntes no mês",
        "grao_geografico": "Brasil",
        "grao_temporal": "mês do arquivo",
        "fontes": ["aneel_cde_beneficiarios"],
        "numerador": "Σ VlrSubsidio (subclasses 3.2 a 3.6; tipos 1 a 4)",
        "regra_agregacao": "soma nacional; o diagnóstico de outras subclasses soma os tipos 1 a 4 das demais subclasses com SubsBaixaRenda",
        "versao_formula": "1.1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["mês"],
        "regras_comparabilidade": ["valores nominais", "regra de desconto mudou em 05/07/2025",
                                   "versão 1.0 somava também as outras subclasses (R$ -26,1 milhões em mar/2026) e foi corrigida"],
        "regra_cobertura": "meses com o original no bronze",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["mar/2026: R$ 786.968.415,45 em releitura independente do arquivo (subclasses 3.2 a 3.6, tipos 1 a 4)",
                       "mai/2025: R$ 530.597.136,83 na mesma releitura"],
        "limitacoes": ["cancelamento e refaturamento podem referir-se a faturas de meses anteriores"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.cde_desconto_medio_fatura",
        "titulo": "Desconto médio por fatura com Tarifa Social",
        "pergunta": "Quanto vale, em média, o desconto em cada fatura com Tarifa Social?",
        "definicao": "Desconto das faturas de faturamento (tipo 1, subclasses 3.2 a 3.6) dividido pelo número dessas faturas, no Brasil ou na UF, no mesmo mês do arquivo.",
        "unidade": "R$ por fatura no mês",
        "grao_geografico": "Brasil, UF",
        "grao_temporal": "mês do arquivo",
        "fontes": ["aneel_cde_beneficiarios"],
        "numerador": "Σ VlrSubsidio das faturas tipo 1 das subclasses 3.2 a 3.6",
        "denominador": "número dessas faturas",
        "formula": "Σ desconto ÷ Σ faturas (razão de somas, nunca média de médias municipais)",
        "regra_agregacao": "razão de somas no território",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["UF", "mês"],
        "regras_comparabilidade": ["depende da tarifa local e do consumo", "a regra de 05/07/2025 (gratuidade até 80 kWh) muda o patamar a partir de jul/2025"],
        "regra_cobertura": "faturas > 0; UF só com municípios válidos",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["mesmas faturas no numerador e no denominador"],
        "limitacoes": ["média por fatura, não desconto de cada família"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.tsee_variacao_12m",
        "titulo": "Variação das UC com Tarifa Social em 12 meses",
        "pergunta": "O número de UC com Tarifa Social cresceu ou caiu no último ano?",
        "definicao": "Variação percentual das UC com Tarifa Social do mês de referência contra o mesmo mês do ano anterior, no Brasil (série nacional) ou na distribuidora (mesmo CNPJ).",
        "unidade": "%",
        "grao_geografico": "Brasil; distribuidora",
        "grao_temporal": "mês contra o mesmo mês 12 meses antes",
        "fontes": ["aneel_scs"],
        "numerador": "UC com Tarifa Social no mês",
        "denominador": "UC com Tarifa Social 12 meses antes",
        "formula": "100 × (UC_m ÷ UC_(m−12) − 1)",
        "regra_agregacao": "razão entre dois totais do mesmo universo",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["mês", "distribuidora"],
        "regras_comparabilidade": ["no Brasil, só comparável quando o mês base também é completo (campo comparavel)",
                                   "na distribuidora, incorporação no intervalo muda o universo (ver incorporacoes)"],
        "regra_cobertura": "mês base presente; ausente fica sem valor",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["mai/2025 contra mai/2024: 2,36%, conferido por soma direta do CSV"],
        "limitacoes": ["não separa entrada de novas famílias de recadastramento e revisão cadastral"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.tsee_dmr_12m",
        "titulo": "DMR da Tarifa Social em 12 meses",
        "pergunta": "Quanto custou a Tarifa Social nos últimos 12 meses, pelo SCS?",
        "definicao": "Soma da Diferença Mensal de Receita (VlrDMR, despacho vigente, um valor por distribuidora e mês) dos 12 meses até o mês de referência.",
        "unidade": "R$ correntes em 12 meses",
        "grao_geografico": "Brasil",
        "grao_temporal": "12 meses móveis",
        "fontes": ["aneel_scs"],
        "numerador": "Σ DMR mensal nacional dos 12 meses",
        "regra_agregacao": "soma de 12 meses; sem valor quando falta qualquer mês da janela; meses incompletos (distribuidora esperada faltando) entram e são contados em meses_incompletos",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["janela de 12 meses"],
        "regras_comparabilidade": ["valores nominais", "não coincide com o valor anual da CDE (ano de referência do orçamento)"],
        "regra_cobertura": "12 meses presentes no SCS; mês incompleto na janela é declarado, não completado",
        "politica_ausencia": "Mês ausente na janela: soma sem valor (não soma parcial).",
        "validacoes": ["jun/2024 a mai/2025: R$ 6.498.825.755,39, conferido por soma direta do CSV"],
        "limitacoes": ["mês incompleto na janela subestima a soma; o número de meses incompletos acompanha o valor"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.tsee_faixas_consumo",
        "titulo": "UC com Tarifa Social por faixa de consumo",
        "pergunta": "Em que faixa de consumo estão as UC com Tarifa Social?",
        "definicao": "UC com Tarifa Social em cada uma das cinco faixas de consumo do SCS (até 30 kWh, 31 a 50, 51 a 100, 101 a 220, acima de 220) e a parte de cada faixa no total do mês.",
        "unidade": "unidades consumidoras; % das UC com Tarifa Social",
        "grao_geografico": "Brasil",
        "grao_temporal": "mês",
        "fontes": ["aneel_scs"],
        "numerador": "Σ UC com Tarifa Social da faixa",
        "denominador": "Σ UC com Tarifa Social das cinco faixas",
        "formula": "100 × UC da faixa ÷ UC das cinco faixas",
        "regra_agregacao": "soma entre distribuidoras no despacho vigente",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["faixa", "mês"],
        "regras_comparabilidade": ["faixas do SCS, não as da regra de desconto de 05/07/2025"],
        "regra_cobertura": "mês de referência e 12 meses antes",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["soma das faixas igual ao total do mês"],
        "limitacoes": ["faixa do consumo faturado do mês, não do consumo habitual"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.cobertura_proxy",
        "titulo": "Cobertura potencial da Tarifa Social (proxy)",
        "pergunta": "Quem pode estar ficando de fora?",
        "definicao": "UC (ou faturas) com Tarifa Social por 100 famílias do Cadastro Único com renda per capita de até meio salário mínimo e cadastro atualizado, no mesmo mês e território. É PROXY: o numerador inclui beneficiários pelo BPC e por equipamento médico, fora do denominador, e conta UC, não famílias.",
        "unidade": "UC (série mensal nacional, SCS) ou faturas com desconto (Brasil, UF e município no mês do mapa, CDE) com Tarifa Social por 100 famílias",
        "grao_geografico": "município, UF, Brasil",
        "grao_temporal": "mês",
        "fontes": ["aneel_scs", "aneel_cde_beneficiarios", "mds_cadunico"],
        "numerador": "UC com Tarifa Social (SCS, série nacional) ou faturas com Tarifa Social (CDE, município e UF)",
        "denominador": "famílias do Cadastro Único com renda per capita até ½ salário mínimo e cadastro atualizado (MI Social)",
        "formula": "100 × Σ numerador ÷ Σ denominador; faixa de sensibilidade com todas as famílias cadastradas no denominador",
        "regra_agregacao": "razão de somas; município com menos de 50 famílias fora da distribuição",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["município", "UF", "mês"],
        "regras_comparabilidade": ["mesmo mês no numerador e no denominador", "critérios de elegibilidade iguais no período (verificado na ANEEL em 30/09/2026)"],
        "regra_cobertura": "municípios com fatura no arquivo e cadastro no MDS; vínculo pelos 6 dígitos do código IBGE",
        "politica_ausencia": "Município sem fatura no arquivo: razão ausente, não zero.",
        "validacoes": ["não se publica número de famílias fora do benefício", "rótulo PROXY em toda exibição"],
        "limitacoes": ["titularidade da conta, falta de acesso à rede e critérios II e III afastam a razão da cobertura real"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.pof_energia_media",
        "titulo": "Despesa média mensal com energia elétrica por família (POF)",
        "pergunta": "Quanto as famílias gastam com energia elétrica por mês?",
        "definicao": "Despesa monetária e não monetária média mensal familiar com energia elétrica (POF 2017-2018), em reais de 15/01/2018. Estimativa amostral: a publicada pelo IBGE na tabela 6715 (estimado pela fonte) e a refeita dos microdados com o plano amostral (estimado pelo observatório), conferidas uma contra a outra.",
        "unidade": "R$ por família e mês (15/01/2018)",
        "grao_geografico": "Brasil, grande região, UF",
        "grao_temporal": "período da pesquisa (jul/2017 a jul/2018)",
        "fontes": ["ibge_pof_6715", "ibge_pof_cv", "ibge_pof_microdados"],
        "numerador": "Σ w·despesa com energia",
        "denominador": "Σ w (famílias)",
        "formula": "Σ w·y ÷ Σ w; erro-padrão por linearização com estrato e UPA",
        "regra_agregacao": "média ponderada pelo fator de expansão",
        "versao_formula": "1.0",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["território", "classe de rendimento (Brasil e regiões)"],
        "regras_comparabilidade": ["estatística histórica; não representa 2026", "reais de 15/01/2018"],
        "regra_cobertura": "CV até 15% publicado; 15% a 30% com cautela; acima de 30% suprimido",
        "politica_ausencia": "Estimativa suprimida por precisão aparece como suprimida, não como zero.",
        "validacoes": ["igual à tabela 6715 em todos os territórios e classes (meio centavo)", "CV comparado ao publicado pelo IBGE (Brasil)"],
        "limitacoes": ["despesa declarada: família sem conta própria aparece com zero"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.pof_razao_medias",
        "titulo": "Participação da energia na despesa total (razão de médias)",
        "pergunta": "Que parte do gasto total das famílias vai para energia elétrica, somando todas?",
        "definicao": "Média da despesa com energia dividida pela média da despesa total do mesmo domínio: é a 'distribuição' publicada pelo IBGE.",
        "unidade": "% da despesa total",
        "grao_geografico": "Brasil, grande região, UF",
        "grao_temporal": "2017-2018",
        "fontes": ["ibge_pof_6715", "ibge_pof_microdados"],
        "numerador": "Σ w·despesa com energia",
        "denominador": "Σ w·despesa total",
        "formula": "100 × Σ w·energia ÷ Σ w·despesa",
        "regra_agregacao": "razão de totais ponderados",
        "versao_formula": "1.0",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["território", "classe de rendimento"],
        "regras_comparabilidade": ["não é a média das participações de cada família (pesa mais as famílias que gastam mais)"],
        "regra_cobertura": "igual à despesa média",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["igual à distribuição da tabela 6715 até o arredondamento de uma casa"],
        "limitacoes": ["subestima o peso típico nas famílias de menor despesa"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.pof_media_razoes",
        "titulo": "Participação média da energia no orçamento de cada família (média das razões)",
        "pergunta": "Para a família típica, quanto a energia pesa no orçamento?",
        "definicao": "Média ponderada, entre famílias, da razão despesa com energia ÷ despesa total (ou ÷ rendimento total e variação patrimonial), e a mediana ponderada da mesma razão.",
        "unidade": "% da despesa total ou da renda",
        "grao_geografico": "Brasil, grande região, UF",
        "grao_temporal": "2017-2018",
        "fontes": ["ibge_pof_microdados"],
        "numerador": "Σ w·(energia ÷ base)",
        "denominador": "Σ w (famílias com base positiva)",
        "formula": "100 × Σ w·(y ÷ x) ÷ Σ w",
        "regra_agregacao": "média ponderada de razões individuais; erro-padrão por linearização",
        "versao_formula": "1.0",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["território", "classe de rendimento", "base (despesa ou renda)"],
        "regras_comparabilidade": ["publicada ao lado da razão de médias, nunca no lugar dela",
                                   "na renda, sempre acompanhada da mediana e da sensibilidade (inclusao.pof_sensibilidade_renda)"],
        "regra_cobertura": "famílias com despesa total (ou renda) positiva",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["mesma base de famílias conferida contra a tabela 6715"],
        "limitacoes": ["sensível a famílias com renda muito baixa; por isso a mediana acompanha"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.pof_sensibilidade_renda",
        "titulo": "Sensibilidade da participação média da energia na renda",
        "pergunta": "Quanto a média das participações na renda depende de poucas famílias com renda declarada quase nula?",
        "definicao": "Para o mesmo domínio da média das participações na renda: (a) a mesma média sem as famílias com despesa de energia acima da renda; (b) o número dessas famílias na amostra e o seu peso em % das famílias; (c) a soma das 3 maiores parcelas w·(energia ÷ renda) ÷ Σw, em ponto percentual. É análise de sensibilidade, não correção da estimativa.",
        "unidade": "% da renda; famílias da amostra; % das famílias; ponto percentual",
        "grao_geografico": "Brasil, grande região, UF",
        "grao_temporal": "2017-2018",
        "fontes": ["ibge_pof_microdados"],
        "numerador": "Σ w·(energia ÷ renda) das famílias com energia ≤ renda",
        "denominador": "Σ w dessas famílias",
        "formula": "100 × Σ w·(y ÷ x) ÷ Σ w no subconjunto; parcelas máximas = 100 × Σ dos 3 maiores w·(y ÷ x) ÷ Σ w",
        "regra_agregacao": "média ponderada no subconjunto; erro-padrão por linearização",
        "versao_formula": "1.0",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["território", "classe de rendimento"],
        "regras_comparabilidade": ["sempre ao lado da média completa e da mediana; nunca substitui a média publicada"],
        "regra_cobertura": "famílias com renda positiva",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["Brasil, até R$ 1.908: média 6,88%, mediana 4,27% (conferidas em reprodução independente dos microdados)"],
        "limitacoes": ["o corte em energia acima da renda é uma escolha de sensibilidade: renda subdeclarada e despesa esporádica alta não se distinguem na POF"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.pof_acima_limiar",
        "titulo": "Famílias com energia acima de um limiar do orçamento (sensibilidade)",
        "pergunta": "Quantas famílias gastam com energia mais que 3%, 5% ou 10% da renda ou da despesa?",
        "definicao": "Proporção ponderada de famílias cuja despesa com energia supera o limiar da renda (ou da despesa total). Os limiares são análise de sensibilidade, não definição oficial de pobreza energética.",
        "unidade": "% das famílias",
        "grao_geografico": "Brasil, grande região, UF",
        "grao_temporal": "2017-2018",
        "fontes": ["ibge_pof_microdados"],
        "numerador": "Σ w·1(energia ÷ base > limiar)",
        "denominador": "Σ w (famílias com base positiva)",
        "formula": "100 × Σ w·indicador ÷ Σ w",
        "regra_agregacao": "proporção ponderada; erro-padrão por linearização",
        "versao_formula": "1.0",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["território", "classe de rendimento", "limiar (3, 5, 10%)", "base"],
        "regras_comparabilidade": ["sempre apresentado com os três limiares"],
        "regra_cobertura": "famílias com base positiva",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["proporções entre 0 e 100 e decrescentes com o limiar"],
        "limitacoes": ["não mede privação (família que deixa de usar energia para economizar não aparece)"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.pnad_com_energia",
        "titulo": "Domicílios com energia elétrica (PNAD Contínua)",
        "pergunta": "Quantos domicílios têm energia elétrica, e de que fonte?",
        "definicao": "Percentual de domicílios com energia elétrica de qualquer fonte e percentual com energia da rede geral (tabela 6737), com o coeficiente de variação publicado.",
        "unidade": "% dos domicílios",
        "grao_geografico": "Brasil, grande região, UF",
        "grao_temporal": "ano",
        "fontes": ["ibge_pnadc_energia"],
        "regra_agregacao": "publicado pelo IBGE",
        "versao_formula": "1.0",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["território", "ano", "situação (urbana, rural)"],
        "regras_comparabilidade": ["erro-padrão = CV × estimativa ÷ 100"],
        "regra_cobertura": "domicílios particulares permanentes",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["percentual entre 0 e 100", "CV publicado junto"],
        "limitacoes": ["não mede qualidade nem continuidade"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.pnad_rede_integral",
        "titulo": "Fornecimento da rede geral em tempo integral (PNAD Contínua)",
        "pergunta": "Entre os domicílios ligados à rede, quantos têm energia o tempo todo?",
        "definicao": "Percentual dos domicílios com energia da rede geral que declaram fornecimento em tempo integral (tabela 6738).",
        "unidade": "% dos domicílios ligados à rede geral",
        "grao_geografico": "Brasil, grande região, UF",
        "grao_temporal": "ano",
        "fontes": ["ibge_pnadc_energia"],
        "regra_agregacao": "publicado pelo IBGE",
        "versao_formula": "1.0",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["território", "ano", "situação"],
        "regras_comparabilidade": ["denominador são os domicílios ligados à rede, não todos"],
        "regra_cobertura": "domicílios com energia de rede geral",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["denominador conferido: domicílios em tempo integral ÷ domicílios de rede geral reproduz o percentual publicado"],
        "limitacoes": ["declaração do morador, não medição de interrupções"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.pnad_sem_energia",
        "titulo": "Domicílios sem energia elétrica (diferença calculada)",
        "pergunta": "Quantos domicílios ainda não têm energia elétrica?",
        "definicao": "Domicílios (tabela 6731, total) menos domicílios com energia elétrica de qualquer fonte (tabela 6737), em mil.",
        "unidade": "mil domicílios",
        "grao_geografico": "Brasil, grande região, UF",
        "grao_temporal": "ano",
        "fontes": ["ibge_pnadc_energia"],
        "numerador": "domicílios − domicílios com energia",
        "formula": "domicílios_mil − domicílios_com_energia_mil",
        "regra_agregacao": "diferença de duas estimativas publicadas",
        "versao_formula": "1.0",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["território", "ano", "situação"],
        "regras_comparabilidade": ["sem erro-padrão publicado; valores pequenos são imprecisos"],
        "regra_cobertura": "domicílios particulares permanentes",
        "politica_ausencia": ("Estimativa ausente: sem valor (estado ausente). Diferença zero entre as duas contagens arredondadas em milhares: "
                              "sem valor e estado menos_de_1_mil (a verdadeira fica entre 0 e 1 mil), nunca 0,0 mil."),
        "validacoes": ["percentual complementar coerente com 100 − percentual com energia",
                       "RR 2025 rural: 20 − 20 mil com 99,3% com energia vira menos_de_1_mil, não zero"],
        "limitacoes": ["as duas estimativas vêm arredondadas em milhares"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.sisol_localidades",
        "titulo": "Localidades e população dos sistemas isolados (PASI)",
        "pergunta": "Quantas pessoas vivem em localidades fora do SIN?",
        "definicao": "Localidades listadas no ciclo de planejamento dos sistemas isolados (EPE, PASI) e a soma da população informada.",
        "unidade": "localidades; pessoas",
        "grao_geografico": "localidade, município, UF, distribuidora",
        "grao_temporal": "ciclo anual de planejamento",
        "fontes": ["epe_pasi_localidades"],
        "numerador": "contagem de localidades; Σ população",
        "regra_agregacao": "contagem e soma por ciclo",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["ciclo", "UF", "distribuidora", "programa de universalização"],
        "regras_comparabilidade": ["entrada e saída da lista entre ciclos não têm motivo informado"],
        "regra_cobertura": "localidades do ciclo; a soma de população usa só as localidades que a informam",
        "politica_ausencia": ("População ausente não vira zero: cada agregado (ciclo, UF, distribuidora) soma só as populações informadas, traz a "
                              "contagem de localidades sem população e fica sem valor quando nenhuma localidade do grupo informa (caso da VIBRA ENERGIA no ciclo 2025)."),
        "validacoes": ["ciclo 2025 conferido contra o caderno em PDF da EPE (160 localidades, 1,965 milhão de pessoas)"],
        "limitacoes": ["população informada no planejamento, não censitária"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.cde_custeio",
        "titulo": "CDE: valores anuais para Tarifa Social, Luz para Todos e CCC",
        "pergunta": "Quanto a CDE destina por ano à Tarifa Social, à universalização e aos sistemas isolados?",
        "definicao": "Valores anuais de despesa da CDE nas rubricas Subsídio Baixa Renda, Programa Luz para Todos e CCC, como publicados pela ANEEL.",
        "unidade": "R$ correntes por ano",
        "grao_geografico": "Brasil",
        "grao_temporal": "ano",
        "fontes": ["aneel_cde_custeio"],
        "regra_agregacao": "valor da fonte; participação = rubrica ÷ soma das rubricas de despesa do ano",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["ano", "rubrica"],
        "regras_comparabilidade": ["valores nominais", "ano em curso é orçamento"],
        "regra_cobertura": "anos publicados (desde 2013)",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["rubricas conferidas por nome exato"],
        "limitacoes": ["o conjunto não separa orçado de executado"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.lpt_domicilios_atendidos",
        "titulo": "Domicílios atendidos pelo Luz para Todos",
        "pergunta": "Quantos domicílios o programa de universalização ligou, onde e quando?",
        "definicao": "Soma de qtddomicilios do arquivo domicilios_atendidos.csv do MME: ligações novas homologadas, por programa (rural, regiões remotas da Amazônia Legal, recurso da distribuidora), município, UF e mês do atendimento.",
        "unidade": "domicílios",
        "grao_geografico": "município (código IBGE pelo nome exato na UF); UF; Brasil",
        "grao_temporal": "mês do atendimento; ano",
        "fontes": ["mme_luz_para_todos"],
        "numerador": "Σ qtddomicilios",
        "regra_agregacao": "soma; UF e Brasil somam todos os municípios, inclusive os sem código IBGE",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["programa", "UF", "município", "mês", "ano"],
        "regras_comparabilidade": ["domicílio ligado não é pessoa nem unidade consumidora com Tarifa Social",
                                   "o ano corrente está incompleto e não compete com anos completos",
                                   "não se compara com domicílios sem energia da PNAD como se fosse o mesmo universo"],
        "regra_cobertura": "todas as linhas válidas do arquivo; linha com quantidade, data, estado ou programa inválido fica fora e contada no diagnóstico",
        "politica_ausencia": ("Programa sem nenhuma linha no ano ou na UF: sem valor. Programa com linhas que somam zero (qtddomicilios = 0 na fonte): "
                              "0 publicado, como em 'Recurso da Distribuidora' em 2017 e 2018."),
        "validacoes": ["soma por UF e por município iguais ao total nacional", "municípios sem correspondência exata de nome contados e publicados"],
        "limitacoes": ["o arquivo muda quando chegam homologações de meses anteriores", "sem código IBGE na fonte"],
        "gold": GOLD, "paginas": PAGINAS,
    },
    {
        "id": "inclusao.lpt_recursos",
        "titulo": "Recursos do Luz para Todos por UF e fonte",
        "pergunta": "Quanto foi contratado e pago no programa, e de que fonte?",
        "definicao": "Soma, por UF, dos valores contratados e pagos por contrato no arquivo recursos_aplicados.csv do MME, separados por fonte: subvenção da CDE, empréstimo da RGR, Caixa ou outras fontes e contrapartida do agente executor.",
        "unidade": "R$ correntes",
        "grao_geografico": "UF",
        "grao_temporal": "vida do contrato (primeira a última liberação)",
        "fontes": ["mme_luz_para_todos"],
        "numerador": "Σ valor do campo por contrato",
        "regra_agregacao": "soma por UF e fonte; contratado e pago nunca se somam",
        "versao_formula": "1.0",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["UF", "fonte do recurso", "situação (contratado, pago)"],
        "regras_comparabilidade": ["valores nominais de anos diferentes, sem correção", "não se somam aos valores anuais da CDE (custeio)"],
        "regra_cobertura": "contratos do arquivo com estado reconhecido",
        "politica_ausencia": AUSENCIA,
        "validacoes": ["números no formato brasileiro conferidos na leitura", "contratos repetidos contados no diagnóstico"],
        "limitacoes": ["o dicionário do MME descreve vlrpagocaixa como pago da RGR; o módulo segue a correspondência com vlrempenhadocaixa"],
        "gold": GOLD, "paginas": PAGINAS,
    },
]
