"""Métricas do módulo Mercado (P032 a P035: livre e regulado, agentes e migração, MRE e GSF,
encargos e contabilização). A fórmula roda em pipeline/energia/modulos/mercado.py (com os
leitores de pipeline/energia/fontes/{epe,aneel,mme,ccee}_mercado.py); a interface lê o valor
calculado e esta definição, nunca refaz a conta.

Três universos de consumo convivem no módulo e nenhum é igualado à carga do ONS: o consumo na
rede informado ao SAM e consolidado pela EPE, o consumo contabilizado pela CCEE (centro de
gravidade, com perdas da rede básica rateadas) e o mercado faturado por distribuidora no SAMP
da ANEEL (sem o consumidor livre ligado direto à rede básica). Agente (CNPJ), perfil (código do
perfil na CCEE), parcela de carga (unidade de consumo modelada na CCEE) e unidade consumidora
(ponto de entrega medido) são contagens diferentes e nunca se somam entre si."""

_GOLD = "mercado.json"
_PAG = ["/setor-eletrico/mercado"]
_EPE = ["epe_consumo_mensal", "epe_consumo_classe"]
_SAMP = ["aneel_samp_mercado"]
_CB = ["aneel_conta_bandeira"]
_MME = ["mme_boletim_monitoramento"]
_IM = ["ccee_infomercado"]


def _ccee(*nomes):
    return [f"ccee_{n}" for n in nomes]


_CCEE_INICIO = ("Os conjuntos abertos da CCEE começam em 2023 (entre maio e dezembro, conforme o conjunto); não há série "
                "anterior neste formato no portal de dados abertos.")
_RECONTAB = ("A CCEE pode recontabilizar meses já publicados; cada captura fica no silver e a revisão entre capturas é "
             "registrada e publicada na evidência.")
_AUSENCIA_JANELA = ("Janela de 12 meses só é calculada com os 12 meses publicados; mês ausente interrompe a janela (nunca é "
                    "completado, interpolado ou tratado como zero).")
_NAO_CARGA = ("Consumo não é carga: a carga do ONS inclui perdas na rede e consumo não apurado; o Boletim do MME publica a "
              "diferença como 'Perdas e Diferenças'. ACL + ACR fecha com o universo da própria fonte, não com a carga.")
_EPE_PRELIM = "O ano corrente é preliminar pela EPE (asterisco na planilha formatada) e pode ser revisado."
_QUEBRA_VAREJISTA = ("Quebra na CCEE em fevereiro de 2026: a classe Comercializador deu lugar à Varejista e o conjunto "
                     "CONSUMO_MENSAL_AMBIENTE_COMERCIALIZACAO deixou de contar a Varejista no ACL (cerca de 2.500 MW médios); "
                     "o ACL do observatório soma todas as classes exceto Distribuidor, o que mantém a série comparável.")
_TIPOS_ESS = ("ENCARGO_CONST_ON, ENCARGO_CONST_OFF, ENCARGO_REST_OP_UNIT_COMT, ENCARGO_CS, OUTROS_SERVICOS_ANCILARES, "
              "ENCARGO_SEG_ENER, RECEBIMENTO_ENCARGO_DH, ENCARGO_IMPORTACAO e RECEBIMENTO_ENCARGO_RESERVA_OP")
_PLD = ("O PLD é o preço do mercado de curto prazo, não o preço dos contratos do mercado livre; o módulo não publica preço "
        "de contrato, de PPA nem curva a termo.")


def _m(**kw):
    base = {"gold": _GOLD, "paginas": _PAG, "versao_formula": "1"}
    base.update(kw)
    return base


METRICAS = [
    # ------------------------------------------------------------------ P032
    _m(id="mercado_participacao_livre_epe",
       titulo="Participação do mercado livre no consumo na rede (EPE)",
       pergunta="Que parte do consumo de energia elétrica na rede foi comprada no mercado livre?",
       definicao="Consumo dos consumidores livres (TipoConsumidor = Livre) dividido pelo consumo total (cativo + livre) da tabela 'CONSUMO E NUMCONS SAM' dos dados abertos da EPE, no mês, no ano civil ou na janela de 12 meses.",
       unidade="%", grao_geografico="Brasil; região, subsistema e UF (aberturas da fonte)", grao_temporal="mês; ano civil; 12 meses",
       fontes=_EPE, numerador="Σ consumo livre do período (MWh)", denominador="Σ consumo cativo + livre do período (MWh)",
       formula="livre_pct = 100 × Σ livre ÷ Σ (cativo + livre)",
       regra_agregacao="Razão das somas em MWh do período; nunca média de percentuais mensais ou regionais.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["mês", "ano", "região", "subsistema", "classe", "UF"],
       regras_comparabilidade=["Ano incompleto (menos de 12 meses com cativo e livre) não compete com ano completo.", _EPE_PRELIM, _NAO_CARGA],
       regra_cobertura="Janeiro de 2004 até o último mês publicado pela EPE (UF até o penúltimo).",
       politica_ausencia="Mês sem cativo ou sem livre fica sem participação; linha sem consumo não entra na soma (não vira zero).",
       validacoes=["Soma das linhas da tabela longa = total nacional da planilha formatada da EPE, mês a mês, para total, cativo, livre e consumidores (tolerância: maior entre 1 MWh e 10⁻⁶ do total do mês; 1 unidade consumidora).",
                   "Soma de 12 meses do ACL conferida com o Boletim Mensal do MME (GWh inteiros; diferença acima de 1 GWh vira ressalva, pois o boletim usa a consolidação da EPE da data da edição)."],
       limitacoes=["Livre inclui consumidores livres, especiais e autoprodutores que compram no ACL; a fonte não separa as categorias.",
                   "Não inclui autoprodução sem uso da rede nem perdas."]),
    _m(id="mercado_consumo_cativo_livre_epe",
       titulo="Consumo de energia elétrica na rede, cativo e livre (EPE)",
       pergunta="Quanto se consumiu na rede em cada ambiente de contratação?",
       definicao="Coluna Consumo (MWh) da tabela 'CONSUMO E NUMCONS SAM' (e 'SAM UF') dos dados abertos de consumo mensal da EPE, somada por tipo de consumidor e pela abertura pedida.",
       unidade="MWh", grao_geografico="Brasil; região; subsistema (SE, S, NE, N, sistemas isolados); UF", grao_temporal="mês; ano civil; 12 meses",
       fontes=_EPE, formula="Σ Consumo das linhas da abertura e do tipo no período",
       regra_agregacao="Soma simples de volumes do mesmo período e do mesmo tipo.",
       natureza_fonte="OBSERVADO", natureza_transformacao="OBSERVADO",
       dimensoes=["mês", "ano", "região", "subsistema", "classe", "tipo", "UF"],
       regras_comparabilidade=[_NAO_CARGA, _EPE_PRELIM],
       regra_cobertura="Janeiro de 2004 até o último mês publicado.",
       politica_ausencia="Célula vazia é ausência (None); a soma só usa o que a fonte publicou e o mês sem linha do tipo fica sem valor.",
       validacoes=["Esquema conferido na chegada: colunas, regiões, subsistemas, classes, tipos e UF fora do dicionário interrompem a leitura.",
                   "Reconciliação com o total nacional da planilha formatada da EPE."],
       limitacoes=["A tabela por UF vai até o penúltimo mês publicado."]),
    _m(id="mercado_ucs_livres_epe",
       titulo="Unidades consumidoras no mercado livre (EPE)",
       pergunta="Quantos pontos de consumo compram energia no mercado livre?",
       definicao="Coluna Consumidores (número de unidades consumidoras) das linhas com TipoConsumidor = Livre, somada no mês; variação líquida = estoque do mês menos o do mês anterior (ou de 12 meses antes).",
       unidade="unidades consumidoras", grao_geografico="Brasil; classe", grao_temporal="mês",
       fontes=_EPE, formula="Σ Consumidores (Livre) no mês; variação = estoque_m − estoque_{m−k}",
       regra_agregacao="Soma de estoques do mesmo mês; variação entre estoques de meses diferentes.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["mês", "classe"],
       regras_comparabilidade=["Unidade consumidora não é agente nem perfil: uma empresa pode ter várias unidades.",
                               "Variação líquida não separa quem entrou de quem saiu."],
       regra_cobertura="Janeiro de 2004 até o último mês publicado.",
       politica_ausencia="Mês sem número de consumidores fica sem estoque e sem variação.",
       validacoes=["Soma = número de consumidores livres da planilha formatada da EPE (tolerância de 1 unidade).",
                   "Comparação com as unidades livres faturadas no SAMP no último mês publicado por quase todas as distribuidoras (tolerância de 3%: universos diferentes)."],
       limitacoes=["Definição de unidade consumidora da Resolução ANEEL 83/2004, citada pelo dicionário da EPE."]),
    _m(id="mercado_participacao_acl_ccee",
       titulo="Participação do ACL no consumo contabilizado (CCEE)",
       pergunta="Que parte do consumo contabilizado pela CCEE está no ambiente livre?",
       definicao="ACL = soma do CONSUMO de todas as classes de agente exceto Distribuidor; ACR = CONSUMO da classe Distribuidor (conjunto CONSUMO_CLASSE_AGENTE, centro de gravidade, MWmed). Participação = razão das energias do período (MWmed × horas do mês).",
       unidade="%", grao_geografico="SIN", grao_temporal="mês; 12 meses",
       fontes=_ccee("consumo_classe_agente", "consumo_mensal_ambiente_comercializacao"),
       numerador="Σ ACL_m × horas_m (MWh)", denominador="Σ (ACR_m + ACL_m) × horas_m (MWh)",
       formula="acl_pct = 100 × Σ(ACL × horas) ÷ Σ((ACR + ACL) × horas)",
       regra_agregacao="Razão das somas em MWh, ponderada pelas horas de cada mês.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["mês", "classe de agente"],
       regras_comparabilidade=["Centro de gravidade (perdas da rede básica rateadas): não é comparável ao consumo da EPE sem esse ajuste.", _QUEBRA_VAREJISTA, _NAO_CARGA],
       regra_cobertura="Maio de 2023 até o último mês contabilizado.", politica_ausencia=_AUSENCIA_JANELA,
       validacoes=["Σ classes = ACR + ACL do conjunto de ambiente (mais a classe Varejista a partir de fevereiro de 2026), resíduo até 5 MW médios por mês.",
                   "ACR + ACL conferido com o 'Consumo/Geração' do InfoMercado de agosto e outubro de 2024 e julho de 2026 (diferença de 0,1% a 0,2%, publicada como ressalva: a definição do InfoMercado não é detalhada)."],
       limitacoes=[_CCEE_INICIO, _RECONTAB]),
    _m(id="mercado_livre_distribuidora_samp",
       titulo="Energia e unidades do mercado livre e cativo faturadas por distribuidora (SAMP)",
       pergunta="Quanto do mercado de cada distribuidora já é livre?",
       definicao="SAMP da ANEEL: Energia TUSD (kWh) e número de consumidores com DscOpcaoEnergia = LIVRE; Energia TE (kWh) e número de consumidores do CATIVO; só os tipos de mercado faturados na própria competência (refaturamento em coluna própria). Participação faturada = livre ÷ (livre + cativo) do ano.",
       unidade="MWh; unidades consumidoras; %", grao_geografico="distribuidora (CNPJ)", grao_temporal="mês; ano civil",
       fontes=_SAMP, numerador="Σ energia TUSD livre do ano (MWh)", denominador="Σ energia TUSD livre + energia TE cativa do ano (MWh)",
       formula="livre_pct_faturada = 100 × livre ÷ (livre + cativo); kWh ÷ 1.000 = MWh",
       regra_agregacao="Soma das linhas da mesma distribuidora, mês e medida (abertura por classe, subgrupo e posto da fonte); taxa só com os 12 meses do ano.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["distribuidora", "mês", "ano", "característica do consumidor livre"],
       regras_comparabilidade=["Mês só entra em comparação nacional quando publicado por pelo menos 95% da mediana de distribuidoras dos 12 meses anteriores.",
                               "Energia cativa de quem tem micro ou minigeração é a líquida da compensação."],
       regra_cobertura="Janeiro de 2019 até a última competência publicada; ano de referência = último ano civil completo.",
       politica_ausencia="Distribuidora sem linha no mês não entra na soma do mês; taxa anual exige 12 meses.",
       validacoes=["Esquema conferido no Parquet (colunas exigidas); tipos de mercado desconhecidos são contados e ficam fora.",
                   "Unidades livres do SAMP comparadas às da EPE no mesmo mês (98,5% em julho de 2026)."],
       limitacoes=["Consumidor livre ligado direto à rede básica não é faturado por distribuidora e não aparece.",
                   "'Fonte incentivada' inclui os consumidores especiais sem separá-los; 'ERC' não é definido no dicionário."]),
    _m(id="mercado_consumo_sobre_carga_mme",
       titulo="Consumo na rede como parte da carga (Boletim do MME)",
       pergunta="Por que ACL + ACR não é igual à carga do sistema?",
       definicao="Consumo total da EPE no mês (GWh) dividido pela carga do Brasil publicada na tabela de consumo por classe do Boletim Mensal de Monitoramento do MME, que traz a linha 'Perdas e Diferenças'.",
       unidade="%", grao_geografico="Brasil", grao_temporal="mês (edição do boletim)",
       fontes=_EPE + _MME, numerador="consumo cativo + livre da EPE no mês (GWh)", denominador="carga total do mês no boletim (GWh)",
       formula="consumo_sobre_carga_pct = 100 × consumo_EPE ÷ carga_MME",
       regra_agregacao="Razão de um mês; não é agregada.", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["mês"], regras_comparabilidade=[_NAO_CARGA],
       regra_cobertura="Meses das edições de 2026 do boletim acessíveis no portal do MME.",
       politica_ausencia="Edição sem a tabela reconhecida não gera linha.",
       validacoes=["Tabela de consumo por ambiente do boletim conferida na extração: ACR + ACL = Total (tolerância de 1 GWh)."],
       limitacoes=["Edições anteriores a 2026 não estão acessíveis no portal do MME."]),
    # ------------------------------------------------------------------ P033
    _m(id="mercado_agentes_contabilizados",
       titulo="Agentes na contabilização da CCEE",
       pergunta="Quantos agentes participaram da contabilização do mês, por classe?",
       definicao="Coluna QUANTIDADE_AGENTE_CONTABILIZACAO do conjunto AGENTE_QTD_CONTABILIZACAO, por classe e somada no mês.",
       unidade="agentes", grao_geografico="SIN", grao_temporal="mês", fontes=_ccee("agente_qtd_contabilizacao"),
       formula="Σ QUANTIDADE_AGENTE_CONTABILIZACAO das classes do mês",
       regra_agregacao="Soma das classes do mesmo mês (a fonte conta cada agente na sua classe).",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["mês", "classe"],
       regras_comparabilidade=["Agente é pessoa jurídica (CNPJ): novo perfil não é empresa nova."],
       regra_cobertura="Dezembro de 2023 até o último mês contabilizado.", politica_ausencia="Classe sem linha no mês não é somada (não vira zero).",
       validacoes=["Classes dentro do domínio do dicionário mais Varejista, Importador e Transmissor (conferidas nos arquivos); outra classe recusa o arquivo.",
                   "Conferido com o InfoMercado (agosto e outubro de 2024: 15.803 e 15.936 no conjunto aberto contra 15.795 e 15.932 publicados; julho de 2026: 16.376 contra 16.364): ressalva, o conjunto é a versão vigente da contabilização."],
       limitacoes=[_CCEE_INICIO, _RECONTAB]),
    _m(id="mercado_fluxo_agentes_associados",
       titulo="Entradas e saídas de agentes associados (CNPJ)",
       pergunta="Quantas empresas entraram e saíram da CCEE em cada mês?",
       definicao="Lista de agentes associados mês a mês (LISTA_AGENTE_ASSOCIADO): entrada no mês m = CNPJ presente em m e ausente em m−1; saída = presente em m−1 e ausente em m; estoque = CNPJ distintos no mês.",
       unidade="agentes (CNPJ)", grao_geografico="SIN", grao_temporal="mês", fontes=_ccee("lista_agente_associado"),
       formula="entradas_m = |CNPJ_m − CNPJ_{m−1}|; saídas_m = |CNPJ_{m−1} − CNPJ_m|",
       regra_agregacao="Contagem de conjuntos de CNPJ entre meses consecutivos; o primeiro mês da série não tem fluxo.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["mês", "classe do agente"],
       regras_comparabilidade=["Saída da lista não é sinônimo de desligamento: sucessão e mudança de CNPJ também tiram um CNPJ da lista.",
                               "Identidade pelo CNPJ de 14 dígitos (nunca por semelhança de nome)."],
       regra_cobertura="Outubro de 2025 (primeiro mês publicado) até o último mês.", politica_ausencia="Mês sem lista não tem estoque; mês seguinte a uma lacuna não tem fluxo.",
       validacoes=["CNPJ validado (14 dígitos); linha sem mês ou CNPJ é contada à parte e não entra."],
       limitacoes=["A lista mês a mês só existe a partir de outubro de 2025."]),
    _m(id="mercado_perfis_cadastro",
       titulo="Perfis de agente cadastrados na CCEE",
       pergunta="Quantos perfis existem, de quantos agentes, e quantos perfis cada agente tem?",
       definicao="Posição do cadastro LISTA_PERFIL_V1: perfis (COD_PERF_AGENTE) e agentes (COD_AGENTE) distintos por classe do perfil e status; distribuição do número de perfis ativos por agente.",
       unidade="perfis; agentes", grao_geografico="SIN", grao_temporal="posição (data de publicação do recurso)",
       fontes=_ccee("lista_perfil_v1"), formula="contagem de códigos distintos por classe e status",
       regra_agregacao="Contagens de códigos distintos; agentes por classe não se somam (um agente pode ter perfis em mais de uma classe).",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["classe do perfil", "status"],
       regras_comparabilidade=["Perfil não é empresa: um agente pode ter vários perfis (por exemplo, por fonte incentivada)."],
       regra_cobertura="Uma posição do cadastro (a mais recente publicada).", politica_ausencia="Linha sem código de agente ou de perfil é contada à parte.",
       validacoes=["Classes dentro do domínio (com as não documentadas declaradas); outra classe recusa o arquivo."],
       limitacoes=["Sem histórico mensal: o cadastro é uma posição, então o fluxo de perfis não é publicado."]),
    _m(id="mercado_parcelas_carga_migracao",
       titulo="Parcelas de carga no ACL e migrações no mês",
       pergunta="Quantas unidades de consumo estão modeladas no mercado livre e quantas migraram no mês?",
       definicao="Conjunto PARCELA_CARGA_CONSUMO: parcelas (COD_PARCELA_CARGA) distintas com linha no mês; migração no mês = parcela cuja DATA_MIGRACAO cai no próprio mês de referência; consumo ACL e total somados (MWh).",
       unidade="parcelas de carga; MWh", grao_geografico="SIN; submercado; UF", grao_temporal="mês",
       fontes=_ccee("parcela_carga_consumo"), formula="contagem de COD_PARCELA_CARGA distintos; migrações = parcelas com DATA_MIGRACAO no mês",
       regra_agregacao="Contagens de códigos distintos por mês; consumo somado.", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["mês", "submercado", "UF"],
       regras_comparabilidade=["Parcela de carga não é unidade consumidora: uma parcela pode reunir várias UCs."],
       regra_cobertura="Abril de 2024 até o último mês publicado.", politica_ausencia="Linha sem código de parcela é contada à parte e não entra.",
       validacoes=["Parcelas por submercado somam o total do mês."],
       limitacoes=["A data de migração é a da parcela no cadastro atual; migração de parcela depois desligada pode não aparecer."]),
    _m(id="mercado_desligamentos",
       titulo="Desligamentos de agentes da CCEE",
       pergunta="Quantos agentes deixaram a CCEE, por tipo e classe?",
       definicao="Conjuntos DESLIGAMENTO_VOLUNTARIO e DESLIGAMENTO_COMPULSORIO: desligamentos por ano da data, tipo e classe do agente desligado, com o tipo de sucessão.",
       unidade="desligamentos", grao_geografico="SIN", grao_temporal="ano (data do desligamento)",
       fontes=_ccee("desligamento_voluntario", "desligamento_compulsorio"), formula="contagem de linhas por ano, tipo e classe",
       regra_agregacao="Contagem; cada linha é um desligamento aprovado pelo Conselho de Administração.", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["ano", "tipo", "classe", "sucessão"],
       regras_comparabilidade=["Desligamento voluntário com sucessão não é saída da atividade: o sucessor continua."],
       regra_cobertura="Histórico publicado nos arquivos de 2026 (desligamentos voluntários desde 2010 e compulsórios desde 2013).", politica_ausencia="Linha sem data é contada à parte e não entra.",
       validacoes=["Cabeçalho conferido (falha fechada); CNPJ validado."],
       limitacoes=["Arquivo único com o histórico; atualização anual pela fonte."]),
    _m(id="mercado_agentes_aneel",
       titulo="Agentes cadastrados na ANEEL por atividade",
       pergunta="Quantas pessoas jurídicas exercem cada atividade do setor?",
       definicao="Cadastro de agentes do setor elétrico da ANEEL: CNPJ distintos, situação ativa e indicadores de comercialização, distribuição, geração e transmissão.",
       unidade="agentes (CNPJ)", grao_geografico="Brasil", grao_temporal="posição (data de geração do arquivo)",
       fontes=["aneel_agentes_mercado"], formula="contagem de CNPJ ativos com o indicador da atividade",
       regra_agregacao="Contagens por atividade (um CNPJ pode ter várias).", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["atividade"], regras_comparabilidade=["Cadastro da ANEEL não é a lista de associados da CCEE."],
       regra_cobertura="Posição do arquivo publicado.", politica_ausencia="Situação vazia não conta como ativa.",
       validacoes=["Esquema conferido (colunas exigidas); indicador fora de 0 e 1 é contado."],
       limitacoes=["O indicador 2 em geração aparece em uma linha sem definição no dicionário."]),
    # ------------------------------------------------------------------ P034
    _m(id="mercado_gsf",
       titulo="Fator de ajuste do MRE (GSF)",
       pergunta="Quanto as hidrelétricas do MRE geraram em relação à garantia física ajustada?",
       definicao="Geração das usinas do MRE no centro de gravidade (GERACAO_MRE, soma dos quatro submercados, conjunto GERACAO_SUBMERCADO) dividida pela garantia física modulada ajustada pelo fator de disponibilidade (GARANTIA_FISICA_MODULADA_FDISP, conjunto MRE_MENSAL).",
       unidade="%", grao_geografico="MRE (SIN)", grao_temporal="mês; ano; 12 meses",
       fontes=_ccee("geracao_submercado", "mre_mensal", "garantia_fisica_sazo_mre_submercado") + _IM,
       numerador="Σ GERACAO_MRE × horas (MWh)", denominador="Σ GARANTIA_FISICA_MODULADA_FDISP × horas (MWh)",
       formula="GSF = 100 × Σ(geração MRE × horas) ÷ Σ(GFIS_2 × horas)",
       regra_agregacao="Período = razão das somas em MWh; nunca média de fatores mensais.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["mês", "ano"],
       regras_comparabilidade=["Garantia física e geração ficam em colunas separadas; o fator é razão de energias do mesmo perímetro.",
                               "Não se infere exposição financeira de usina ou agente."],
       regra_cobertura="Maio de 2023 até o último mês contabilizado, com os quatro submercados.",
       politica_ausencia="Mês sem os quatro submercados fica sem GSF; janela incompleta não é calculada.",
       validacoes=["Reproduz o fator publicado no InfoMercado mensal: 79,37% em agosto e 73,49% em outubro de 2024 e 76,83% em julho de 2026 (tolerância de 0,006 p.p.).",
                   "Σ garantia física sazonalizada dos submercados = garantia física sazonalizada do MRE (diferença 0)."],
       limitacoes=["A CCEE não publica o GSF como coluna dos dados abertos.", _CCEE_INICIO]),
    _m(id="mercado_risco_hidrologico_acr",
       titulo="Custo do risco hidrológico alocado às distribuidoras",
       pergunta="Quanto do risco hidrológico recaiu sobre o mercado regulado?",
       definicao="Conta Bandeira (ANEEL), custos apurados pela CCEE por distribuidora e competência: risco hidrológico de Itaipu + das usinas repactuadas + das cotas de garantia física (CCGF); a previsão de risco na tarifa e o prêmio de risco são publicados à parte.",
       unidade="R$ nominais", grao_geografico="distribuidora (CNPJ); Brasil", grao_temporal="mês de competência; ano; 12 meses",
       fontes=_CB, formula="rh_bruto = VlrRiscoHidrologicoItaipu + VlrRiscoHidrologicoRepactuadas + VlrRiscoHidrologicoCCGF",
       regra_agregacao="Soma de valores nominais das competências e das distribuidoras (inclusive linhas sem CNPJ).",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["mês", "ano", "distribuidora"],
       regras_comparabilidade=["Valores nominais: comparação entre anos distantes sem correção monetária é indicativa."],
       regra_cobertura="Janeiro de 2015 até a última competência publicada.", politica_ausencia="Campo vazio não entra na soma; mês sem algum dos três componentes fica sem total.",
       validacoes=["Identidade do dicionário em cada linha: CCGF e repactuadas líquido = repactuadas + CCGF + previsão + prêmio (0 linhas fora da tolerância de R$ 1)."],
       limitacoes=["É o risco que cabe ao consumidor cativo, não o resultado das usinas.", "A ANEEL não informa a data de cada atualização da base."]),
    # ------------------------------------------------------------------ P035
    _m(id="mercado_ess",
       titulo="Encargos de serviços do sistema (ESS)",
       pergunta="Quanto custaram, por tipo, os serviços do sistema cobrados na contabilização?",
       definicao=f"Soma dos nove tipos do conjunto ENCARGO_ESS_ANCILAR ({_TIPOS_ESS}) no mês de competência; as seis colunas RESSARCIMENTO_* detalham OUTROS_SERVICOS_ANCILARES e não são somadas de novo.",
       unidade="R$ nominais", grao_geografico="SIN", grao_temporal="mês de competência; 12 meses",
       fontes=_ccee("encargo_ess_ancilar") + _IM + _MME, formula="ESS_m = Σ dos nove tipos; ESS_12m = Σ ESS_m",
       regra_agregacao="Soma de valores nominais por tipo e por mês.", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["mês", "tipo de encargo"],
       regras_comparabilidade=["Competência (mês de referência) não é pagamento: o pagamento sai depois do alívio com recursos do mercado.",
                               "O total do InfoMercado e do boletim do MME inclui a resposta da demanda, que fica em métrica própria.", _PLD],
       regra_cobertura="Julho de 2023 até o último mês contabilizado.", politica_ausencia="Mês com algum tipo vazio fica sem total e interrompe a janela.",
       validacoes=["OUTROS_SERVICOS_ANCILARES = Σ ressarcimentos em todos os meses (diferença de R$ 0,00).",
                   "Componentes e total sem as parcelas fora do conjunto (resposta da demanda, suporte de reativo do sandbox) conferidos com o InfoMercado: R$ 477,52, 265,48 e 63,89 milhões em agosto e outubro de 2024 e julho de 2026 (tolerância de R$ 0,06 milhão no total e R$ 0,005 milhão por parcela publicada).",
                   "Tipos por mês conferidos com o Boletim do MME de 2026 (66 de 66 dentro de 0,5 mil R$)."],
       limitacoes=[_CCEE_INICIO, _RECONTAB]),
    _m(id="mercado_resposta_demanda",
       titulo="Encargo de resposta da demanda",
       pergunta="Quanto foi pago por redução voluntária de consumo, repassado como encargo?",
       definicao="Coluna RECEBIMENTO_ENCARGO_RD do conjunto RD_ENCARGOS_CONTAB_MENSAL, somada nos submercados com valor no mês.",
       unidade="R$ nominais", grao_geografico="SIN; submercado", grao_temporal="mês de competência",
       fontes=_ccee("rd_encargos_contab_mensal") + _MME + _IM, formula="RD_m = Σ RECEBIMENTO_ENCARGO_RD dos submercados com valor",
       regra_agregacao="Soma dos submercados com valor publicado.", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["mês", "submercado"], regras_comparabilidade=["Não faz parte do conjunto ENCARGO_ESS_ANCILAR."],
       regra_cobertura="Janeiro de 2024 até o último mês publicado; outubro de 2024 não está no arquivo.",
       politica_ausencia="Célula vazia é ausência; mês com os quatro submercados vazios fica sem valor (não vira zero).",
       validacoes=["Agosto de 2024 = InfoMercado (R$ 3,87 milhões); fevereiro a maio de 2026 = boletim do MME.",
                   "Janeiro de 2026 diverge do boletim do MME (5.859 mil R$ no boletim; 0 no conjunto): divergência entre fontes publicada."],
       limitacoes=["A fonte não explica a diferença de janeiro de 2026 nem a ausência de outubro de 2024."]),
    _m(id="mercado_eer",
       titulo="Encargo de energia de reserva (EER)",
       pergunta="Quanto os usuários pagaram pela contratação da energia de reserva?",
       definicao="Coluna ENCARGO_ENERGIA_RESERVA do conjunto RESERVA_ENCARGO, por mês de competência; janela de 12 meses = soma.",
       unidade="R$ nominais", grao_geografico="SIN", grao_temporal="mês; 12 meses", fontes=_ccee("reserva_encargo"),
       formula="EER_12m = Σ ENCARGO_ENERGIA_RESERVA dos 12 meses", regra_agregacao="Soma de valores nominais.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["mês"],
       regras_comparabilidade=["Não é ESS: é cobrado via CONER, conta própria da energia de reserva."],
       regra_cobertura="Setembro de 2023 até o último mês publicado.", politica_ausencia=_AUSENCIA_JANELA,
       validacoes=["Cabeçalho conferido na chegada (7 colunas; falha fechada)."], limitacoes=[_CCEE_INICIO]),
    _m(id="mercado_pagamento_ess",
       titulo="Pagamento de ESS depois do alívio",
       pergunta="Quanto do ESS apurado foi efetivamente pago pelos consumidores, depois do alívio?",
       definicao="Colunas PAGAMENTO_ENCARGO_ESS e PAGAMENTO_ENCARGO_SE do conjunto ENCARGO_PGTO_MENSAL; recursos de alívio (RESERVA_ALIVIO_ESS) e penalidades em colunas próprias.",
       unidade="R$ nominais", grao_geografico="SIN", grao_temporal="mês", fontes=_ccee("encargo_pgto_mensal") + _IM,
       formula="pagamento = PAGAMENTO_ENCARGO_ESS + PAGAMENTO_ENCARGO_SE", regra_agregacao="Soma de valores nominais.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["mês"],
       regras_comparabilidade=["Pagamento não é competência: o alívio reduz o valor pago."],
       regra_cobertura="Setembro de 2023 até o último mês publicado.", politica_ausencia="Célula vazia é ausência.",
       validacoes=["InfoMercado: total de encargos − alívio = pagamento em agosto e outubro de 2024 (R$ 361,54 e 20,87 milhões; tolerância de R$ 0,06 milhão); em julho de 2026 o InfoMercado implica R$ 2,55 milhões e o conjunto traz R$ 0,00 milhão: divergência publicada."],
       limitacoes=[_CCEE_INICIO]),
    _m(id="mercado_inadimplencia_liquidacao",
       titulo="Inadimplência na liquidação do mercado de curto prazo",
       pergunta="Que parte do valor a liquidar no MCP não foi paga?",
       definicao="Conjunto SUMARIO_MENSAL_LIQUIDACAO: VALOR_INAD ÷ VALOR_TOTAL_LIQ_PRE no mês de apuração; só nos meses em que a liquidar = liquidado + inadimplência.",
       unidade="%", grao_geografico="SIN", grao_temporal="mês", fontes=_ccee("sumario_mensal_liquidacao") + _IM,
       numerador="VALOR_INAD (R$)", denominador="VALOR_TOTAL_LIQ_PRE (R$)", formula="inadimplencia_pct = 100 × VALOR_INAD ÷ VALOR_TOTAL_LIQ_PRE",
       regra_agregacao="Razão de um mês; não é média entre meses.", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["mês"], regras_comparabilidade=["Mês com liquidado e inadimplência publicados como 0 e valor a liquidar positivo é 'liquidação não informada', sem taxa."],
       regra_cobertura="Julho de 2023 até o último mês liquidado.", politica_ausencia="Mês sem os três valores fica sem taxa.",
       validacoes=["A liquidar = liquidado + inadimplência (tolerância de R$ 1).",
                   "Valor a liquidar conferido com o InfoMercado (R$ 2,14 e 5,84 bilhões em agosto e outubro de 2024; R$ 2,13 bilhões em julho de 2026)."],
       limitacoes=["Maio de 2025, março e abril de 2026 vêm com zeros que não fecham a identidade."]),
    _m(id="mercado_resultado_mcp_submercado",
       titulo="Balanço energético e resultado do MCP por submercado",
       pergunta="Quanto foi liquidado no mercado de curto prazo em cada submercado?",
       definicao="Conjunto SUMARIO_MENSAL_COMPRA_VENDA_SUBMERCADO: balanço energético positivo e negativo (MWh) e resultado de venda e compra no MCP (R$), por submercado e mês.",
       unidade="MWh; R$ nominais", grao_geografico="submercado", grao_temporal="mês", fontes=_ccee("sumario_mensal_compra_venda_submercado"),
       formula="valores como publicados", regra_agregacao="Sem agregação além do arredondamento.",
       natureza_fonte="OBSERVADO", natureza_transformacao="OBSERVADO", dimensoes=["mês", "submercado"],
       regras_comparabilidade=[_PLD], regra_cobertura="Maio de 2023 até o último mês contabilizado.", politica_ausencia="Célula vazia é ausência.",
       validacoes=["Cabeçalho conferido com o package_show versionado (falha fechada)."], limitacoes=[_CCEE_INICIO]),
    _m(id="mercado_ess_boletim_mme",
       titulo="Encargos de serviços do sistema no Boletim do MME",
       pergunta="Como o boletim oficial do MME apresenta os encargos e como eles foram revistos entre edições?",
       definicao="Tabela 'Encargos de Serviços de Sistema' de cada edição de 2026 do Boletim Mensal de Monitoramento do Sistema Elétrico (mil R$, fonte declarada CCEE); vale a edição mais recente de cada mês e as revisões entre edições são publicadas.",
       unidade="mil R$ nominais", grao_geografico="SIN", grao_temporal="mês de competência (edição)", fontes=_MME,
       formula="Σ da linha Total nos meses publicados", regra_agregacao="Soma de meses da edição vigente.",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["mês", "tipo", "edição"],
       regras_comparabilidade=["Traço lido como zero só quando a soma do mês fecha com ele."],
       regra_cobertura="Edições de 2026 acessíveis no portal do MME.", politica_ausencia="Mês que não fecha é descartado inteiro.",
       validacoes=["Em cada mês, Σ tipos = Total e Σ parcelas = tipo (tolerância de 2 mil R$)."],
       limitacoes=["Edições anteriores a 2026 não estão acessíveis no portal."]),
]
