"""Métricas do módulo Perdas de energia na distribuição (P055 a P058). A fórmula roda em
pipeline/energia/modulos/perdas.py (com as funções de pipeline/energia/fontes/aneel_perdas.py);
a interface lê o valor calculado e esta definição, nunca refaz a conta."""

_GOLD = "perdas.json"
_PAG = ["/setor-eletrico/perdas"]
_SAMP = ["aneel_samp_balanco"]
_AUSENCIA_ANUAL = ("Soma anual só existe quando a linha está publicada nos 12 meses do ano civil; um mês ausente deixa o "
                   "ano ausente (nunca vira zero nem é completado). Ano corrente é parcial e fica fora de comparações.")
_TECNICA_ESTIMADA = ("A parcela técnica publicada no SAMP é o percentual regulatório da revisão tarifária aplicado à energia "
                     "injetada (estimativa), não medição.")
_QUEBRA_2024 = ("Quebra em 2024: leiaute da REN 1.003/2022; injetada publicada bruta (o denominador passa a ser a energia "
                "implícita no cálculo da fonte) e separação técnica e não técnica publicada para cerca de metade das "
                "distribuidoras.")
_VALIDACAO_BALANCO = ("Identidade do balanço conferida mês a mês: injetada − fornecida − irregular − perdas; o resíduo é "
                      "publicado e classificado (fecha, residuo_pequeno, residuo_relevante, sem_componentes).")
_FISICA = ("Agente-ano com perda total anual negativa ou maior que a injetada recebe alerta e fica fora de agregados e "
           "comparações (o valor da fonte segue no CSV).")

METRICAS = [
    {
        "id": "perdas_totais_energia",
        "titulo": "Perdas totais de energia na distribuição",
        "pergunta": "Quanta energia injetada na rede da distribuidora não chegou a ser entregue como consumo medido?",
        "definicao": "Linha 'Perdas Totais' do SAMP Balanço da ANEEL, valor medido: energia injetada menos energia fornecida medida (cativos, consumo próprio, suprimento, livres, uso por outras distribuidoras) e menos a energia cobrada por procedimento irregular. Soma dos 12 meses do ano civil, convertida de kWh para MWh.",
        "unidade": "MWh",
        "grao_geografico": "distribuidora (CNPJ); agregados nacionais por universo (concessionárias, permissionárias, todas)",
        "grao_temporal": "mês (fonte); ano civil (publicação)",
        "fontes": _SAMP,
        "formula": "perdas_totais(d, ano) = Σ_m perdas_totais_medidas(d, m) ÷ 1.000",
        "regra_agregacao": "Soma simples de volumes do mesmo ano e do mesmo subconjunto de distribuidoras válidas.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano", "universo"],
        "regras_comparabilidade": ["Volume depende do tamanho do mercado: comparar distribuidoras pela taxa, não pelo volume.",
                                   "Mudança societária ou incorporação muda o universo da série (eventos publicados).", _QUEBRA_2024],
        "regra_cobertura": "Agentes com balanço de distribuição no SAMP Balanço de jan/2003 até a última competência publicada.",
        "politica_ausencia": _AUSENCIA_ANUAL,
        "validacoes": [_VALIDACAO_BALANCO, _FISICA, "Parquet e CSV oficiais de 15/09/2026 conferidos por código independente: 549.552 linhas nos dois e as 2.146 somas anuais completas de perdas totais idênticas ao kWh."],
        "limitacoes": ["Valores mensais oscilam com o calendário de leitura; só o ano civil completo é comparado.",
                       "Perda medida difere da faturada (custo de disponibilidade e compensação da MMGD)."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_taxa_total_injetada",
        "titulo": "Taxa de perdas totais sobre a energia injetada",
        "pergunta": "Que fração da energia injetada na rede se perdeu?",
        "definicao": "Perdas totais medidas divididas pela energia injetada de referência do mesmo ano. Energia injetada de referência: a linha publicada no leiaute antigo do SAMP; no leiaute de 2024, a energia implícita no cálculo da própria fonte (fornecida + irregular + perdas), porque a linha publicada passou a ser bruta.",
        "unidade": "% da energia injetada",
        "grao_geografico": "distribuidora (CNPJ); Brasil por universo",
        "grao_temporal": "ano civil",
        "fontes": _SAMP,
        "numerador": "Σ perdas totais medidas do ano (MWh)",
        "denominador": "Σ energia injetada de referência do ano (MWh)",
        "formula": "100 × Σ perdas_totais ÷ Σ injetada_referência",
        "regra_agregacao": "Agregado = 100 × Σ numeradores ÷ Σ denominadores das distribuidoras válidas; nunca média de taxas.",
        "versao_formula": "1",
        "natureza_fonte": "CALCULADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano", "universo"],
        "regras_comparabilidade": [_QUEBRA_2024, "Não comparar ano parcial com ano completo.",
                                   "Variação anual com mudança de escala da injetada acima de 30% fica marcada como provável mudança de universo."],
        "regra_cobertura": "Ano civil com os 12 meses de perdas e de injetada de referência publicados.",
        "politica_ausencia": _AUSENCIA_ANUAL,
        "validacoes": [_VALIDACAO_BALANCO, _FISICA,
                       "Taxa nacional das concessionárias entre 5% e 30% (fora disso a gold não é publicada).",
                       "2024: injetada de referência das concessionárias dentro do intervalo implícito nos números do relatório da ANEEL."],
        "limitacoes": ["Base medida: difere da taxa sobre o mercado faturado usada pela ANEEL até 2024.", _TECNICA_ESTIMADA],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_tecnicas_energia",
        "titulo": "Perdas técnicas (estimativa regulatória publicada)",
        "pergunta": "Quanto das perdas se atribui às características físicas da rede?",
        "definicao": "Linha 'Perdas Técnicas' do SAMP Balanço. " + _TECNICA_ESTIMADA + " Taxa técnica = perdas técnicas ÷ energia injetada de referência.",
        "unidade": "MWh e % da energia injetada",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "ano civil",
        "fontes": _SAMP,
        "numerador": "Σ perdas técnicas do ano (MWh)",
        "denominador": "Σ energia injetada de referência do ano (MWh), só das distribuidoras com a técnica publicada nos 12 meses",
        "formula": "taxa_tecnica = 100 × Σ perdas_tecnicas ÷ Σ injetada_referência",
        "regra_agregacao": "Agregado só sobre o subconjunto com a técnica publicada, com a cobertura (em % da injetada) ao lado.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano"],
        "regras_comparabilidade": [_QUEBRA_2024, "A técnica não mede desempenho: segue o percentual regulatório por construção."],
        "regra_cobertura": "Publicada para a maioria das distribuidoras até 2023; cerca de metade a partir de 2024.",
        "politica_ausencia": _AUSENCIA_ANUAL + " Distribuidora sem a técnica em algum mês não tem técnica nem não técnica no ano.",
        "validacoes": ["Perda técnica idêntica nas bases medida e faturada (conferido no arquivo)."],
        "limitacoes": ["Não se pode concluir que toda perda técnica é evitável nem que é eliminável a custo zero."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_nao_tecnicas_bt",
        "titulo": "Perdas não técnicas sobre o mercado de baixa tensão",
        "pergunta": "Quanto da energia perdida não se explica pela física da rede, em relação ao consumo de baixa tensão?",
        "definicao": "Perdas não técnicas medidas (perdas totais menos técnicas, linha 'Perdas Não-Técnicas' do SAMP) divididas pelo mercado de baixa tensão medido: energia medida entregue em BT a cativos, consumo próprio e livres. É a base que a ANEEL usa para a referência regulatória não técnica (mercado medido desde 2025). Inclui furto, fraude e erros de medição, leitura e faturamento, que a fonte não separa.",
        "unidade": "% do mercado de baixa tensão medido",
        "grao_geografico": "distribuidora (CNPJ); Brasil por universo",
        "grao_temporal": "ano civil",
        "fontes": _SAMP,
        "numerador": "Σ perdas não técnicas medidas do ano (MWh)",
        "denominador": "Σ mercado BT medido do ano (MWh)",
        "formula": "100 × Σ pnt_medidas ÷ Σ mercado_BT_medido",
        "regra_agregacao": "100 × Σ numeradores ÷ Σ denominadores do subconjunto com as duas grandezas nos 12 meses.",
        "versao_formula": "1",
        "natureza_fonte": "CALCULADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano", "universo"],
        "regras_comparabilidade": ["Pode passar de 100% em áreas com perda muito alta (a base é só o mercado BT).",
                                   "Pode ser negativa quando a estimativa técnica supera a perda total medida (pequenas distribuidoras).",
                                   _QUEBRA_2024],
        "regra_cobertura": "Mercado BT por nível de tensão existe a partir de 2010.",
        "politica_ausencia": _AUSENCIA_ANUAL,
        "validacoes": ["Não técnica = total − técnica conferido nas linhas da fonte."],
        "limitacoes": ["Não resumir a furto: a definição da fonte inclui erros de medição e faturamento.",
                       "Não atribuir às famílias de uma área a responsabilidade pelas perdas não técnicas."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_nao_tecnicas_injetada",
        "titulo": "Perdas não técnicas sobre a energia injetada",
        "pergunta": "Que fração da energia injetada corresponde às perdas não técnicas?",
        "definicao": "Perdas não técnicas medidas divididas pela energia injetada de referência. Mesma base da taxa total, o que permite somar técnica e não técnica: taxa técnica + taxa não técnica = taxa total.",
        "unidade": "% da energia injetada",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "ano civil",
        "fontes": _SAMP,
        "numerador": "Σ perdas não técnicas medidas (MWh)",
        "denominador": "Σ energia injetada de referência (MWh)",
        "formula": "100 × Σ pnt_medidas ÷ Σ injetada_referência",
        "regra_agregacao": "100 × Σ numeradores ÷ Σ denominadores.",
        "versao_formula": "1",
        "natureza_fonte": "CALCULADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano"],
        "regras_comparabilidade": ["Só se soma à taxa técnica porque o denominador é o mesmo; nunca somar com a taxa sobre BT."],
        "regra_cobertura": "Como a técnica.",
        "politica_ausencia": _AUSENCIA_ANUAL,
        "validacoes": ["taxa técnica + taxa não técnica = taxa total (arredondamento de 0,01 p.p.)."],
        "limitacoes": [_TECNICA_ESTIMADA],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_residuo_balanco",
        "titulo": "Resíduo do balanço energético",
        "pergunta": "A perda publicada é explicada pelas linhas de energia publicadas?",
        "definicao": "Energia injetada publicada menos energia fornecida medida, energia cobrada por procedimento irregular e perdas totais. Zero quando a conta fecha; diferente de zero mostra o que a fonte não explica. Não é outra perda e não é atribuído a nenhuma causa.",
        "unidade": "MWh e % da energia injetada publicada",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "mês e ano civil",
        "fontes": _SAMP,
        "numerador": "injetada publicada − fornecida − irregular − perdas totais (MWh)",
        "denominador": "injetada publicada (MWh)",
        "formula": "resíduo = I − F − R − P; classe: |resíduo| ≤ 1 kWh por linha (fecha), ≤ 0,1% de I (pequeno), acima (relevante)",
        "regra_agregacao": "Soma dos meses do ano.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês", "ano"],
        "regras_comparabilidade": ["O leiaute de 2024 produz resíduo positivo sistemático nas distribuidoras com muita geração conectada à rede."],
        "regra_cobertura": "Meses com injetada, fornecida medida e perda total publicadas.",
        "politica_ausencia": "Sem as linhas de fornecimento medido o resíduo é ausente e a classe é 'sem_componentes'.",
        "validacoes": ["Representação de cada grandeza escolhida pela concordância com a soma dos níveis de tensão do mês."],
        "limitacoes": ["Tolerância de 0,1% da injetada: abaixo disso a taxa não muda na primeira casa decimal."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_tecnica_regulatoria_implicita",
        "titulo": "Percentual regulatório de perdas técnicas (implícito no SAMP)",
        "pergunta": "Qual percentual técnico a regulação reconhece para a distribuidora em cada período tarifário?",
        "definicao": "Razão entre perdas técnicas e energia injetada publicadas no SAMP quando ela é constante por meses seguidos: é o percentual regulatório aplicado pela fonte. O mês de troca mistura as duas taxas pró-rata dos dias. A resolução homologatória é associada ao trecho quando o início de vigência dela (componentes tarifárias) cai no mês da troca; o dia reconstituído da média pró-rata fica só no CSV, como diagnóstico.",
        "unidade": "% da energia injetada",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "trecho de vigência (meses)",
        "fontes": _SAMP + ["aneel_componentes_tarifarias_b1"],
        "numerador": "perdas técnicas do mês (kWh)",
        "denominador": "energia injetada publicada do mês (kWh)",
        "formula": "pct = round(100 × PT ÷ I, 3); trecho = meses consecutivos com o mesmo pct (mínimo 2)",
        "regra_agregacao": "Não se agrega entre distribuidoras.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "vigência"],
        "regras_comparabilidade": ["É parâmetro regulatório, não perda realizada nem meta de perda zero."],
        "regra_cobertura": "Distribuidoras e períodos em que a fonte aplica percentual fixo (em geral de 2016 a 2023).",
        "politica_ausencia": "Onde a razão varia mês a mês não há trecho: o percentual regulatório fica ausente (não é estimado).",
        "validacoes": ["CEMIG-D: 8,766% de jun/2018 a abr/2023; maio/2018 = 7,959% = média pró-rata com início em 28/05/2018, a vigência da REH 2.396/2018 (o mesmo em maio/2023 com a REH 3.202/2023).",
                        "Conferência de 30/09/2026: em 342 trechos, 78 têm REH no mês da troca; o dia reconstituído coincide com o da REH só nos dois casos da CEMIG-D, por isso não é publicado como vigência."],
        "limitacoes": ["A referência regulatória não técnica não está em base aberta acessível."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_custo_tarifa_b1",
        "titulo": "Custo unitário das perdas na tarifa residencial",
        "pergunta": "Quanto da tarifa residencial remunera perdas de energia, segundo o processo tarifário?",
        "definicao": "Soma das componentes TUSD_PT (perdas técnicas), TUSD_PNT (não técnicas), TUSD_Per_RB_D e TE_Per_RB (perdas na Rede Básica) da tarifa B1 residencial convencional, base econômica, publicadas pela ANEEL por resolução homologatória e vigência; participação = essa soma ÷ (TUSD + TE).",
        "unidade": "R$/MWh nominais, sem tributos; % da tarifa",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "processo tarifário (vigência)",
        "fontes": ["aneel_componentes_tarifarias_b1"],
        "numerador": "TUSD_PT + TUSD_PNT + TUSD_Per_RB_D + TE_Per_RB (R$/MWh)",
        "denominador": "TUSD + TE (R$/MWh)",
        "formula": "participação = 100 × perdas ÷ (TUSD + TE)",
        "regra_agregacao": "Não se agrega entre distribuidoras (tarifas diferentes, mercados diferentes).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "resolução homologatória", "vigência", "base tarifária"],
        "regras_comparabilidade": ["Valores nominais: comparar anos exige cuidado com inflação e preço da energia.",
                                   "É nível regulatório reconhecido, não custo das perdas reais."],
        "regra_cobertura": "Processos com vigência desde 2010 publicados nas componentes tarifárias (arquivos de 2012 a 2026).",
        "politica_ausencia": "Processo sem alguma das seis componentes não tem resumo.",
        "validacoes": ["TUSD igual à soma das componentes TUSD_* e TE igual à soma das TE_* (tolerância de 0,01 R$/MWh, arredondamento da fonte)."],
        "limitacoes": ["Não é o custo total em reais reconhecido no processo (planilhas do processo inacessíveis).",
                       "Não se multiplica pela tarifa cheia nem por mercado para inventar um custo total."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_area_municipios",
        "titulo": "Área de atuação por municípios (vínculos oficiais)",
        "pergunta": "Em quais municípios cada distribuidora atua, segundo a ANEEL?",
        "definicao": "Municípios ligados à distribuidora por algum conjunto elétrico de continuidade do ano (limites de continuidade) presente na relação IndQual Município. Vínculo confirmado quando o cadastro de micro e minigeração distribuída tem ao menos um empreendimento da distribuidora no município.",
        "unidade": "municípios",
        "grao_geografico": "município (código IBGE) × distribuidora (CNPJ)",
        "grao_temporal": "relação vigente do ano",
        "fontes": ["aneel_continuidade_limites", "aneel_indqual_municipio", "aneel_mmgd_municipio"],
        "formula": "vínculo(d, m) ⇔ ∃ conjunto c: CNPJ(c, ano) = d e m ∈ municípios(c)",
        "regra_agregacao": "Contagem de municípios; compartilhado quando mais de uma distribuidora tem vínculo confirmado.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "município", "UF"],
        "regras_comparabilidade": ["Nunca ratear volume ou taxa da distribuidora entre municípios."],
        "regra_cobertura": "Conjuntos com limite de continuidade no ano da relação.",
        "politica_ausencia": "Conjunto sem município na relação IndQual fica listado; município sem distribuidora não recebe cor.",
        "validacoes": ["Código de município conferido na lista oficial do IBGE.", "Vínculo sem MMGD marcado como não confirmado, não removido."],
        "limitacoes": ["Município inteiro mesmo quando atendido só em parte; não é polígono de concessão."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_contexto_renda",
        "titulo": "Renda domiciliar per capita média na área (Censo 2022)",
        "pergunta": "Qual é a renda média dos moradores dos municípios onde a distribuidora atua?",
        "definicao": "Média do rendimento nominal mensal domiciliar per capita dos moradores em domicílios particulares permanentes ocupados (Censo 2022, tabela 10295), ponderada pelo número de moradores de cada município confirmado da área; versão só com municípios exclusivos ao lado.",
        "unidade": "R$ de 2022 por mês",
        "grao_geografico": "conjunto dos municípios da distribuidora",
        "grao_temporal": "2022 (censitário)",
        "fontes": ["ibge_censo2022_municipio"],
        "numerador": "Σ renda média per capita × moradores",
        "denominador": "Σ moradores",
        "formula": "Σ(r_m × n_m) ÷ Σ n_m",
        "regra_agregacao": "Ponderada por moradores; nunca média simples de médias municipais.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora"],
        "regras_comparabilidade": ["Contexto territorial, não explicação de perdas; associação descritiva (Spearman) com n e sem causalidade."],
        "regra_cobertura": "Municípios confirmados com dado do Censo.",
        "politica_ausencia": "Município sem valor do IBGE fica fora do numerador e do denominador; a contagem aparece.",
        "validacoes": ["Soma de moradores e média ponderada conferidas com valores do IBGE em teste."],
        "limitacoes": ["Municípios compartilhados entram inteiros; a cobertura exclusiva mostra o peso deles.",
                       "Perda não técnica não é atribuída às famílias da área."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_taxa_total_acumulada",
        "titulo": "Taxa de perdas totais acumulada no ano aberto",
        "pergunta": "Como estão as perdas no ano corrente, comparadas ao mesmo período do ano anterior?",
        "definicao": "Perdas totais medidas de janeiro até o último mês publicado por ao menos 90% das distribuidoras válidas no ano de referência, divididas pela energia injetada de referência do mesmo recorte; ao lado, o mesmo recorte do ano anterior, sobre as mesmas distribuidoras.",
        "unidade": "% da energia injetada",
        "grao_geografico": "distribuidora (CNPJ); Brasil por universo",
        "grao_temporal": "janeiro a mes_fim do ano aberto",
        "fontes": _SAMP,
        "numerador": "Σ perdas totais medidas de janeiro a mes_fim (MWh)",
        "denominador": "Σ energia injetada de referência de janeiro a mes_fim (MWh)",
        "formula": "100 × Σ perdas_totais[1..mes_fim] ÷ Σ injetada_referência[1..mes_fim]",
        "regra_agregacao": "Razão de somas sobre as distribuidoras completas e sem alerta nos dois recortes (mesmo conjunto nos dois anos).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "universo"],
        "regras_comparabilidade": ["Compara só com o mesmo período do ano anterior; nunca com anos completos.",
                                   "Sazonalidade e calendário de leitura pesam mais em recortes curtos."],
        "regra_cobertura": "Distribuidoras com todos os meses de janeiro a mes_fim nos dois anos.",
        "politica_ausencia": "Mês ausente no recorte deixa a distribuidora fora (comparavel = 0); nada é completado.",
        "validacoes": [_FISICA, "Recorte mes_fim único para todas as distribuidoras."],
        "limitacoes": ["A separação técnica e não técnica quase não é publicada no ano aberto (2026)."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "perdas_associacao_renda",
        "titulo": "Associação entre renda da área e perdas (Spearman)",
        "pergunta": "Distribuidoras cujas áreas têm renda média menor tendem a ter perdas maiores?",
        "definicao": "Correlação de postos de Spearman entre a renda média domiciliar per capita dos municípios confirmados da área (Censo 2022) e a taxa de perdas (não técnicas sobre BT e totais sobre a injetada) das concessionárias no ano do Censo, com o número de pares.",
        "unidade": "coeficiente entre −1 e 1",
        "grao_geografico": "concessionária",
        "grao_temporal": "2022 (ano do Censo)",
        "fontes": _SAMP + ["ibge_censo2022_municipio", "aneel_indqual_municipio", "aneel_continuidade_limites", "aneel_mmgd_municipio"],
        "formula": "ρ = correlação de Pearson entre os postos (empates com posto médio); ausente com menos de 5 pares",
        "regra_agregacao": "Um par por concessionária com ano completo, sem alerta e com território identificado.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["concessionária"],
        "regras_comparabilidade": ["Associação descritiva entre áreas; não é causa nem descreve cada família."],
        "regra_cobertura": "Concessionárias com perdas de 2022 completas e municípios confirmados.",
        "politica_ausencia": "Concessionária sem a taxa ou sem renda fica fora do par; n publicado ao lado.",
        "validacoes": ["Spearman conferido em teste com empates (valores conhecidos)."],
        "limitacoes": ["Municípios compartilhados entram inteiros; renda municipal média esconde a desigualdade interna.",
                       "Não atribui perdas não técnicas às famílias de uma área."],
        "gold": _GOLD, "paginas": _PAG,
    },
]
