"""Métricas do módulo PLD (detalhe): definição única das medidas publicadas em
public/energia/gold/pld_detalhe.json. A fórmula roda em pipeline/energia/modulos/pld_detalhe.py;
a interface só lê o valor calculado.

Convenções comuns: horário de Brasília; PLD em R$/MWh nominais; hora h = intervalo
[h:00, h+1:00). Na hora, "no limite" é igualdade ao centavo (|PLD − limite| ≤ R$ 0,005/MWh,
o PLD e os limites são publicados em centavos); a média diária frente ao teto estrutural usa
R$ 0,01/MWh (erro de arredondamento da média); a separação entre submercados é diferença de
mais de um centavo. Natureza da fonte: o CMO do ONS (DECOMP e DESSEM) é ESTIMADO pela fonte
(resultado de modelo, "Este CMO é estimado pelo modelo DESSEM"); o PLD publicado pela CCEE é
OBSERVADO (preço oficial de liquidação). Métrica que combina os dois herda ESTIMADO.
"""

GOLD = "pld_detalhe.json"
PAGINA = ["/setor-eletrico/pld"]
F_PLD = "ccee_pld_horario"
F_SH = "ons_cmo_semihorario"
F_SEM = "cmo_se"
F_A02 = "ons_cmo_semanal_a02"
F_BAL = "balanco_energia_subsistema_ho"
F_INT = "intercambio_nacional_ho"
F_IPCA = "ibge_ipca_1737"
F_LIM = "regulatorio:limites_pld"

_AUS_PLD = "Hora sem PLD publicado não entra no cálculo nem vira zero; o número de horas usadas acompanha cada valor."
_NAO_CAUSAL = "Estatística descritiva: não identifica causa."


def _m(**kw):
    base = {"gold": GOLD, "paginas": PAGINA, "versao_formula": "1.0"}
    base.update(kw)
    return base


METRICAS = [
    _m(id="pld_cmo_dessem_hora", titulo="CMO do DESSEM na hora",
       pergunta="Qual foi o custo marginal de operação calculado pelo ONS em cada hora?",
       definicao="Média das duas meias horas do CMO semi-horário do DESSEM publicado pelo ONS que começam em h:00 e h:30.",
       unidade="R$/MWh", grao_geografico="subsistema do ONS", grao_temporal="hora",
       fontes=[F_SH], formula="CMO_h = (CMO_{h:00} + CMO_{h:30}) ÷ 2",
       regra_agregacao="média por duração (as duas meias horas têm 30 minutos)",
       natureza_fonte="ESTIMADO", natureza_transformacao="CALCULADO",
       dimensoes=["subsistema", "hora"],
       regras_comparabilidade=["Comparável com o PLD da mesma hora, mas não equivalente: o PLD é calculado pela CCEE e tem limites."],
       regra_cobertura="Só horas com as duas meias horas publicadas.",
       politica_ausencia="Hora com meia hora ausente fica sem valor (não é completada).",
       validacoes=["esquema do CSV (subsistema, grade de 30 minutos, número com ponto decimal)", "sem duplicidade de (subsistema, instante)",
                   "convenção do instante (início da meia hora) conferida contra o PLD"],
       limitacoes=["Resultado de modelo do ONS, não medição.", "O conjunto não identifica deck, versão ou revisão do modelo."]),
    _m(id="pld_cmo_dessem_semana", titulo="CMO médio do DESSEM na semana operativa",
       pergunta="Qual foi o CMO médio do DESSEM na mesma semana do CMO semanal do DECOMP?",
       definicao="Média das 336 meias horas do CMO do DESSEM da semana operativa (sábado a sexta).",
       unidade="R$/MWh", grao_geografico="subsistema do ONS", grao_temporal="semana operativa",
       fontes=[F_SH], formula="DESSEM_semana = Σ CMO_meia ÷ 336", regra_agregacao="média por duração",
       natureza_fonte="ESTIMADO", natureza_transformacao="CALCULADO", dimensoes=["subsistema", "semana operativa"],
       regras_comparabilidade=["Comparado com o CMO semanal do DECOMP e com o PLD da mesma semana, em diferença absoluta; nunca em razão."],
       regra_cobertura="Semana com as 336 meias horas.", politica_ausencia="Semana incompleta fica sem média; a contagem de meias horas é publicada no CSV.",
       validacoes=["contagem de meias horas por semana", "convenção de data do CMO semanal (sexta que encerra a semana) conferida por correlação"],
       limitacoes=["O CMO semanal do DECOMP é um valor da semana inteira, por patamar e em média semanal; a média do DESSEM não é o mesmo produto."]),
    _m(id="pld_pld_semana", titulo="PLD médio da semana operativa",
       pergunta="Qual foi o PLD médio na semana operativa?",
       definicao="Média simples das 168 horas do PLD da semana operativa (sábado a sexta).",
       unidade="R$/MWh", grao_geografico="submercado", grao_temporal="semana operativa", fontes=[F_PLD],
       numerador="Σ PLD_h nas 168 horas", denominador="168", formula="PLD_semana = Σ PLD_h ÷ 168",
       regra_agregacao="média temporal", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["submercado", "semana operativa"],
       regras_comparabilidade=["Média temporal: não é preço ponderado pela carga."],
       regra_cobertura="Semana com as 168 horas.", politica_ausencia=_AUS_PLD,
       validacoes=["168 horas de sábado 00h a sexta 23h", "reconciliação por releitura do arquivo original da CCEE com leitor independente"],
       limitacoes=["Valores nominais."]),
    _m(id="pld_diferenca_pld_cmo", titulo="Diferença entre PLD e CMO no mesmo intervalo",
       pergunta="Quanto o PLD se afastou do CMO publicado pelo ONS no mesmo intervalo?",
       definicao="PLD menos CMO na mesma hora (DESSEM) ou na mesma semana operativa (DECOMP e média do DESSEM), em R$/MWh. Resumida por ano e submercado nas horas com o PLD entre os limites (fora de dias com a média no teto estrutural) e nas horas no piso.",
       unidade="R$/MWh", grao_geografico="submercado e subsistema de mesmo nome", grao_temporal="hora e semana operativa",
       fontes=[F_PLD, F_SH, F_SEM, F_LIM], formula="Δ = PLD − CMO do mesmo intervalo; média, média do módulo e mediana do módulo por ano",
       regra_agregacao="média simples das diferenças horárias", natureza_fonte="ESTIMADO", natureza_transformacao="CALCULADO",
       dimensoes=["submercado", "ano", "situação do PLD frente aos limites"],
       regras_comparabilidade=["Só entre o mesmo intervalo de tempo.", "Diferença absoluta; nenhuma razão ou multiplicador (achado A01)."],
       regra_cobertura="Horas com PLD e CMO do DESSEM na hora.", politica_ausencia="Hora sem um dos dois fica fora e é contada em horas_sem_cmo.",
       validacoes=["situação frente aos limites só quando os atos estão disponíveis"],
       limitacoes=["Um dos termos (o CMO) é estimado por modelo pelo ONS; o PLD é o preço publicado pela CCEE.",
                   "CMO e PLD não são automaticamente equivalentes: modelo, configuração e limites diferem.", _NAO_CAUSAL]),
    _m(id="pld_horas_piso", titulo="Horas com o PLD no piso",
       pergunta="Com que frequência o PLD ficou no limite mínimo?",
       definicao=("Fração das horas do ano em que o PLD foi igual ao mínimo vigente no dia, ao centavo (|PLD − mínimo| ≤ R$ 0,005/MWh), "
                  "segundo os atos anuais da ANEEL. Horas exatamente um centavo acima do piso ficam numa classe à parte."),
       unidade="fração das horas (a ficha de evidência exibe em % das horas)", grao_geografico="submercado", grao_temporal="ano civil (parcial marcado)",
       fontes=[F_PLD, F_LIM], numerador="horas com |PLD − mínimo vigente| ≤ 0,005", denominador="horas com limites vigentes conhecidos",
       formula="frac_piso = horas_piso ÷ horas_com_limite", regra_agregacao="contagem de horas",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["submercado", "ano", "dia (calendário)"],
       regras_comparabilidade=["Cada ano tem o seu piso; frações de anos diferentes comparam regimes diferentes.", "Ano parcial marcado."],
       regra_cobertura="Horas com PLD e com ato vigente no dia.", politica_ausencia="Dia sem ato vigente conta como sem limite e sai do denominador.",
       validacoes=["nenhuma hora abaixo do piso", "sensibilidade com R$ 0,01/MWh na hora e classe à parte para o centavo vizinho",
                   "menor valor observado conferido com o piso do ato (sem substituí-lo)",
                   "limites vigentes de cada dia iguais aos de limites_em do módulo Regulação (mesma regra em outro módulo)",
                   "trecho e valor do ato vigente conferidos no PDF do ato", "recontagem por releitura do arquivo original da CCEE"],
       limitacoes=["O menor valor observado nunca substitui o piso regulatório.",
                   "Depende dos atos integrados pelo módulo Regulação; três atos (2021 e 2023) têm os valores lidos em voto ou nota técnica do processo, não no texto do ato."]),
    _m(id="pld_horas_teto_horario", titulo="Horas com o PLD no teto horário",
       pergunta="Com que frequência o PLD encostou no máximo horário?",
       definicao="Fração das horas do ano com o PLD igual ao máximo horário vigente ao centavo (|PLD − máximo horário| ≤ R$ 0,005/MWh).",
       unidade="fração das horas", grao_geografico="submercado", grao_temporal="ano civil",
       fontes=[F_PLD, F_LIM], numerador="horas no teto horário", denominador="horas com limites vigentes conhecidos",
       formula="frac_teto = horas_teto ÷ horas_com_limite", regra_agregacao="contagem de horas",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["submercado", "ano"],
       regras_comparabilidade=["Cada ano tem o seu teto."], regra_cobertura="Horas com ato vigente.",
       politica_ausencia="Dia sem ato vigente sai do denominador.", validacoes=["nenhuma hora acima do teto horário"],
       limitacoes=["Depende dos atos integrados pelo módulo Regulação."]),
    _m(id="pld_dias_teto_estrutural", titulo="Dias com a média do PLD no teto estrutural",
       pergunta="Em quantos dias a média diária do PLD ficou no máximo estrutural?",
       definicao="Dias com |média das 24 horas − máximo estrutural vigente| ≤ R$ 0,01/MWh.",
       unidade="dias", grao_geografico="submercado", grao_temporal="dia; total por ano",
       fontes=[F_PLD, F_LIM], formula="|Σ PLD_h ÷ 24 − máximo estrutural| ≤ 0,01", regra_agregacao="contagem de dias completos",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["submercado", "ano", "dia"],
       regras_comparabilidade=["A média de 24 valores arredondados ao centavo erra no máximo R$ 0,005/MWh."],
       regra_cobertura="Dias com as 24 horas.", politica_ausencia="Dia incompleto não recebe média.",
       validacoes=["nenhum dia com média acima do teto estrutural"],
       limitacoes=["A verificação é sobre a média diária publicada; a regra de aplicação está nos atos da ANEEL."]),
    _m(id="pld_empates_piso", titulo="Horas com os quatro submercados no piso",
       pergunta="Quando o piso vale para todo o sistema ao mesmo tempo?",
       definicao="Número de horas do ano em que 0, 1, 2, 3 ou 4 submercados estavam no piso; empate no piso = os quatro no piso.",
       unidade="horas", grao_geografico="sistema (quatro submercados)", grao_temporal="ano",
       fontes=[F_PLD, F_LIM], formula="k_h = nº de submercados com |PLD − mínimo| ≤ 0,005 na hora h", regra_agregacao="contagem",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["ano", "quantidade de submercados no piso"],
       regras_comparabilidade=["Horas empatadas no piso têm diferença de preço zero por construção dos limites."],
       regra_cobertura="Horas com os quatro submercados.", politica_ausencia=_AUS_PLD, validacoes=["soma das classes igual às horas do ano"],
       limitacoes=["Depende dos atos integrados pelo módulo Regulação."]),
    _m(id="pld_media_mensal_temporal", titulo="PLD médio mensal (média temporal)",
       pergunta="Qual foi o PLD médio do mês?",
       definicao="Média simples das horas do mês com PLD publicado.",
       unidade="R$/MWh", grao_geografico="submercado", grao_temporal="mês (parcial marcado)", fontes=[F_PLD],
       numerador="Σ PLD_h do mês", denominador="horas do mês com PLD", formula="Σ PLD_h ÷ n", regra_agregacao="média temporal",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["submercado", "mês"],
       regras_comparabilidade=["Não é preço ponderado pelo consumo.", "Mês parcial não compete com mês completo sem aviso."],
       regra_cobertura="Todas as horas publicadas do mês.", politica_ausencia=_AUS_PLD, validacoes=["horas por mês publicadas"],
       limitacoes=["Valores nominais."]),
    _m(id="pld_media_mensal_ponderada_carga", titulo="PLD médio mensal ponderado pela carga",
       pergunta="Qual foi o PLD médio do mês pesando cada hora pela carga do subsistema?",
       definicao=("Soma do PLD vezes a carga verificada do subsistema na mesma hora, dividida pela soma da carga, nas horas com carga "
                  "publicada e positiva."),
       unidade="R$/MWh", grao_geografico="submercado (peso: subsistema de mesmo nome)", grao_temporal="mês",
       fontes=[F_PLD, F_BAL], numerador="Σ PLD_h × carga_h (carga_h > 0)", denominador="Σ carga_h (carga_h > 0)",
       formula="Σ PLD_h × carga_h ÷ Σ carga_h nas horas com carga_h > 0",
       regra_agregacao="média ponderada pela energia (MWmed numa hora = MWh)", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["submercado", "mês"],
       regras_comparabilidade=["Só é comparada com a média temporal quando as duas usam as mesmas horas (campo mesmas_horas)."],
       regra_cobertura="Horas com PLD e carga positiva.",
       politica_ausencia=("Hora sem carga fica fora da ponderada; hora com carga ≤ 0 (valor fisicamente impossível) também sai do peso e é "
                          "listada como ressalva; mesmas_horas indica a diferença de cobertura."),
       validacoes=["controle físico: carga > 0 em toda hora usada como peso", "numerador e denominador publicados na evidência",
                   "magnitude e alcance das revisões da carga por mês, com o efeito na ponderada",
                   "reconciliação por releitura dos arquivos originais da CCEE e do ONS"],
       limitacoes=["Carga do subsistema do ONS, não consumo contabilizado na CCEE; correspondência subsistema e submercado pelo nome.",
                   "A carga é revista pelo ONS depois de publicada; a ponderada dos meses recentes pode mudar."]),
    _m(id="pld_media_mensal_real", titulo="PLD médio mensal em moeda constante",
       pergunta="Quanto valeria o PLD médio de cada mês em reais de hoje?",
       definicao="Média temporal do mês multiplicada pelo IPCA do mês-base e dividida pelo IPCA do mês.",
       unidade="R$/MWh do mês-base", grao_geografico="submercado", grao_temporal="mês", fontes=[F_PLD, F_IPCA],
       formula="real = temporal × IPCA(base) ÷ IPCA(mês)", regra_agregacao="deflação mensal",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["submercado", "mês"],
       regras_comparabilidade=["Perspectiva adicional; o valor nominal é o dado principal."],
       regra_cobertura="Meses com IPCA publicado.", politica_ausencia="Mês sem índice fica sem valor real.",
       validacoes=["mês-base = último mês do IPCA não posterior ao dia de referência"],
       limitacoes=["O IPCA mede preços ao consumidor, não custos de energia."]),
    _m(id="pld_percentil_sazonal", titulo="Posição sazonal do PLD",
       pergunta="O preço está alto para esta época do ano?",
       definicao="Percentil da média diária do dia de referência na distribuição das médias diárias do mesmo mês (e da mesma semana ISO) nos anos anteriores; quantis P10 a P90 por mês.",
       unidade="percentil (0 a 100); R$/MWh nos quantis", grao_geografico="submercado", grao_temporal="dia; mês do ano",
       fontes=[F_PLD], formula="percentil = 100 × (menores + 0,5 × iguais) ÷ n; quantis tipo 7",
       regra_agregacao="distribuição empírica dos dias completos", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["submercado", "mês do ano", "semana ISO"],
       regras_comparabilidade=["Anos anteriores têm limites diferentes; ver a distribuição por regime.", "n publicado ao lado."],
       regra_cobertura="Dias completos de anos anteriores ao ano de referência.", politica_ausencia="Dia incompleto não entra.",
       validacoes=["empates contados pelo rank médio"], limitacoes=["Série horária desde 2021: no máximo cinco anos anteriores."]),
    _m(id="pld_quantis_regime", titulo="Distribuição do PLD por regime de limites",
       pergunta="Como o PLD se distribuiu em cada regime anual de limites?",
       definicao="Quantis P10 a P90 dos valores horários de cada ano, com os limites vigentes e as frações no piso e no teto.",
       unidade="R$/MWh", grao_geografico="submercado", grao_temporal="ano (regime)", fontes=[F_PLD, F_LIM],
       formula="quantis tipo 7 dos valores horários", regra_agregacao="distribuição horária",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["submercado", "ano"],
       regras_comparabilidade=["Ano parcial marcado."], regra_cobertura="Horas publicadas.", politica_ausencia=_AUS_PLD,
       validacoes=["limites do regime listados com o ato"], limitacoes=["Valores nominais."]),
    _m(id="pld_perfil_hora_mes", titulo="Perfil hora a hora por mês",
       pergunta="Em que horas do dia o PLD costuma ser mais alto em cada mês?",
       definicao=("Média do PLD em cada hora do dia (0 a 23) dentro de cada um dos últimos 12 meses; o detalhe hora × dia dos últimos "
                  "90 dias vai em arquivo próprio (pld_hora_dia.json)."),
       unidade="R$/MWh", grao_geografico="submercado", grao_temporal="hora do dia × mês", fontes=[F_PLD],
       formula="média de PLD_h com hora do dia = k no mês m", regra_agregacao="média temporal",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["submercado", "mês", "hora do dia"],
       regras_comparabilidade=["Mês parcial marcado."], regra_cobertura="Horas publicadas.", politica_ausencia=_AUS_PLD,
       validacoes=["24 colunas por mês"], limitacoes=[_NAO_CAUSAL]),
    _m(id="pld_amplitude_horaria", titulo="Amplitude horária entre submercados",
       pergunta="Quanto o maior PLD se afastou do menor na mesma hora?",
       definicao="Maior PLD menos menor PLD entre os quatro submercados na mesma hora; resumida por período.",
       unidade="R$/MWh", grao_geografico="sistema", grao_temporal="hora; resumo por ano, 12 meses e 30 dias",
       fontes=[F_PLD], formula="amplitude_h = max_s PLD_h(s) − min_s PLD_h(s)", regra_agregacao="média, quantis e máximo das horas",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["período", "hora"],
       regras_comparabilidade=["Sempre na mesma hora e na mesma publicação da CCEE."], regra_cobertura="Horas com os quatro submercados.",
       politica_ausencia=_AUS_PLD, validacoes=["amplitude ≥ 0"], limitacoes=[_NAO_CAUSAL]),
    _m(id="pld_separacao_par", titulo="Frequência de separação de preços por par",
       pergunta="Com que frequência dois submercados tiveram preços diferentes?",
       definicao="Fração das horas em que |PLD_A − PLD_B| > R$ 0,01/MWh; com contagens acima de R$ 1 e R$ 10 como sensibilidade.",
       unidade="fração das horas (a ficha de evidência exibe em % das horas)", grao_geografico="par de submercados", grao_temporal="período", fontes=[F_PLD],
       numerador="horas separadas", denominador="horas com os quatro submercados", formula="horas com |Δ| > 0,01 ÷ horas",
       regra_agregacao="contagem de horas", natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO",
       dimensoes=["par", "período", "hora do dia"],
       regras_comparabilidade=["Limiar diferente do usado em pld.json (R$ 1,00/MWh); cada medida declara o seu."],
       regra_cobertura="Horas com os quatro submercados.", politica_ausencia=_AUS_PLD,
       validacoes=["matriz 12 meses reconciliada com a tabela por par", "recontagem pelas diferenças arredondadas ao centavo"], limitacoes=[_NAO_CAUSAL]),
    _m(id="pld_diferenca_media_par", titulo="Diferença média entre submercados",
       pergunta="Em média, quanto um submercado ficou acima ou abaixo de outro?",
       definicao="Média de PLD_A − PLD_B nas mesmas horas; matriz para os últimos 12 meses.",
       unidade="R$/MWh", grao_geografico="par ordenado de submercados", grao_temporal="período", fontes=[F_PLD],
       formula="média de (PLD_A − PLD_B)", regra_agregacao="média temporal das diferenças",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["par", "período"],
       regras_comparabilidade=["Matriz antissimétrica: dif(A,B) = −dif(B,A)."], regra_cobertura="Horas com os quatro submercados.",
       politica_ausencia=_AUS_PLD, validacoes=["antissimetria da matriz"], limitacoes=[_NAO_CAUSAL]),
    _m(id="pld_sentido_fluxo_separacao", titulo="Sentido do fluxo nas horas de preços separados",
       pergunta="Quando os preços se separam, para que lado a energia está fluindo na fronteira?",
       definicao="Nas horas com preços separados entre as pontas de uma fronteira monitorada pelo ONS, contagem das horas em que o fluxo verificado ia do submercado de menor para o de maior preço, no sentido oposto ou era nulo (até 1 MWmed).",
       unidade="horas; fração das horas separadas", grao_geografico="fronteira (N e NE, N e SE/CO, NE e SE/CO, S e SE/CO)",
       grao_temporal="período", fontes=[F_PLD, F_INT], numerador="horas do menor para o maior preço", denominador="horas separadas com fluxo",
       formula="sentido = sinal do fluxo na orientação canônica comparado com o lado de menor preço", regra_agregacao="contagem",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["fronteira", "período"],
       regras_comparabilidade=["Mesma hora; fluxo publicado até a última hora do balanço de intercâmbio."],
       regra_cobertura="Horas com PLD nas duas pontas e fluxo publicado.", politica_ausencia="Hora sem fluxo fica fora.",
       validacoes=["classes somam as horas com fluxo"],
       limitacoes=["Limites de intercâmbio não integrados: nenhuma hora é classificada como congestionada.", _NAO_CAUSAL]),
    _m(id="pld_sequencia_zero_cmo_semanal", titulo="Sequência de CMO semanal igual a zero",
       pergunta="Os zeros do CMO semanal existem no arquivo original do ONS?",
       definicao="Semanas operativas consecutivas com CMO semanal exatamente zero, e conferência no CSV e no Parquet originais.",
       unidade="semanas", grao_geografico="subsistema", grao_temporal="semana operativa", fontes=[F_SEM, F_A02],
       formula="semanas consecutivas (passo de 7 dias) com média semanal = 0; mínimo de 4", regra_agregacao="contagem",
       natureza_fonte="ESTIMADO", natureza_transformacao="CALCULADO", dimensoes=["subsistema"],
       regras_comparabilidade=["Zero é valor publicado; ausência interrompe a sequência."], regra_cobertura="Todos os arquivos anuais.",
       politica_ausencia="Semana ausente interrompe a sequência.",
       validacoes=["CSV contra Parquet célula a célula", "silver principal contra releitura independente"],
       limitacoes=["O ONS não informa a razão dos zeros."]),
    _m(id="pld_folga_lat1d", titulo="Folga da hipótese LAT1D para o PLD",
       pergunta="A regra de defasagem dos backtests antecipa informação do PLD?",
       definicao="Horas entre a primeira captura completa de um dia do PLD e o instante em que LAT1D permite usar aquele dia (D+2 às 00h de Brasília).",
       unidade="horas", grao_geografico="sistema", grao_temporal="dia", fontes=[F_PLD],
       formula="folga = (início do dia D + 2 dias) − primeira captura completa", regra_agregacao="mínimo entre os dias observados",
       natureza_fonte="OBSERVADO", natureza_transformacao="CALCULADO", dimensoes=["dia"],
       regras_comparabilidade=["Só dias com captura direta; a captura versionada não informa publicação."],
       regra_cobertura="Dias com captura direta.", politica_ausencia="Sem captura direta, sem folga.",
       validacoes=["primeira captura calculada da vintage mais antiga que contém a hora"],
       limitacoes=["Primeira captura não é publicação; a CCEE não informa a data de publicação."]),
]
