"""Métricas do módulo Qualidade do serviço de distribuição (P051 a P054). A fórmula roda
em pipeline/energia/modulos/qualidade.py; a interface lê o valor calculado e esta definição."""

_GOLD = "qualidade.json"
_PAG = ["/setor-eletrico/qualidade"]
_CONT = ["aneel_continuidade"]
_UNIDADE_DEC = "horas e centésimos de hora por unidade consumidora (10,50 h = 10 h 30 min)"
_UNIDADE_FEC = "interrupções e centésimos de interrupção por unidade consumidora"
_AUSENCIA_CONT = ("Conjunto sem valor ou sem número de UCs no mês fica fora do numerador e do denominador daquele mês "
                  "(nunca vira zero); ano com menos de 12 meses não tem valor anual; mês nacional em que as UCs com DEC "
                  "ficam abaixo de 99% do máximo das UCs com NumCon nos 12 meses anteriores fica marcado como incompleto "
                  "(UCs e não número de conjuntos: redefinições de conjuntos mudam a contagem sem mudar o universo); "
                  "distribuidora-mês com NumCon implausível fica fora do Brasil e, com mais de um conjunto, sem DEC e FEC.")
_LIM_MEDIA = "Média por unidade consumidora: não descreve o tempo sem energia de cada pessoa nem de cada município."
_EXPURGOS = ("O apurado exclui interrupções em situação de emergência, dia crítico, de origem externa e por ação do ONS; "
             "elas aparecem nas parcelas.")

METRICAS = [
    {
        "id": "qualidade_dec_conjunto",
        "titulo": "DEC do conjunto de unidades consumidoras",
        "pergunta": "Por quanto tempo, em média, cada unidade consumidora do conjunto ficou sem energia?",
        "definicao": "Duração Equivalente de Interrupção por Unidade Consumidora apurada pela distribuidora para o conjunto (PRODIST, Módulo 8): soma das durações das interrupções de mais de 3 minutos de cada UC dividida pelo número de UCs. Valor mensal publicado pela ANEEL; o anual é a soma dos 12 meses. " + _EXPURGOS,
        "unidade": _UNIDADE_DEC,
        "grao_geografico": "conjunto de unidades consumidoras (IdeConjUndConsumidoras)",
        "grao_temporal": "mês; ano civil (soma dos meses)",
        "fontes": _CONT,
        "formula": "DEC(c, ano) = Σ_m DEC(c, m), só com os 12 meses publicados; soma em centésimos exatos (cada mês é publicado com duas casas)",
        "regra_agregacao": "Anual = soma dos meses do conjunto, arredondada ao centésimo para tirar o resíduo do ponto flutuante (a soma de valores com duas casas tem duas casas). Não se faz média simples entre conjuntos: agregados usam qualidade_dec_distribuidora.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["conjunto", "distribuidora (CNPJ)", "mês", "ano", "parcela"],
        "regras_comparabilidade": ["Comparar com o limite do mesmo conjunto e do mesmo ano.",
                                   "Ano parcial não é comparado com ano completo."],
        "regra_cobertura": "Conjuntos publicados nos Parquets de continuidade de 2000 em diante (2000 a 2009 sem as parcelas atuais).",
        "politica_ausencia": _AUSENCIA_CONT,
        "validacoes": ["Chave (CNPJ, conjunto, ano, mês, sigla) única; duplicata com valor diferente é contada.",
                       "Desde 2022, DEC = DECIP + DECIND em todos os conjunto-meses (tolerância 0,01 h de arredondamento).",
                       "Teste relê o Parquet por outro código e confere valores concretos."],
        "limitacoes": [_LIM_MEDIA, "Apurado e enviado pela distribuidora; sujeito a revisão e fiscalização da ANEEL."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_fec_conjunto",
        "titulo": "FEC do conjunto de unidades consumidoras",
        "pergunta": "Quantas vezes, em média, cada unidade consumidora do conjunto ficou sem energia?",
        "definicao": "Frequência Equivalente de Interrupção por Unidade Consumidora: número de interrupções de mais de 3 minutos de cada UC somado e dividido pelo número de UCs do conjunto. Valor mensal; anual = soma dos meses. " + _EXPURGOS,
        "unidade": _UNIDADE_FEC,
        "grao_geografico": "conjunto de unidades consumidoras",
        "grao_temporal": "mês; ano civil",
        "fontes": _CONT,
        "formula": "FEC(c, ano) = Σ_m FEC(c, m), só com os 12 meses publicados",
        "regra_agregacao": "Como o DEC do conjunto.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["conjunto", "distribuidora (CNPJ)", "mês", "ano", "parcela"],
        "regras_comparabilidade": ["Comparar com o limite de FEC do mesmo conjunto e ano."],
        "regra_cobertura": "Conjuntos publicados de 2000 em diante.",
        "politica_ausencia": _AUSENCIA_CONT,
        "validacoes": ["Desde 2022, FEC = FECIP + FECIND em todos os conjunto-meses (tolerância 0,01)."],
        "limitacoes": [_LIM_MEDIA],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_dec_distribuidora",
        "titulo": "DEC da distribuidora e do Brasil",
        "pergunta": "Por quanto tempo, em média, os consumidores da distribuidora (ou do país) ficaram sem energia no ano?",
        "definicao": "Média mensal do DEC dos conjuntos ponderada pelo número de unidades consumidoras de cada conjunto no mês, somada nos 12 meses. É o DEC da união dos conjuntos (Σ DIC ÷ UCs), a regra usada pela ANEEL no DGC do ranking da continuidade.",
        "unidade": _UNIDADE_DEC,
        "grao_geografico": "distribuidora (CNPJ de 14 dígitos) e Brasil",
        "grao_temporal": "mês e ano civil",
        "fontes": _CONT,
        "formula": "DEC(g, m) = Σ_c DEC(c, m) × UC(c, m) ÷ Σ_c UC(c, m); DEC(g, ano) = Σ_m DEC(g, m)",
        "numerador": "Σ_c DEC(c, m) × UC(c, m), em horas × UC",
        "denominador": "Σ_c UC(c, m) dos conjuntos com DEC e número de UCs no mês",
        "regra_agregacao": "Ponderação por UCs no mês; soma dos meses no ano. Nunca média simples de conjuntos ou de distribuidoras.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês", "ano", "parcela"],
        "regras_comparabilidade": ["Comparar com o limite agregado do mesmo ano.",
                                   "Ano corrente só contra os mesmos meses do ano anterior, e só com os meses nacionais completos nos dois anos.",
                                   "Comparar o Brasil com o número divulgado pela ANEEL exige o mesmo universo (concessionárias).",
                                   "Ano com quebra de perímetro da distribuidora não é comparável com o anterior sem a ressalva.",
                                   "2010 a 2021: parte dos conjuntos incluía as parcelas externas XN e XP no apurado (identidade publicada por ano; em 2021, todos os 1.482 conjunto-meses divergentes têm DEC = IP + IND + XN + XP).",
                                   "2000 a 2009: outra desagregação e outros critérios de expurgo na fonte; comparação de nível com ressalva."],
        "regra_cobertura": "Distribuidoras com conjuntos no Parquet de continuidade; cobertura mensal (UCs com DEC ÷ UCs com número de UCs) publicada.",
        "politica_ausencia": _AUSENCIA_CONT,
        "validacoes": ["Reconciliação: DGC calculado com esta regra contra o DGC publicado pela ANEEL no ranking (tolerância 0,01, a precisão publicada).",
                       "Reconciliação externa do Brasil: DEC e FEC só das concessionárias contra o número da notícia anual da ANEEL de 2023 a 2025 (tolerância 0,005, a precisão divulgada).",
                       "Identidade executada em cada construção: Brasil refeito a partir das distribuidoras (Σ DEC × UC ÷ Σ UC) = agregado direto dos conjuntos calculado na importação (tolerância 1e-6); reprovação derruba a publicação.",
                       "Controle de NumCon por distribuidora e mês: média de até 1 UC por conjunto, ou queda ou pico isolado de mais da metade contra os meses vizinhos, tira o mês do Brasil e, com mais de um conjunto, do DEC e do FEC da distribuidora (ressalva em validacao).",
                       "Quebra de perímetro (incorporação ou cessão de área) detectada por variação de mais de 10% nas UCs com continuidade territorial com outra distribuidora que perde UCs no mesmo ano; marcada na série."],
        "limitacoes": [_LIM_MEDIA, "Distribuidora sem conjuntos no conjunto de dados (algumas permissionárias pequenas) não aparece.",
                       "O Brasil publicado cobre todas as distribuidoras, inclusive permissionárias; o número divulgado pela ANEEL cobre só as concessionárias e vai em dec_concessionarias (só a partir de 2019, porque distribuidoras encerradas antes não têm classificação publicada nas manifestações nem no IASC)."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_fec_distribuidora",
        "titulo": "FEC da distribuidora e do Brasil",
        "pergunta": "Quantas vezes, em média, os consumidores da distribuidora (ou do país) ficaram sem energia no ano?",
        "definicao": "Média mensal do FEC dos conjuntos ponderada pelo número de UCs de cada conjunto no mês, somada nos 12 meses.",
        "unidade": _UNIDADE_FEC,
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "mês e ano civil",
        "fontes": _CONT,
        "formula": "FEC(g, m) = Σ_c FEC(c, m) × UC(c, m) ÷ Σ_c UC(c, m); FEC(g, ano) = Σ_m FEC(g, m)",
        "numerador": "Σ_c FEC(c, m) × UC(c, m)",
        "denominador": "Σ_c UC(c, m) dos conjuntos com FEC no mês",
        "regra_agregacao": "Como o DEC da distribuidora.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês", "ano", "parcela"],
        "regras_comparabilidade": ["Como o DEC da distribuidora."],
        "regra_cobertura": "Como o DEC da distribuidora.",
        "politica_ausencia": _AUSENCIA_CONT,
        "validacoes": ["Reconciliação com o DGC publicado (inclui a razão de FEC)."],
        "limitacoes": [_LIM_MEDIA],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_parcelas",
        "titulo": "Parcelas do DEC e do FEC por origem e expurgo",
        "pergunta": "Quanto do tempo sem energia foi expurgado do apurado e por quê?",
        "definicao": "Parcelas publicadas pela ANEEL: interna programada (IP) e não programada não expurgável (IND), que formam o apurado; situação de emergência (INE); dia crítico (INC, IPC); origem externa (XN, XP, XNC, XPC); racionamento ou alívio de carga pelo ONS (INO). O total de todas as parcelas é o DEC de todas as origens publicadas.",
        "unidade": _UNIDADE_DEC + "; " + _UNIDADE_FEC,
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "ano civil",
        "fontes": _CONT,
        "formula": "P(g, ano) = Σ_m [Σ_c P(c, m) × UC(c, m) ÷ Σ_c UC(c, m)], só conjuntos que informaram a parcela no mês",
        "numerador": "Σ_c P(c, m) × UC(c, m)",
        "denominador": "Σ_c UC(c, m) dos conjuntos que informaram a parcela",
        "regra_agregacao": "Ponderação por UCs no mês, soma no ano; a cobertura da parcela (fração das UC-mês com a parcela informada) é guardada no silver.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano", "grupo de parcela"],
        "regras_comparabilidade": ["Desde 2022 as parcelas externas em dia crítico (XNC, XPC) deixaram de ser informadas pela maioria dos conjuntos: o grupo externa antes e depois de 2022 não é homogêneo."],
        "regra_cobertura": "Conjuntos com as parcelas IP e IND informadas entram no total.",
        "politica_ausencia": "Parcela não informada não é zero: fica fora do numerador e do denominador daquela parcela.",
        "validacoes": ["Soma dos grupos = total de todas as parcelas publicadas.", "Apurado = IP + IND desde 2022."],
        "limitacoes": ["Interrupções de menos de 3 minutos e as de responsabilidade do consumidor não são publicadas em nenhuma parcela."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_limite_e_razao",
        "titulo": "Limite anual e distância ao limite (razão apurado ÷ limite)",
        "pergunta": "O serviço cumpriu o padrão regulatório no ano?",
        "definicao": "Limite anual de DEC e FEC fixado pela ANEEL para cada conjunto e ano. Para a distribuidora e o Brasil, média dos limites dos conjuntos ponderada pelas UCs médias do ano. Razão = apurado anual ÷ limite do mesmo ano; acima de 1 = transgressão.",
        "unidade": "horas, interrupções e razão adimensional",
        "grao_geografico": "conjunto, distribuidora e Brasil",
        "grao_temporal": "ano civil (vigência do limite)",
        "fontes": _CONT,
        "formula": "L(g, ano) = Σ_c L(c, ano) × UCmédia(c, ano) ÷ Σ_c UCmédia(c, ano); razão = DEC(g, ano) ÷ L(g, ano)",
        "numerador": "DEC ou FEC apurado no ano",
        "denominador": "limite do mesmo ano e do mesmo universo de conjuntos",
        "regra_agregacao": "Limite ponderado pelas UCs; razão calculada depois da agregação (nunca média de razões de conjuntos).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["conjunto", "distribuidora", "ano"],
        "regras_comparabilidade": ["Realizado e limite sempre do mesmo ano e da mesma cobertura.", "Conjunto sem limite no ano fica fora da razão."],
        "regra_cobertura": "Conjuntos com 12 meses e limite publicado no ano; cobertura do limite (fração de UCs) publicada por distribuidora.",
        "politica_ausencia": "Sem limite publicado para o conjunto e ano: razão ausente; distribuidora em carência de contrato novo fica sem razão.",
        "validacoes": ["DGC = (razão DEC + razão FEC) ÷ 2 reconciliado com o ranking da ANEEL de 2021 em diante."],
        "limitacoes": ["A distribuição dos conjuntos (quantis e caudas) é publicada ao lado da média para não esconder conjuntos muito acima do limite."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_pct_conjuntos_acima",
        "titulo": "Conjuntos acima do limite de DEC",
        "pergunta": "Quantos conjuntos, e quantas unidades consumidoras, ficaram acima do limite de DEC no ano?",
        "definicao": "Número e percentual de conjuntos com 12 meses publicados e limite de DEC no ano cujo DEC anual é maior que o limite; também a fração das UCs (médias do ano) nesses conjuntos.",
        "unidade": "% dos conjuntos e % das UCs",
        "grao_geografico": "Brasil",
        "grao_temporal": "ano civil",
        "fontes": _CONT,
        "formula": "100 × #(DEC(c, ano) > L(c, ano)) ÷ #(conjuntos com limite)",
        "numerador": "conjuntos com DEC anual acima do limite",
        "denominador": "conjuntos com 12 meses e limite",
        "regra_agregacao": "Contagem simples de conjuntos; versão ponderada por UCs publicada ao lado.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["ano"],
        "regras_comparabilidade": ["Conjuntos têm tamanhos muito diferentes: a contagem e a fração de UCs respondem perguntas diferentes."],
        "regra_cobertura": "Conjuntos com 12 meses e limite de DEC publicado no ano.",
        "politica_ausencia": "Sem limite ou com menos de 12 meses: fora do denominador.",
        "validacoes": ["Comparação estrita em centésimos inteiros (DEC anual e limite como a ANEEL publica, com duas casas): igual ao limite não conta como acima.",
                       "Recontagem independente nas linhas do CSV por década em cada construção, com o resultado na evidência."],
        "limitacoes": ["Estar acima do limite coletivo não implica que cada UC do conjunto tenha recebido compensação."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_compensacoes",
        "titulo": "Compensações pagas por violação dos limites individuais de continuidade",
        "pergunta": "Quanto as distribuidoras pagaram em compensações por interrupções acima dos limites individuais?",
        "definicao": "Soma dos valores pagos e das quantidades de compensação publicadas pela ANEEL por conjunto, tipo (mensal, trimestral, anual, DICRI, DISE), tensão e competência, com unidades consumidoras (UC) e unidades geradoras (UG) separadas; o total de UC é o universo do número que a ANEEL divulga.",
        "unidade": "R$ nominais; ocorrências de compensação",
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "competência mensal (trimestre e ano para os tipos trimestral e anual)",
        "fontes": _CONT,
        "formula": "valor(g, competência) = Σ_c Σ_tensão valor pago(c, tensão, tipo, competência)",
        "numerador": "valor pago (R$) ou quantidade",
        "regra_agregacao": "Soma simples (grandezas aditivas); valor por UC = valor anual ÷ UCs médias do ano, só como normalização.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "competência", "tipo", "unidade consumidora ou geradora", "tensão"],
        "regras_comparabilidade": ["Reais correntes, sem correção pela inflação.",
                                   "Desde 2022 (mudança do PRODIST, REN 956/2021) as compensações trimestrais e anuais de unidades consumidoras não são publicadas (ausência, não zero); as de unidades geradoras vêm com valor zero. DISE só desde 2026.",
                                   "O total divulgado pela ANEEL é só de unidades consumidoras: comparar com valor_uc, não com o total que inclui unidades geradoras.",
                                   "Mês ou ano sem todas as distribuidoras fica marcado como incompleto."],
        "regra_cobertura": "Compensações publicadas desde 2011.",
        "politica_ausencia": "Distribuidora sem linha na competência fica sem valor; zero só quando a fonte publica zero.",
        "validacoes": ["Sigla fora do padrão PG/QT de continuidade é contada e não somada.", "Soma relida do Parquet por outro código no teste.",
                       "Total de UC conferido com o total da notícia anual da ANEEL (tolerância R$ 0,5 milhão e 50 mil compensações, a precisão divulgada): 2024 dentro; 2023 e 2025 fora, sem explicação verificada (ressalva na evidência)."],
        "limitacoes": ["Quantidade é de ocorrências, não de consumidores distintos.",
                       "A fonte não informa a data do crédito, só a competência.",
                       "O crédito individual não pode ser estimado a partir do DEC ou FEC do conjunto."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_iasc",
        "titulo": "Índice ANEEL de Satisfação do Consumidor (IASC)",
        "pergunta": "Quão satisfeitos os consumidores residenciais dizem estar com a distribuidora?",
        "definicao": "Índice de 0 a 100 estimado pela ANEEL a partir de pesquisa amostral anual com consumidores residenciais de cada distribuidora (construto de satisfação), publicado com a ordem na categoria e com as contagens de entrevistados.",
        "unidade": "índice de 0 a 100; entrevistas",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "ano da pesquisa",
        "fontes": ["aneel_iasc"],
        "regra_agregacao": "Não é agregado: publicado por distribuidora; resumo nacional apenas por quantis entre distribuidoras.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["distribuidora", "ano", "categoria da pesquisa"],
        "regras_comparabilidade": ["A ANEEL compara distribuidoras dentro de categorias de porte e região.",
                                   "Em 2020 o construto de fidelidade não se formou (ausência publicada)."],
        "regra_cobertura": "Distribuidoras pesquisadas no ano (concessionárias e permissionárias).",
        "politica_ausencia": "Construto não publicado fica ausente.",
        "validacoes": ["Escala de 0 a 100 conferida em cada construção (reprovação derruba a publicação).",
                       "Conferência documental (não automática): a soma das amostras por distribuidora de 2025, 29.624 entrevistas em 103 distribuidoras, é coerente com as cerca de 30 mil que a ANEEL declara no conjunto de dados."],
        "limitacoes": ["Estimativa amostral sem intervalo de confiança publicado por distribuidora.", "Só consumidores residenciais."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_reclamacoes_por_uc",
        "titulo": "Reclamações por mil unidades consumidoras",
        "pergunta": "Quantas reclamações os consumidores registram na distribuidora e na ANEEL, considerando o tamanho de cada uma?",
        "definicao": "Reclamações recebidas no ano no 1º nível (SAC) e no 2º nível (ouvidoria) da distribuidora, pela tipologia da REN 1.000/2021 (grupo 102; em 2023 a tipologia vem do IdeTipoRCA traduzido por tabela explícita, porque o arquivo ainda usa códigos antigos), e reclamações registradas na Ouvidoria Setorial da ANEEL, divididas pelas UCs médias da mesma distribuidora no mesmo ano.",
        "unidade": "reclamações por mil UCs (distribuidora) e por 100 mil UCs (ANEEL)",
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "ano civil (meses publicados informados)",
        "fontes": ["aneel_manifestacoes", "aneel_ouvidoria", "aneel_continuidade"],
        "formula": "taxa = fator × Σ reclamações(g, ano) ÷ UCs médias(g, ano)",
        "numerador": "reclamações recebidas no ano",
        "denominador": "UCs médias da distribuidora no mesmo ano (indicadores de continuidade)",
        "regra_agregacao": "Brasil = Σ reclamações ÷ Σ UCs das distribuidoras com os dois dados (mesmo universo no numerador e no denominador).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano", "nível", "tipo de reclamação"],
        "regras_comparabilidade": ["Nunca comparar números absolutos sem a população exposta.",
                                   "Ano parcial não é comparado com ano completo.",
                                   "Série de 2010 a 2022 usa outra tipologia e não é somada."],
        "regra_cobertura": "Distribuidoras com manifestações e com UCs nos indicadores de continuidade.",
        "politica_ausencia": "Sem UCs no ano: taxa ausente. Manifestações: distribuidora sem os 12 meses enviados fica sem taxa e fora do agregado nacional (mês não enviado é ausência). Ouvidoria ANEEL: registro de solicitações; mês sem solicitação da distribuidora é zero registrado, mas distribuidora sem nenhuma solicitação no ano fica fora do agregado (zero e CNPJ não vinculado não se distinguem), com a cobertura em UCs publicada.",
        "validacoes": ["Reclamação identificada pelo grupo 102 da tipologia; linhas sem tipologia reconhecida contadas à parte (sem_grupo).",
                       "2023: reclamações de falta de energia pelo IdeTipoRCA conferidas com a soma pela descrição publicada (DscManifestacao) no teste.",
                       "Arquivo da Ouvidoria de 2023 em Parquet conferido com o CSV do mesmo ano: 603.640 linhas e as mesmas somas por categoria."],
        "limitacoes": ["Registro depende dos canais e da prática de cada distribuidora."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_tmae",
        "titulo": "Tempo médio de atendimento a emergências (TMAE)",
        "pergunta": "Quanto tempo, em média, a distribuidora leva para atender uma ocorrência emergencial?",
        "definicao": "TMAE = TMP (preparação) + TMD (deslocamento) + TME (execução), em minutos, apurado por conjunto e mês; agregado pela média ponderada pelo número de ocorrências emergenciais.",
        "unidade": "minutos",
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "mês; ano",
        "fontes": ["aneel_atendimento_emergencial"],
        "formula": "TMAE(g, período) = Σ (TMP + TMD + TME)(c, m) × ocorrências(c, m) ÷ Σ ocorrências(c, m)",
        "numerador": "Σ tempo médio × ocorrências",
        "denominador": "Σ ocorrências com os três tempos informados",
        "regra_agregacao": "Ponderação pelo número de ocorrências.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês", "ano"],
        "regras_comparabilidade": ["Distribuidoras com redes rurais extensas têm deslocamentos maiores."],
        "regra_cobertura": "Conjuntos com ocorrências e os três tempos informados, de 2015 em diante.",
        "politica_ausencia": "Conjunto-mês sem algum dos três tempos fica fora da média.",
        "validacoes": ["Controle: conjunto-meses com ocorrências com interrupção (Nie) maiores que o total de ocorrências (NumOcorr) são contados em cada construção e publicados como ressalva em validacao; a fonte publica esses casos e eles não são corrigidos. Nie não entra no TMAE.",
                       "TMAE do ano corrente marcado como parcial (meses publicados e período)."],
        "limitacoes": ["Média: não mostra os atendimentos muito longos."],
        "gold": _GOLD, "paginas": _PAG,
    },
{
        "id": "qualidade_dgc",
        "titulo": "DGC: desempenho global de continuidade",
        "pergunta": "Quão longe dos limites regulatórios, somando duração e frequência, ficou a distribuidora no ano?",
        "definicao": "Indicador de desempenho global de continuidade da ANEEL: média aritmética simples das razões apurado ÷ limite anual de DEC e de FEC da distribuidora. Abaixo de 1, dentro dos limites na média; acima de 1, acima.",
        "unidade": "razão adimensional",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "ano civil",
        "fontes": _CONT + ["aneel_ranking_continuidade"],
        "formula": "DGC(g, ano) = [DEC(g, ano) ÷ L_DEC(g, ano) + FEC(g, ano) ÷ L_FEC(g, ano)] ÷ 2",
        "regra_agregacao": "Calculado depois da agregação ponderada de apurado e limite; nunca média de DGC de conjuntos.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano"],
        "regras_comparabilidade": ["A ANEEL ranqueia separadamente distribuidoras com mais e com até 400 mil UCs.",
                                   "Distribuidoras em regime de designação ou em carência de contrato novo ficaram fora de rankings de alguns anos."],
        "regra_cobertura": "Distribuidoras com 12 meses e limite de DEC e FEC no ano.",
        "politica_ausencia": "Sem limite no ano: DGC ausente.",
        "validacoes": ["Reconciliado com o DGC publicado nas páginas do ranking da continuidade de 2021 a 2025 (tolerância 0,01, a precisão publicada); divergências listadas na gold."],
        "limitacoes": ["As divergências com o ranking não foram explicadas: revisão posterior dos indicadores, decisão judicial ou limite diferente na nota técnica são hipóteses não verificadas."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_eventos_emergencia",
        "titulo": "Eventos em situação de emergência",
        "pergunta": "Quais eventos extremos a distribuidora declarou e quanto eles superaram o critério de emergência?",
        "definicao": "Eventos declarados pelas distribuidoras como situação de emergência, com início, fim, CHI do evento (consumidor × hora interrompido) e CHI limite da distribuidora; a razão CHI do evento ÷ CHI limite mostra quantas vezes o evento superou o critério.",
        "unidade": "eventos; horas; consumidor × hora; razão",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "evento",
        "fontes": ["aneel_eventos_emergencia"],
        "formula": "duração = fim − início (horas); razão CHI = CHI do evento ÷ CHI limite",
        "regra_agregacao": "Não agregado: publicado por evento; contagem e duração mediana como resumo.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "evento", "origem"],
        "regras_comparabilidade": ["Base publicada a partir de 2026; não há série anterior no mesmo formato."],
        "regra_cobertura": "Eventos publicados no arquivo de 2026.",
        "politica_ausencia": "CHI limite vazio na fonte fica ausente e a razão não é calculada.",
        "validacoes": ["Datas lidas como publicadas; duração negativa ou extrema conferida no arquivo original antes de publicar."],
        "limitacoes": ["Evento declarado pela distribuidora e verificado pela ANEEL; a interrupção expurgada entra na parcela de emergência do DEC."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_mapa_intervalo_municipal",
        "titulo": "Intervalo de DEC e FEC dos conjuntos que atendem o município",
        "pergunta": "Que valores de continuidade têm os conjuntos que atendem este município?",
        "definicao": "Para cada município, o menor e o maior DEC (e FEC) anual entre os conjuntos ativos no ano que o atendem segundo a base IndQual Município, com a classificação da relação (conjunto exclusivo, conjunto compartilhado com outros municípios, vários conjuntos).",
        "unidade": _UNIDADE_DEC + "; " + _UNIDADE_FEC,
        "grao_geografico": "município (atribuição por conjunto, não medição municipal)",
        "grao_temporal": "ano civil",
        "fontes": _CONT + ["aneel_indqual_municipio"],
        "formula": "dec_min(mun) = min_c DEC(c, ano); dec_max(mun) = max_c DEC(c, ano), c nos conjuntos ativos ligados ao município",
        "regra_agregacao": "Sem média municipal: a base não informa quantas UCs de cada conjunto estão no município.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["município", "ano", "relação conjunto × município"],
        "regras_comparabilidade": ["Nunca ler o valor como DEC medido no município: quando o conjunto cobre vários municípios, todos recebem o mesmo intervalo."],
        "regra_cobertura": "Municípios da base IndQual Município com ao menos um conjunto com DEC no ano.",
        "politica_ausencia": "Município sem conjunto ativo no ano fica sem valor (sem_conjunto_ativo).",
        "validacoes": ["Só conjuntos com DEC publicado no ano entram (a base acumula conjuntos antigos sem vigência).",
                       "Códigos conferidos com o cadastro de municípios do IBGE (API de localidades) e com a malha do mapa: código sem município fica fora do mapa e listado; município sem relação publicada fica no mapa sem valor."],
        "limitacoes": ["A base não traz vigência da relação nem o número de UCs por município e conjunto."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_atendimento_telefonico",
        "titulo": "Qualidade do atendimento telefônico (INS, IAb, ICO)",
        "pergunta": "A central telefônica da distribuidora atende as ligações dentro do padrão regulatório?",
        "definicao": "Indicadores mensais publicados pela ANEEL para as distribuidoras obrigadas a manter central de teleatendimento: INS (chamadas atendidas em até 30 s ÷ chamadas recebidas menos as abandonadas em até 30 s; padrão ≥ 85%), IAb (abandonadas depois de 30 s ÷ o mesmo denominador; padrão ≤ 4%) e ICO (chamadas ocupadas ÷ oferecidas; padrão ≤ 2%), só com os períodos típicos; os valores cheios incluem os atípicos.",
        "unidade": "% e chamadas",
        "grao_geografico": "distribuidora (CNPJ) e Brasil (só as obrigadas)",
        "grao_temporal": "mês; ano (contagem de meses no padrão e ICO anual)",
        "fontes": ["aneel_atendimento_telefonico", "aneel_continuidade"],
        "formula": "ICO(g, ano) = 100 × Σ_m chamadas ocupadas ÷ Σ_m chamadas oferecidas; meses no padrão = #(meses com o indicador dentro do padrão)",
        "numerador": "chamadas ocupadas (ICO); meses dentro do padrão (INS, IAb)",
        "denominador": "chamadas oferecidas (ICO); meses publicados (INS, IAb)",
        "regra_agregacao": "INS e IAb não são agregados (a fonte não publica os numeradores em até 30 s): o resumo anual e nacional conta os distribuidora-meses dentro do padrão. ICO agregado por soma das contagens. Chamadas por mil UCs com as UCs médias do ano.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês", "ano", "indicador"],
        "regras_comparabilidade": ["Só as 40 distribuidoras com mais de 60 mil UCs (39 em 2014 e 2015); as menores não publicam.",
                                   "Regulado (períodos típicos) e cheio (todos os períodos) não se misturam.",
                                   "Ano corrente marcado como incompleto."],
        "regra_cobertura": "Distribuidoras obrigadas, de 2014 em diante; cobertura em UCs publicada por ano.",
        "politica_ausencia": "Mês não publicado fica ausente; percentual com denominador zero na fonte é publicado como a fonte o traz.",
        "validacoes": ["Chave (CNPJ, ano, mês) única no arquivo; repetição com valor diferente é contada.",
                       "ICO publicado = chamadas ocupadas ÷ oferecidas em todas as linhas (conferido); ICO acima de 100% (mais ocupadas que oferecidas) contado como ressalva em validacao."],
        "limitacoes": ["Indicador sobre a central telefônica: não mede o atendimento presencial, digital nem a solução do problema.",
                       "A fonte publica fração (0 a 1) em campos chamados Pct; o valor é multiplicado por 100."],
        "gold": _GOLD, "paginas": _PAG,
    },
]
