"""Métricas do módulo Qualidade do serviço de distribuição (P051 a P054). A fórmula roda
em pipeline/energia/modulos/qualidade.py; a interface lê o valor calculado e esta definição."""

_GOLD = "qualidade.json"
_PAG = ["/setor-eletrico/qualidade"]
_CONT = ["aneel_continuidade"]
_UNIDADE_DEC = "horas e centésimos de hora por unidade consumidora (10,50 h = 10 h 30 min)"
_UNIDADE_FEC = "interrupções e centésimos de interrupção por unidade consumidora"
_AUSENCIA_CONT = ("Conjunto sem valor ou sem número de UCs no mês fica fora do numerador e do denominador daquele mês "
                  "(nunca vira zero); ano com menos de 12 meses não tem valor anual; mês nacional com menos de 99% dos "
                  "conjuntos do último ano fica marcado como incompleto.")
_LIM_MEDIA = "Média por unidade consumidora: não descreve o tempo sem energia de cada pessoa nem de cada município."
_EXPURGOS = ("O apurado exclui interrupções em situação de emergência, dia crítico, de origem externa e por ação do ONS; "
             "elas aparecem nas parcelas.")

METRICAS = [
    {
        "id": "qualidade_dec_conjunto",
        "titulo": "DEC do conjunto de unidades consumidoras",
        "pergunta": "Por quanto tempo, em média, cada unidade consumidora do conjunto ficou sem energia?",
        "definicao": "Duração Equivalente de Interrupção por Unidade Consumidora apurada pela distribuidora para o conjunto (PRODIST, Módulo 8): soma das durações das interrupções de mais de 3 minutos de cada UC dividida pelo número de UCs. Valor mensal publicado pela ANEEL; o anual é a soma dos 12 meses. " + _EXPURGOS,
        "unidade": _UNIDADE_DEC,
        "grao_geografico": "conjunto de unidades consumidoras (IdeConjUndConsumidoras)",
        "grao_temporal": "mês; ano civil (soma dos meses)",
        "fontes": _CONT,
        "formula": "DEC(c, ano) = Σ_m DEC(c, m), só com os 12 meses publicados",
        "regra_agregacao": "Anual = soma dos meses do conjunto. Não se faz média simples entre conjuntos: agregados usam qualidade_dec_distribuidora.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["conjunto", "distribuidora (CNPJ)", "mês", "ano", "parcela"],
        "regras_comparabilidade": ["Comparar com o limite do mesmo conjunto e do mesmo ano.",
                                   "Ano parcial não é comparado com ano completo."],
        "regra_cobertura": "Conjuntos publicados no Parquet de continuidade de 2010 em diante.",
        "politica_ausencia": _AUSENCIA_CONT,
        "validacoes": ["Chave (CNPJ, conjunto, ano, mês, sigla) única; duplicata com valor diferente é contada.",
                       "Desde 2022, DEC = DECIP + DECIND em todos os conjunto-meses (tolerância 0,01 h de arredondamento).",
                       "Teste relê o Parquet por outro código e confere valores concretos."],
        "limitacoes": [_LIM_MEDIA, "Apurado e enviado pela distribuidora; sujeito a revisão e fiscalização da ANEEL."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_fec_conjunto",
        "titulo": "FEC do conjunto de unidades consumidoras",
        "pergunta": "Quantas vezes, em média, cada unidade consumidora do conjunto ficou sem energia?",
        "definicao": "Frequência Equivalente de Interrupção por Unidade Consumidora: número de interrupções de mais de 3 minutos de cada UC somado e dividido pelo número de UCs do conjunto. Valor mensal; anual = soma dos meses. " + _EXPURGOS,
        "unidade": _UNIDADE_FEC,
        "grao_geografico": "conjunto de unidades consumidoras",
        "grao_temporal": "mês; ano civil",
        "fontes": _CONT,
        "formula": "FEC(c, ano) = Σ_m FEC(c, m), só com os 12 meses publicados",
        "regra_agregacao": "Como o DEC do conjunto.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["conjunto", "distribuidora (CNPJ)", "mês", "ano", "parcela"],
        "regras_comparabilidade": ["Comparar com o limite de FEC do mesmo conjunto e ano."],
        "regra_cobertura": "Conjuntos publicados de 2010 em diante.",
        "politica_ausencia": _AUSENCIA_CONT,
        "validacoes": ["Desde 2022, FEC = FECIP + FECIND em todos os conjunto-meses (tolerância 0,01)."],
        "limitacoes": [_LIM_MEDIA],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_dec_distribuidora",
        "titulo": "DEC da distribuidora e do Brasil",
        "pergunta": "Por quanto tempo, em média, os consumidores da distribuidora (ou do país) ficaram sem energia no ano?",
        "definicao": "Média mensal do DEC dos conjuntos ponderada pelo número de unidades consumidoras de cada conjunto no mês, somada nos 12 meses. É o DEC da união dos conjuntos (Σ DIC ÷ UCs), a regra usada pela ANEEL no DGC do ranking da continuidade.",
        "unidade": _UNIDADE_DEC,
        "grao_geografico": "distribuidora (CNPJ de 14 dígitos) e Brasil",
        "grao_temporal": "mês e ano civil",
        "fontes": _CONT,
        "formula": "DEC(g, m) = Σ_c DEC(c, m) × UC(c, m) ÷ Σ_c UC(c, m); DEC(g, ano) = Σ_m DEC(g, m)",
        "numerador": "Σ_c DEC(c, m) × UC(c, m), em horas × UC",
        "denominador": "Σ_c UC(c, m) dos conjuntos com DEC e número de UCs no mês",
        "regra_agregacao": "Ponderação por UCs no mês; soma dos meses no ano. Nunca média simples de conjuntos ou de distribuidoras.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês", "ano", "parcela"],
        "regras_comparabilidade": ["Comparar com o limite agregado do mesmo ano.",
                                   "Ano corrente só contra os mesmos meses do ano anterior.",
                                   "2010 a 2021: parte dos conjuntos incluía parcelas externas no apurado (identidade publicada por ano)."],
        "regra_cobertura": "Distribuidoras com conjuntos no Parquet de continuidade; cobertura mensal (UCs com DEC ÷ UCs com número de UCs) publicada.",
        "politica_ausencia": _AUSENCIA_CONT,
        "validacoes": ["Reconciliação: DGC calculado com esta regra contra o DGC publicado pela ANEEL no ranking (tolerância 0,01, a precisão publicada).",
                       "Identidade: Brasil = agregação das distribuidoras com os mesmos pesos."],
        "limitacoes": [_LIM_MEDIA, "Distribuidora sem conjuntos no conjunto de dados (algumas permissionárias pequenas) não aparece."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_fec_distribuidora",
        "titulo": "FEC da distribuidora e do Brasil",
        "pergunta": "Quantas vezes, em média, os consumidores da distribuidora (ou do país) ficaram sem energia no ano?",
        "definicao": "Média mensal do FEC dos conjuntos ponderada pelo número de UCs de cada conjunto no mês, somada nos 12 meses.",
        "unidade": _UNIDADE_FEC,
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "mês e ano civil",
        "fontes": _CONT,
        "formula": "FEC(g, m) = Σ_c FEC(c, m) × UC(c, m) ÷ Σ_c UC(c, m); FEC(g, ano) = Σ_m FEC(g, m)",
        "numerador": "Σ_c FEC(c, m) × UC(c, m)",
        "denominador": "Σ_c UC(c, m) dos conjuntos com FEC no mês",
        "regra_agregacao": "Como o DEC da distribuidora.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês", "ano", "parcela"],
        "regras_comparabilidade": ["Como o DEC da distribuidora."],
        "regra_cobertura": "Como o DEC da distribuidora.",
        "politica_ausencia": _AUSENCIA_CONT,
        "validacoes": ["Reconciliação com o DGC publicado (inclui a razão de FEC)."],
        "limitacoes": [_LIM_MEDIA],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_parcelas",
        "titulo": "Parcelas do DEC e do FEC por origem e expurgo",
        "pergunta": "Quanto do tempo sem energia foi expurgado do apurado e por quê?",
        "definicao": "Parcelas publicadas pela ANEEL: interna programada (IP) e não programada não expurgável (IND), que formam o apurado; situação de emergência (INE); dia crítico (INC, IPC); origem externa (XN, XP, XNC, XPC); racionamento ou alívio de carga pelo ONS (INO). O total de todas as parcelas é o DEC de todas as origens publicadas.",
        "unidade": _UNIDADE_DEC + "; " + _UNIDADE_FEC,
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "ano civil",
        "fontes": _CONT,
        "formula": "P(g, ano) = Σ_m [Σ_c P(c, m) × UC(c, m) ÷ Σ_c UC(c, m)], só conjuntos que informaram a parcela no mês",
        "numerador": "Σ_c P(c, m) × UC(c, m)",
        "denominador": "Σ_c UC(c, m) dos conjuntos que informaram a parcela",
        "regra_agregacao": "Ponderação por UCs no mês, soma no ano; a cobertura da parcela (fração das UC-mês com a parcela informada) é guardada no silver.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano", "grupo de parcela"],
        "regras_comparabilidade": ["Desde 2022 as parcelas externas em dia crítico (XNC, XPC) deixaram de ser informadas pela maioria dos conjuntos: o grupo externa antes e depois de 2022 não é homogêneo."],
        "regra_cobertura": "Conjuntos com as parcelas IP e IND informadas entram no total.",
        "politica_ausencia": "Parcela não informada não é zero: fica fora do numerador e do denominador daquela parcela.",
        "validacoes": ["Soma dos grupos = total de todas as parcelas publicadas.", "Apurado = IP + IND desde 2022."],
        "limitacoes": ["Interrupções de até 3 minutos e as de responsabilidade do consumidor não são publicadas em nenhuma parcela."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_limite_e_razao",
        "titulo": "Limite anual e distância ao limite (razão apurado ÷ limite)",
        "pergunta": "O serviço cumpriu o padrão regulatório no ano?",
        "definicao": "Limite anual de DEC e FEC fixado pela ANEEL para cada conjunto e ano. Para a distribuidora e o Brasil, média dos limites dos conjuntos ponderada pelas UCs médias do ano. Razão = apurado anual ÷ limite do mesmo ano; acima de 1 = transgressão.",
        "unidade": "horas, interrupções e razão adimensional",
        "grao_geografico": "conjunto, distribuidora e Brasil",
        "grao_temporal": "ano civil (vigência do limite)",
        "fontes": _CONT,
        "formula": "L(g, ano) = Σ_c L(c, ano) × UCmédia(c, ano) ÷ Σ_c UCmédia(c, ano); razão = DEC(g, ano) ÷ L(g, ano)",
        "numerador": "DEC ou FEC apurado no ano",
        "denominador": "limite do mesmo ano e do mesmo universo de conjuntos",
        "regra_agregacao": "Limite ponderado pelas UCs; razão calculada depois da agregação (nunca média de razões de conjuntos).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["conjunto", "distribuidora", "ano"],
        "regras_comparabilidade": ["Realizado e limite sempre do mesmo ano e da mesma cobertura.", "Conjunto sem limite no ano fica fora da razão."],
        "regra_cobertura": "Conjuntos com 12 meses e limite publicado no ano; cobertura do limite (fração de UCs) publicada por distribuidora.",
        "politica_ausencia": "Sem limite publicado para o conjunto e ano: razão ausente; distribuidora em carência de contrato novo fica sem razão.",
        "validacoes": ["DGC = (razão DEC + razão FEC) ÷ 2 reconciliado com o ranking da ANEEL de 2021 em diante."],
        "limitacoes": ["A distribuição dos conjuntos (quantis e caudas) é publicada ao lado da média para não esconder conjuntos muito acima do limite."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_pct_conjuntos_acima",
        "titulo": "Conjuntos acima do limite de DEC",
        "pergunta": "Quantos conjuntos, e quantas unidades consumidoras, ficaram acima do limite de DEC no ano?",
        "definicao": "Número e percentual de conjuntos com 12 meses publicados e limite de DEC no ano cujo DEC anual é maior que o limite; também a fração das UCs (médias do ano) nesses conjuntos.",
        "unidade": "% dos conjuntos e % das UCs",
        "grao_geografico": "Brasil",
        "grao_temporal": "ano civil",
        "fontes": _CONT,
        "formula": "100 × #(DEC(c, ano) > L(c, ano)) ÷ #(conjuntos com limite)",
        "numerador": "conjuntos com DEC anual acima do limite",
        "denominador": "conjuntos com 12 meses e limite",
        "regra_agregacao": "Contagem simples de conjuntos; versão ponderada por UCs publicada ao lado.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["ano"],
        "regras_comparabilidade": ["Conjuntos têm tamanhos muito diferentes: a contagem e a fração de UCs respondem perguntas diferentes."],
        "regra_cobertura": "Conjuntos com 12 meses e limite de DEC publicado no ano.",
        "politica_ausencia": "Sem limite ou com menos de 12 meses: fora do denominador.",
        "validacoes": ["Comparação estrita com os valores publicados em centésimos."],
        "limitacoes": ["Estar acima do limite coletivo não implica que cada UC do conjunto tenha recebido compensação."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_compensacoes",
        "titulo": "Compensações pagas por violação dos limites individuais de continuidade",
        "pergunta": "Quanto as distribuidoras pagaram em compensações por interrupções acima dos limites individuais?",
        "definicao": "Soma dos valores pagos e das quantidades de compensação publicadas pela ANEEL por conjunto, tipo (mensal, trimestral, anual, DICRI, DISE), tensão e competência, para unidades consumidoras e unidades geradoras.",
        "unidade": "R$ nominais; ocorrências de compensação",
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "competência mensal (trimestre e ano para os tipos trimestral e anual)",
        "fontes": _CONT,
        "formula": "valor(g, competência) = Σ_c Σ_tensão valor pago(c, tensão, tipo, competência)",
        "numerador": "valor pago (R$) ou quantidade",
        "regra_agregacao": "Soma simples (grandezas aditivas); valor por UC = valor anual ÷ UCs médias do ano, só como normalização.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "competência", "tipo", "unidade consumidora ou geradora", "tensão"],
        "regras_comparabilidade": ["Reais correntes, sem correção pela inflação.",
                                   "Trimestral e anual têm valores nulos desde 2022 (mudança do PRODIST); DISE só desde 2026.",
                                   "Mês ou ano sem todas as distribuidoras fica marcado como incompleto."],
        "regra_cobertura": "Compensações publicadas desde 2011.",
        "politica_ausencia": "Distribuidora sem linha na competência fica sem valor; zero só quando a fonte publica zero.",
        "validacoes": ["Sigla fora do padrão PG/QT de continuidade é contada e não somada.", "Soma relida do Parquet por outro código no teste."],
        "limitacoes": ["Quantidade é de ocorrências, não de consumidores distintos.",
                       "A fonte não informa a data do crédito, só a competência.",
                       "O crédito individual não pode ser estimado a partir do DEC ou FEC do conjunto."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_iasc",
        "titulo": "Índice ANEEL de Satisfação do Consumidor (IASC)",
        "pergunta": "Quão satisfeitos os consumidores residenciais dizem estar com a distribuidora?",
        "definicao": "Índice de 0 a 100 estimado pela ANEEL a partir de pesquisa amostral anual com consumidores residenciais de cada distribuidora (construto de satisfação), publicado com a ordem na categoria e com as contagens de entrevistados.",
        "unidade": "índice de 0 a 100; entrevistas",
        "grao_geografico": "distribuidora (CNPJ)",
        "grao_temporal": "ano da pesquisa",
        "fontes": ["aneel_iasc"],
        "regra_agregacao": "Não é agregado: publicado por distribuidora; resumo nacional apenas por quantis entre distribuidoras.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["distribuidora", "ano", "categoria da pesquisa"],
        "regras_comparabilidade": ["A ANEEL compara distribuidoras dentro de categorias de porte e região.",
                                   "Em 2020 o construto de fidelidade não se formou (ausência publicada)."],
        "regra_cobertura": "Distribuidoras pesquisadas no ano (concessionárias e permissionárias).",
        "politica_ausencia": "Construto não publicado fica ausente.",
        "validacoes": ["Soma das amostras por distribuidora conferida com o total declarado pela ANEEL (cerca de 30 mil entrevistas)."],
        "limitacoes": ["Estimativa amostral sem intervalo de confiança publicado por distribuidora.", "Só consumidores residenciais."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_reclamacoes_por_uc",
        "titulo": "Reclamações por mil unidades consumidoras",
        "pergunta": "Quantas reclamações os consumidores registram na distribuidora e na ANEEL, considerando o tamanho de cada uma?",
        "definicao": "Reclamações recebidas no ano no 1º nível (SAC) e no 2º nível (ouvidoria) da distribuidora, pela tipologia da REN 1.000/2021 (códigos 102), e reclamações registradas na Ouvidoria Setorial da ANEEL, divididas pelas UCs médias da mesma distribuidora no mesmo ano.",
        "unidade": "reclamações por mil UCs (distribuidora) e por 100 mil UCs (ANEEL)",
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "ano civil (meses publicados informados)",
        "fontes": ["aneel_manifestacoes", "aneel_ouvidoria", "aneel_continuidade"],
        "formula": "taxa = fator × Σ reclamações(g, ano) ÷ UCs médias(g, ano)",
        "numerador": "reclamações recebidas no ano",
        "denominador": "UCs médias da distribuidora no mesmo ano (indicadores de continuidade)",
        "regra_agregacao": "Brasil = Σ reclamações ÷ Σ UCs das distribuidoras com os dois dados (mesmo universo no numerador e no denominador).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "ano", "nível", "tipo de reclamação"],
        "regras_comparabilidade": ["Nunca comparar números absolutos sem a população exposta.",
                                   "Ano parcial não é comparado com ano completo.",
                                   "Série de 2010 a 2022 usa outra tipologia e não é somada."],
        "regra_cobertura": "Distribuidoras com manifestações e com UCs nos indicadores de continuidade.",
        "politica_ausencia": "Sem UCs no ano: taxa ausente.",
        "validacoes": ["Reclamação identificada pelo prefixo 102 do código de tipologia; códigos fora da tipologia contados à parte."],
        "limitacoes": ["Registro depende dos canais e da prática de cada distribuidora."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "qualidade_tmae",
        "titulo": "Tempo médio de atendimento a emergências (TMAE)",
        "pergunta": "Quanto tempo, em média, a distribuidora leva para atender uma ocorrência emergencial?",
        "definicao": "TMAE = TMP (preparação) + TMD (deslocamento) + TME (execução), em minutos, apurado por conjunto e mês; agregado pela média ponderada pelo número de ocorrências emergenciais.",
        "unidade": "minutos",
        "grao_geografico": "distribuidora (CNPJ) e Brasil",
        "grao_temporal": "mês; ano",
        "fontes": ["aneel_atendimento_emergencial"],
        "formula": "TMAE(g, período) = Σ (TMP + TMD + TME)(c, m) × ocorrências(c, m) ÷ Σ ocorrências(c, m)",
        "numerador": "Σ tempo médio × ocorrências",
        "denominador": "Σ ocorrências com os três tempos informados",
        "regra_agregacao": "Ponderação pelo número de ocorrências.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["distribuidora", "mês", "ano"],
        "regras_comparabilidade": ["Distribuidoras com redes rurais extensas têm deslocamentos maiores."],
        "regra_cobertura": "Conjuntos com ocorrências e os três tempos informados, de 2015 em diante.",
        "politica_ausencia": "Conjunto-mês sem algum dos três tempos fica fora da média.",
        "validacoes": ["Ocorrências com interrupção (Nie) nunca maiores que o total de ocorrências."],
        "limitacoes": ["Média: não mostra os atendimentos muito longos."],
        "gold": _GOLD, "paginas": _PAG,
    },
]
