"""Métricas do módulo Transição e ambiente (P063 e P064). As fórmulas rodam em
pipeline/energia/modulos/transicao.py; a interface lê o valor calculado e esta definição.

Três famílias que não se misturam: capacidade cadastrada de MMGD (ANEEL, kW), energia
de MMGD estimada pelo ONS (MWmed) e fatores de emissão de CO2 do MCTI (tCO2/MWh)."""

_GOLD = "transicao.json"
_PAG = ["/setor-eletrico/transicao"]
_MMGD = ["aneel_mmgd_empreendimentos"]
_POP = ["ibge_populacao_6579"]
_ONS = ["ons_carga_verificada_mmgd"]
_MCTI = ["mcti_fator_emissao"]
_CAPACIDADE = "Capacidade instalada cadastrada, não energia gerada."
_AUSENCIA_MMGD = ("Combinação sem registro no cadastro = zero empreendimentos (o arquivo é o cadastro completo), dentro da "
                  "cobertura declarada pela ANEEL (a partir de dez/2008); antes dela, período sem registro = nulo rotulado "
                  "(cobertura_declarada fora ou parcial), e registro existente é publicado com o rótulo. Potência ausente em um "
                  "registro não vira zero: a unidade conta, a potência fica fora da soma, cada agregado traz "
                  "unidades_sem_potencia (soma parcial) e agregado sem nenhuma potência informada publica potência nula. Data "
                  "sentinela (ano < 2000) = sem ano de conexão, no estoque e fora das séries por ano.")
_VALIDACOES_MMGD = ["Código de empreendimento único no arquivo (repetição derruba a publicação).",
                    "Identidade de agregação: soma por município = soma por UF e mês = soma por distribuidora = soma por distribuidora e município = linhas do arquivo.",
                    "Identidade de estoque: estoque acumulado por data de conexão (séries anual e mensal) + unidades com data sentinela = total do cadastro, em unidades (exato) e kW (0,01 kW); diferença derruba a publicação.",
                    "Área da distribuidora: unidades em UF onde o CNPJ da distribuidora não tem conjunto elétrico (base de continuidade da ANEEL) são contadas por município e sinalizadas, sem correção, e separadas pelo CEP publicado em provável município errado (CEP na área da distribuidora), provável distribuidora errada (CEP, código do empreendimento e UF publicada na UF do município) e indeterminadas; as classes somam o total sinalizado (diferença derruba a publicação).",
                    "Unidades sem potência nos agregados = registros com potência ausente ou negativa no arquivo (diferença derruba a publicação).",
                    "Potência não negativa; datas não posteriores à data de geração do conjunto.",
                    "Data de conexão conferida com DatConexao do recurso técnico fotovoltaico, pelo código.",
                    "Parquet e CSV oficiais do mesmo conjunto conferidos entre si por UF e ano (30/09/2026)."]
_LIM_MMGD = ["O cadastro é o vigente na data do arquivo; unidades desativadas não aparecem no histórico.",
             "Meses recentes provisórios: conexões desses meses ainda podem entrar em capturas seguintes; a queda nos meses finais do arquivo não tem causa atribuída.",
             "Duplicidade candidata medida e não removida (CPF e CEP de pessoa física vêm tarjados).",
             ("Há unidades cadastradas em UF onde a distribuidora informada não tem conjunto elétrico: algum campo está errado na origem. "
              "Pelo CEP, parte provavelmente tem o município errado (infla o município publicado) e parte provavelmente tem o CNPJ "
              "errado (fica no município publicado e infla o total da distribuidora informada); ficam sinalizadas, sem correção.")]
_NATUREZA_MCTI = ("Fator estimado pelo MCTI (emissões calculadas a partir do consumo de combustível e de fatores metodológicos, "
                  "divididas pela geração do ONS), não medido; a plataforma publica o valor oficial sem alteração, por isso a "
                  "transformação também é ESTIMADO (da fonte) e não CALCULADO.")
_REGRA_ANO = "Ano parcial (o da data do cadastro) não entra em comparação de crescimento; usa-se o último ano completo."

METRICAS = [
    {
        "id": "mmgd_unidades",
        "titulo": "Unidades de micro e minigeração distribuída",
        "pergunta": "Quantos empreendimentos de MMGD estão conectados e cadastrados?",
        "definicao": "Número de empreendimentos (códigos distintos) na Relação de empreendimentos de MMGD da ANEEL, no cadastro vigente, por território, distribuidora, fonte, classe, modalidade ou ano de conexão.",
        "unidade": "empreendimentos",
        "grao_geografico": "município (código IBGE), UF, distribuidora (CNPJ), Brasil",
        "grao_temporal": "ano e mês de conexão; estoque na data do cadastro",
        "fontes": _MMGD,
        "regra_agregacao": "Contagem simples de registros; soma entre territórios e anos (cada empreendimento conta uma vez).",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["município", "UF", "distribuidora", "fonte", "classe de consumo", "modalidade", "porte", "tipo de consumidor", "ano de conexão"],
        "regras_comparabilidade": ["Unidade de MMGD não é domicílio nem consumidor: uma unidade pode repartir créditos com várias outras.", _REGRA_ANO],
        "regra_cobertura": "Todas as distribuidoras que enviaram dados ao sistema de MMGD da ANEEL; cobertura declarada a partir de dez/2008 (registro anterior publicado com rótulo; período anterior sem registro nulo, não zero).",
        "politica_ausencia": _AUSENCIA_MMGD,
        "validacoes": _VALIDACOES_MMGD,
        "limitacoes": _LIM_MMGD,
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "mmgd_potencia_instalada",
        "titulo": "Potência instalada de MMGD",
        "pergunta": "Quanta capacidade de micro e minigeração distribuída existe em cada lugar?",
        "definicao": "Soma da potência instalada (MdaPotenciaInstaladaKW: soma das potências elétricas ativas nominais das unidades geradoras) dos empreendimentos do cadastro vigente. " + _CAPACIDADE,
        "unidade": "kW (MW nas tabelas, kW ÷ 1000)",
        "grao_geografico": "município (código IBGE), UF, distribuidora (CNPJ), Brasil",
        "grao_temporal": "ano e mês de conexão; estoque na data do cadastro",
        "fontes": _MMGD,
        "regra_agregacao": "Soma dos kW; estoque acumulado por data de conexão.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "OBSERVADO",
        "dimensoes": ["município", "UF", "distribuidora", "fonte", "classe", "modalidade", "porte", "ano e mês de conexão"],
        "regras_comparabilidade": ["Capacidade (MW) não se compara nem se soma com energia (MWh, MWmed).", _REGRA_ANO],
        "regra_cobertura": "Igual à de unidades.",
        "politica_ausencia": _AUSENCIA_MMGD,
        "validacoes": _VALIDACOES_MMGD,
        "limitacoes": _LIM_MMGD + ["Minigeração em autoconsumo remoto e em geração compartilhada fica no município da usina, não no de "
                                   "quem usa o crédito: no autoconsumo remoto a energia compensa outras unidades do mesmo titular, e na "
                                   "geração compartilhada o consumo dos participantes de consórcio, cooperativa, condomínio ou "
                                   "associação (definições da ANEEL), possivelmente em outro município."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "mmgd_potencia_por_habitante",
        "titulo": "Potência de MMGD por habitante",
        "pergunta": "Onde há mais capacidade de geração distribuída em relação à população?",
        "definicao": "Potência instalada cadastrada no território dividida pela população residente estimada pelo IBGE. Relaciona território, não renda nem perfil de beneficiário.",
        "unidade": "W por habitante",
        "grao_geografico": "município, UF, Brasil",
        "grao_temporal": "estoque na data do cadastro; população do último ano estimado",
        "fontes": _MMGD + _POP,
        "formula": "Σ kW instalados × 1000 ÷ população estimada",
        "numerador": "potência instalada cadastrada no território (W)",
        "denominador": "população residente estimada (IBGE, SIDRA 6579)",
        "regra_agregacao": "Razão de somas: Σ W ÷ Σ habitantes do território; nunca média de razões municipais.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["município", "UF"],
        "regras_comparabilidade": ["Rankings só entre municípios com pelo menos 100 mil habitantes estimados (denominador pequeno é instável).",
                                   "Não indica renda nem quem se beneficia da geração."],
        "regra_cobertura": "Municípios com população estimada publicada; sem população = razão ausente.",
        "politica_ausencia": "Município sem população publicada: razão ausente (não zero). Município sem MMGD: zero real.",
        "validacoes": ["Soma municipal da população igual à da UF publicada pelo IBGE (conferida no teste com amostra real).",
                       "Município com unidades de distribuidora sem conjunto elétrico na UF fica sinalizado, com a contagem e os kW dessas unidades e de cada classe pelo CEP.",
                       "Município com unidade sem potência informada fica fora dos rankings e dos quantis (soma parcial)."],
        "limitacoes": ["População é estimativa do IBGE para 1º de julho do ano, não contagem censitária.", _CAPACIDADE,
                       ("Em município com unidades da classe de provável município errado (CEP publicado numa UF da área da distribuidora), a "
                        "razão inclui unidades que provavelmente ficam em outro município e pode estar inflada (ex.: São Caetano de Odivelas, PA, "
                        "com 185 de 249 unidades da Neoenergia PE); para refazê-la, desconte só essa classe (colunas do CSV municipal). A classe "
                        "de provável distribuidora errada (CEP, código e UF publicada na UF do município) fica no município publicado e não "
                        "infla a razão municipal.")],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "mmgd_unidades_por_mil_habitantes",
        "titulo": "Unidades de MMGD por mil habitantes",
        "pergunta": "Quão difundida está a geração distribuída em cada território?",
        "definicao": "Empreendimentos de MMGD no território por mil habitantes estimados pelo IBGE.",
        "unidade": "unidades por mil habitantes",
        "grao_geografico": "município, UF",
        "grao_temporal": "estoque na data do cadastro",
        "fontes": _MMGD + _POP,
        "formula": "Σ unidades × 1000 ÷ população estimada",
        "numerador": "unidades de MMGD no território",
        "denominador": "população residente estimada",
        "regra_agregacao": "Razão de somas.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["município", "UF"],
        "regras_comparabilidade": ["Unidade não é domicílio: não é taxa de adoção por família."],
        "regra_cobertura": "Municípios com população estimada publicada.",
        "politica_ausencia": "Sem população: razão ausente.",
        "validacoes": ["Mesmas da potência por habitante."],
        "limitacoes": ["Não mede quantas famílias se beneficiam: créditos podem ir para várias unidades."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "mmgd_crescimento_estoque_ano",
        "titulo": "Crescimento da potência de MMGD no último ano completo",
        "pergunta": "Onde a geração distribuída cresceu mais no último ano completo?",
        "definicao": "Potência conectada no ano de referência (último ano completo antes da data do cadastro) dividida pela potência conectada até 31/12 do ano anterior, no cadastro vigente.",
        "unidade": "%",
        "grao_geografico": "município, UF",
        "grao_temporal": "ano",
        "fontes": _MMGD,
        "formula": "100 × kW conectados no ano ÷ kW conectados até o fim do ano anterior",
        "numerador": "kW com data de conexão no ano de referência",
        "denominador": "kW com data de conexão até 31/12 do ano anterior",
        "regra_agregacao": "Razão de somas por território.",
        "versao_formula": "1",
        "natureza_fonte": "OBSERVADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["município", "UF"],
        "regras_comparabilidade": ["Estoque anterior zero: crescimento ausente (não infinito).", "Ranking municipal só com população ≥ 100 mil."],
        "regra_cobertura": "Territórios com estoque anterior positivo.",
        "politica_ausencia": "Estoque anterior zero ou sem data: ausente.",
        "validacoes": ["Identidade de estoque: estoque acumulado por ano de conexão + unidades sem data = total do cadastro (o estoque por ano não alcança o total sem os registros de data sentinela)."],
        "limitacoes": ["Conexões do ano de referência ainda não cadastradas o subestimariam até a captura seguinte.", _CAPACIDADE],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "ons_mmgd_estimada_mwmed",
        "titulo": "MMGD estimada pelo ONS",
        "pergunta": "Quanta energia a micro e minigeração distribuída entregou, segundo a estimativa do ONS?",
        "definicao": "Parcela da carga atendida por MMGD (val_cargammgd) na Carga de Energia Verificada do ONS, em MWmed do período: energia estimada dividida pelas horas cobertas.",
        "unidade": "MWmed",
        "grao_geografico": "submercado (SE/CO, S, NE, N) e SIN",
        "grao_temporal": "dia e mês (fonte semi-horária)",
        "fontes": _ONS,
        "formula": "Σ(val_cargammgd × 0,5 h) ÷ Σ horas cobertas; SIN = soma dos quatro submercados nos dias completos",
        "numerador": "energia de MMGD estimada (MWh)",
        "denominador": "horas cobertas",
        "regra_agregacao": "Razão de somas de energia por horas; nunca média de médias diárias.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["submercado", "dia", "mês", "ano"],
        "regras_comparabilidade": ["Energia estimada (MWmed) não se soma com capacidade cadastrada (MW).",
                                   "Só SIN: não inclui sistemas isolados."],
        "regra_cobertura": "Desde 15/02/2019, primeiro dia com valor na API (antes, o campo vem vazio); dias sem valor depois disso são ausência.",
        "politica_ausencia": "Meia hora sem valor fora da soma e das horas; dia sem as 24 horas não entra no SIN.",
        "validacoes": ["Identidade do ONS: carga global = carga sem MMGD + MMGD, dia a dia (0,1 MWh).",
                       "Valores não negativos (o dicionário não admite negativo)."],
        "limitacoes": ["Estimativa do ONS, não medição: o ONS a chama de valor estimado e a separa, no dicionário da carga verificada, da parcela supervisionada; os documentos consultados não descrevem o método.",
                       "O ONS revisa o histórico; meses antigos são recoletados a cada 30 dias."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "ons_mmgd_participacao_carga",
        "titulo": "Participação da MMGD estimada na carga global",
        "pergunta": "Que parte da carga do SIN foi atendida por MMGD, segundo o ONS?",
        "definicao": "Energia de MMGD estimada dividida pela energia da carga global, no mesmo período e perímetro.",
        "unidade": "%",
        "grao_geografico": "submercado e SIN",
        "grao_temporal": "mês e ano",
        "fontes": _ONS,
        "formula": "100 × Σ MWh de MMGD ÷ Σ MWh da carga global",
        "numerador": "energia de MMGD estimada (MWh)",
        "denominador": "energia da carga global (MWh), mesmos intervalos",
        "regra_agregacao": "Razão de somas; nunca média de percentuais.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["submercado", "mês", "ano"],
        "regras_comparabilidade": ["Numerador e denominador do mesmo conjunto e intervalos."],
        "regra_cobertura": "Dias completos.",
        "politica_ausencia": "Mês sem dia completo: ausente.",
        "validacoes": ["Participação entre 0 e 100%, executada a cada publicação: mês (submercado ou SIN) ou ano fora do intervalo derruba a publicação (stub); dia com MMGD negativa ou maior que a carga global vira ressalva na proveniência."],
        "limitacoes": ["Herda a natureza estimada da parcela de MMGD."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "razao_mmgd_ons_capacidade_aneel",
        "titulo": "Razão entre a MMGD estimada pelo ONS e a capacidade cadastrada na ANEEL",
        "pergunta": "A estimativa operacional do ONS é coerente com o tamanho do parque cadastrado?",
        "definicao": "MMGD estimada no SIN (MWmed) dividida pela capacidade cadastrada no Brasil (MW), média do estoque no início e no fim do mês. Comparação de coerência entre duas fontes, não fator de capacidade medido.",
        "unidade": "%",
        "grao_geografico": "SIN (numerador) e Brasil (denominador)",
        "grao_temporal": "mês",
        "fontes": _ONS + _MMGD,
        "formula": "100 × MWmed estimado (SIN) ÷ ((estoque no início do mês + estoque no fim do mês) ÷ 2)",
        "numerador": "MMGD estimada pelo ONS no SIN (MWmed)",
        "denominador": "capacidade de MMGD cadastrada na ANEEL (MW), Brasil",
        "regra_agregacao": "Mensal; sem agregação anual.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "CALCULADO",
        "dimensoes": ["mês"],
        "regras_comparabilidade": ["Perímetros diferentes (SIN × Brasil); conexões ainda não cadastradas nos meses recentes inflariam a razão."],
        "regra_cobertura": "Meses completos da estimativa do ONS e não provisórios no cadastro da ANEEL (anteriores aos 6 meses que precedem a data do cadastro).",
        "politica_ausencia": "Mês incompleto no ONS ou provisório no cadastro: razão ausente (o denominador ainda pode crescer em capturas seguintes).",
        "validacoes": ["Identidade de estoque: estoque mensal acumulado até a data do cadastro + unidades sem data de conexão = total cadastrado (unidades exatas; 0,01 kW). O denominador usa o estoque com data, que não inclui as unidades de data sentinela."],
        "limitacoes": ["Não é fator de capacidade e não deve ser usado para estimar geração municipal."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "mcti_fator_medio_emissao",
        "titulo": "Fator médio de emissão de CO2 do SIN (inventários)",
        "pergunta": "Quanto CO2, em média, foi emitido por MWh gerado no SIN?",
        "definicao": "Fator médio mensal e anual publicado pelo MCTI: média das emissões de todas as usinas em operação no SIN por MWh gerado. Serve para inventários. Não é fator marginal.",
        "unidade": "tCO2/MWh",
        "grao_geografico": "SIN (nacional)",
        "grao_temporal": "mês e ano",
        "fontes": _MCTI,
        "regra_agregacao": "Nenhuma: valores oficiais como publicados. O anual oficial é o do MCTI, não média dos meses.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["mês", "ano"],
        "regras_comparabilidade": ["Não comparar com margem de operação ou de construção.", "CO2, não CO2e.",
                                   "Fator nacional: não existe versão municipal nem horária."],
        "regra_cobertura": "Mensal de jan/2006 ao último mês publicado; anual de 2006 ao último ano completo (planilha de inventários da página vigente do MCTI). O ano corrente não tem anual.",
        "politica_ausencia": "Mês ou ano sem valor publicado fica sem valor; nada é estimado para preencher.",
        "validacoes": ["0 ≤ fator < 2 tCO2/MWh.", "12 meses em cada ano com fator anual.",
                       "Anual publicado comparado à média simples dos 12 meses publicados, tolerância 0,0001 tCO2/MWh (arredondamento da quarta casa); ano fora vira ressalva, sem ajuste.",
                       "Valores da página vigente comparados aos do site institucional anterior do MCTI (2006 a 2021); diferenças publicadas."],
        "limitacoes": [_NATUREZA_MCTI, "Base de usinas do ONS ampliada a partir de jan/2025 (nota técnica NT_FE_jun25): comparações que atravessam jan/2025 misturam bases.",
                       "Emissões da operação das usinas, só CO2; não é ciclo de vida nem CO2e.",
                       "A página vigente do MCTI pode responder com desafio de verificação humana; o pipeline não contorna e mantém a última captura válida."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "mcti_margem_operacao",
        "titulo": "Fator de emissão da margem de operação (MDL)",
        "pergunta": "Qual a intensidade de CO2 das usinas na margem do despacho, para projetos de MDL?",
        "definicao": "Fator da margem de operação pelo método da análise de despacho (mensal e diário) e pelo método simples ajustado (anual), publicados pelo MCTI conforme a ferramenta do Conselho Executivo do MDL.",
        "unidade": "tCO2/MWh",
        "grao_geografico": "SIN",
        "grao_temporal": "dia, mês (despacho) e ano (simples ajustado)",
        "fontes": _MCTI,
        "regra_agregacao": "Nenhuma: valores oficiais.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["dia", "mês", "ano", "método"],
        "regras_comparabilidade": ["Uso exclusivo em projetos de MDL; não é intensidade média da eletricidade consumida."],
        "regra_cobertura": "Despacho: diário e mensal de 2006 ao último mês publicado. Simples ajustado: anual de 2006 ao último ano publicado.",
        "politica_ausencia": "Dia inexistente no calendário (ex.: 29/02 em ano não bissexto, preenchido com 0 na planilha) é descartado.",
        "validacoes": ["Média simples dos fatores diários comparada ao mensal publicado.",
                       "Leitura do mês pela posição quando o rótulo da coluna diverge (registrado em problemas de leitura)."],
        "limitacoes": [_NATUREZA_MCTI, "Método do MDL; não descreve o sistema médio."],
        "gold": _GOLD, "paginas": _PAG,
    },
    {
        "id": "mcti_margem_construcao",
        "titulo": "Fator de emissão da margem de construção (MDL)",
        "pergunta": "Qual a intensidade de CO2 das usinas construídas mais recentemente, para projetos de MDL?",
        "definicao": "Fator anual da margem de construção publicado pelo MCTI nas planilhas do MDL.",
        "unidade": "tCO2/MWh",
        "grao_geografico": "SIN",
        "grao_temporal": "ano",
        "fontes": _MCTI,
        "regra_agregacao": "Nenhuma: valor oficial.",
        "versao_formula": "1",
        "natureza_fonte": "ESTIMADO",
        "natureza_transformacao": "ESTIMADO",
        "dimensoes": ["ano"],
        "regras_comparabilidade": ["Não comparar com o fator médio."],
        "regra_cobertura": "Anos com valor publicado; o ano corrente fica ausente com a nota da fonte (\"será disponibilizado no início\" do ano seguinte).",
        "politica_ausencia": "Texto no lugar do valor (\"a ser publicado\") = ausência com a nota da fonte.",
        "validacoes": ["0 ≤ fator < 2 tCO2/MWh.", "Valor atípico conferido na planilha original antes de publicar (ex.: 0,0028 em 2017, célula G4 da planilha do MCTI)."],
        "limitacoes": [_NATUREZA_MCTI, "Método do MDL.", "Revisões declaradas pela fonte (valor anterior e corrigido) publicadas junto da série."],
        "gold": _GOLD, "paginas": _PAG,
    },
]
